### ISSUE TITLE
[Priority-low] Icons cache update issue

### ISSUE THREAD

**Issue by viewizard** [keeferrourke/la-capitaine-icon-theme#1]
I tested your icons in portage package system (Gentoo) with local ebuild, and found, that the gtk icon cache update utility don't like icons with space(s) in the name (can't create icons cache file). Here is some icons I found (I could miss some, so, please, also check it by yourself):

/apps/scalable/Amazon Cloud Reader-read.amazon.com.svg
/apps/scalable/Google docs-docs.google.com.svg
/apps/scalable/Yahoo Mail-mail.yahoo.com.svg
/apps/scalable/Launcher 2.svg
/apps/scalable/5C12_World of Warcraft Launcher.0.svg
/apps/scalable/56B4_Battle.net Launcher.0.svg

Could you please change spaces in the icons name on other symbols?

**Comment by keeferrourke** [comment]
I fixed those file names and removed Launcher 2. Thanks so much for taking interest in my projects and packaging it :)

**Comment by keeferrourke** [comment]
Reopening this because I was so quick to close it this morning. Possibly other file names need to be fixed, so I'm going to take a better look at this.

**Comment by viewizard** [comment]
Just in time. :-) 
Not file name issue, but too close, so, I post here instead of create new issue.

Just found "QA Notice" in portage (Gentoo package system) logs:
 * QA Notice: Symbolic link /usr/share/icons/la-capitaine/apps/scalable/clamav.svg points to /usr/share/icons/la-capitaine/apps/scalable/security-medium.svg which does not exist.
>>> /usr/share/icons/la-capitaine/apps/scalable/clamav.svg -> security-medium.svg
 * QA Notice: Symbolic link /usr/share/icons/la-capitaine/apps/scalable/clamtk.svg points to /usr/share/icons/la-capitaine/apps/scalable/security-medium.svg which does not exist.
>>> /usr/share/icons/la-capitaine/apps/scalable/clamtk.svg -> security-medium.svg

Looks like ./apps/scalable/clamav.svg and ./apps/scalable/clamtk.svg symlinks are broken.

**Comment by keeferrourke** [comment]
Just pushed a fix for the broken clamav and clamtk symlinks; security-* icons copied over from status/scalable to apps/scalable.

**Comment by keeferrourke** [comment]
@viewizard is this still a problem?

**Comment by viewizard** [comment]
I don't see any warnings/errors during cache update process for now. I think, this issue fixed for sure.

**Comment by keeferrourke** [comment]
Alright, I'm going to close this for now then :smile:
