### ISSUE TITLE
Chromium B.S.U. uses Chromium's icon

### ISSUE THREAD

**Issue by keeferrourke** [keeferrourke/la-capitaine-icon-theme#10]
Chromium B.S.U.:

    Icon=chromium-bsu

Chromium:
    
    Icon=chromium

Chromium B.S.U. is a game, Chromium is a browser. Design a new icon for `chromium-bsu` such that it is not confused with the browser.

**Comment by keeferrourke** [comment]
@Ufeldraku Chromium B.S.U. seems similar to a Space Invaders style arcade game; correct me if I'm wrong. Made a quick draft of an icon based on Numix Legacy, but I'm looking for feedback from someone who actually plays the game. 

![chromium-bsu-new](https://cloud.githubusercontent.com/assets/6888381/17221403/c7a95130-54c1-11e6-8d62-4ad3dfad7534.png) 

The new icon (sorry for small size png, Github doesn't like SVGs) hasn't been committed yet, so still subject to lots of revision or complete redesign before I made it part of La Capitaine.

**Comment by Ufeldraku** [comment]
Yeah, It's cool. The purple seems a nice touch, however, as the ship used is grey, with some blue and red.

**Comment by Ufeldraku** [comment]
http://d2oah9q9xdinv5.cloudfront.net/cache/images/games/1/15/14109/crop_940x740/screenshot2.jpg
Sorry, I didn't have red. My memory is rusty.

**Comment by keeferrourke** [comment]
Are the ships always vertically orientated? Should the icon reflect the actual orientation of the ships?

**Comment by Ufeldraku** [comment]
Yep, it should, the ships are always vertically orientated, so yeah the icon reflecting that would be cool.

**Comment by keeferrourke** [comment]
Fixed in commit 07ccf40.

**Comment by Ufeldraku** [comment]
Looks really cool!
