### ISSUE TITLE
Change Icon: Switchboard

### ISSUE THREAD

**Issue by btd1337** [keeferrourke/la-capitaine-icon-theme#101]
On elementary OS switchboard = System Settings

Switchboard -> Icon=preferences-desktop

Change this icon to point in Icon=preferences-system

**Comment by keeferrourke** [comment]
@btd1337 which icon is this? Is switchboard already in La Capitaine, what icon does it reference?

**Comment by btd1337** [comment]
Is specified: Switchboard -> Icon=preferences-desktop
