### ISSUE TITLE
[Bug] System applications icon not displayed in KDE menu

### ISSUE THREAD

**Issue by kun-zhou** [keeferrourke/la-capitaine-icon-theme#104]
In KDE Plasma 5.8, the menu directory `System` has a blank icon. I have experimented with it a bit. The correct directory entry for this menu directory is `/usr/share/desktop-directories/kf5-system.directory`. In the `.directory ` file, it writes `Icon=applications-system`. Now, this icon is clearly present in `/usr/share/icons/la-capitaine-icon-theme/apps/scalable`. I think the fact that it is a symlink is not the cause of the issue. The issue seems to be the name.

1. If I change it to an icon name that is nowhere to be found, say `icon_non_exist`, the icon for the menu directory will turn to the default kde's icon not found icon.

2. If I change it to another icon name, meanin  let `Icon=firefox`  in the `.directory` file, the menu directory shows up as firefox.

3. If I change the name of the icon in the theme icon folder to another, say `sys_icon` and let `Icon=sys_icon`  in the `.directory`, the icon shows up properly.

I am not sure why this is happening because if I change my icon theme to breeze, the menu directory's icon shows up correctly. To clarify, by menu directory, I mean the directory you see when you clock the KDE application launcher widget, usually at the left down corner of one's screen, click on Applications, and you see all the different menu directories such as `Multimedia`, `Games`, `Office`, etc.

**Comment by keeferrourke** [comment]
Can you post a screenshot of the issue?

...It's possible `applications-system` or indeed `applications-*` icons in La Capitaine are corrupt under KDE's SVG rendering engine &mdash; this has been an issue for some icons in the past. If this is the case, I'll redesign them.

**Comment by kun-zhou** [comment]
No problem. I have attached a screenshot. I would also like to clarify the following: If I change the file name of the icon, (not the icon itself, just the name in the scalable folder), and change the corresponding `.the directory` entry in the `desktop-directories` folder to update the icon it is mapping to, the icon will show up properly.


![screenshot_20170206_202125](https://cloud.githubusercontent.com/assets/19158151/22673741/e90f4052-eca9-11e6-8484-e185c7fbcf7d.png)

**Comment by keeferrourke** [comment]
@kun-zhou I'll take a look, but I won't be able to address this issue for at least a week. Midterms have snuck up on my again, and they're back with a vengance.

**Comment by kun-zhou** [comment]
@keeferrourke Haha, no worries. Thanks.

**Comment by demoy** [comment]
System menu icons visible after recents commits -
![screenshot_20170214_124832](https://cloud.githubusercontent.com/assets/2396524/22941559/ec72484c-f2b3-11e6-9c36-612cd2c35b7a.png)

![screenshot_20170214_124921](https://cloud.githubusercontent.com/assets/2396524/22941571/03eff474-f2b4-11e6-8872-9c52a769c7a6.png)

**Comment by kun-zhou** [comment]
Haha, thanks! I updated my icons from the git repo. Just wondering what is causing this issue? There are a couple of action button icons in `KWrite` that is experiencing the same issue. They are blank and the breeze fallback does not kick in. I would love to contribute if that's okay :)

**Comment by demoy** [comment]
Which Kwrite icons?
If they still dont appear post a screenshot in [issue 106](https://github.com/keeferrourke/la-capitaine-icon-theme/issues/106), and I'l try to find it.

**Comment by keeferrourke** [comment]
@demoy aside from the inconsistent look of the application icons in your screenshot, looks good. I'll try to fix the design of those icons later. Gonna close this issue, as it seems to have mostly merged with #106.

**Comment by keeferrourke** [comment]
@kun-zhou 
> I would love to contribute if that's okay :)

Absolutely welcome! Any and all contributions will always be considered :)

@demoy Though you didn't mention it, I've opened another issue regarding the inconsistent look of the application categories icons. See #107.
