### ISSUE TITLE
[Community Feedback] Help me decide on an address book redesign (please share your thoughts!)

### ISSUE THREAD

**Issue by keeferrourke** [keeferrourke/la-capitaine-icon-theme#109]
I just redesigned the `addressbook.svg` / `x-office-address-book.svg` icon, but am not sure which elements need shadowing. I'm going to leave this one up to the community to pick a design, since I'm agnostic to all of them. This will help shape La Capitaine moving forward!

As it is right now from commit 55359e7fe376eea75db0ae72c33b25b331bc376d; here the bookmark has no dimension, and the addressbook takes the form of a thin, flat-pressed book:
![addressbook1](https://cloud.githubusercontent.com/assets/6888381/23095632/f7469f00-f5da-11e6-9c53-cc9581012ba8.png)
Here, the bookmark has dimension and casts a shadow:
![addressbook2](https://cloud.githubusercontent.com/assets/6888381/23096344/7b56c010-f5e8-11e6-89b4-e507e4e30e4e.png)
And lastly, the addressbook is simply a flat card, with a bookmark that has a shadow:
![addressbook3](https://cloud.githubusercontent.com/assets/6888381/23096391/ac4afe38-f5e9-11e6-9b44-a96ddcdf8990.png)

Informal poll: please pick option 1, 2, or 3. If this issue receives comments by Sunday Feb 19, I'll default to option 1 and close the issue.

**Comment by RaitaroH** [comment]
Hmmm, not to late?
I prefer the first.

**Comment by Ufeldraku** [comment]
The first one looks better.

**Comment by keeferrourke** [comment]
The first icon it is!
