### ISSUE TITLE
[Request] Icon suggestions

### ISSUE THREAD

**Issue by Ufeldraku** [keeferrourke/la-capitaine-icon-theme#11]
MegaSync.
Jdownloader
Some of Xfce's utilities like the "Window Manager's Settings"

**Comment by keeferrourke** [comment]
Great suggestions but please leave the Icon names for each application here as well, and a reference for what each icon should look like if possible.

You'll find the name of the icons if you do: 

`cat /user/share/applications/megasync.desktop | grep 'Icon='`

Replace 'megasync' with whatever the name of your application's desktop file is.

**Comment by Ufeldraku** [comment]
Megasync | Icon=mega
Jdownloader | Icon=jdownloader

**Comment by keeferrourke** [comment]
Megasync and Jdownloader icons added in commit cf5549c.

Can I get the icon names for XFCE Window Manager Settings, and other XFCE Settings icons that are possibly unthemed?

**Comment by Ufeldraku** [comment]
Hmmmm
Gotta see my friend.

**Comment by Ufeldraku** [comment]
Your work's awesome.

**Comment by keeferrourke** [comment]
@Ufeldraku thanks for the kind words!

**Comment by keeferrourke** [comment]
@Ufeldraku any ideas on the XFCE settings stuff?

**Comment by Ufeldraku** [comment]
Gotta see man.

**Comment by Ufeldraku** [comment]
No clue man

**Comment by Ufeldraku** [comment]
And, by the way, the Xfce icon still is the default one.

**Comment by keeferrourke** [comment]
Okay I'll look into this, but it's probably going to be a while before I can test this properly on XFCE.

**Comment by auroszx** [comment]
Hello there. Just wanted to take the chance and request some icons in this thread instead of creating another one. One of them is the Xfce Window Manager Tweaks Settings (I believe this is the one OP is talking about). I'm attaching a [zip with the desktop files and their icons](https://github.com/keeferrourke/la-capitaine-icon-theme/files/402058/icon-requests.zip).

Also, another one of the icons is Firefox, or rather Firefox ESR, which sould be using the same icon but isn't. Adding a symlink called _firefox-esr_ (linking to firefox-svg) should fix that.

Thanks, and let me know if you need anything else for this.

**Comment by keeferrourke** [comment]
@auroszx thanks for the request! I'll take a look at the files you've attached this weekend, and try to have an update staged by monday; in the meantime I've symlinked firefox.svg --> firefox-esr.svg in commit  0122772 .

**Comment by keeferrourke** [comment]
@auroszx here's a preview of what's coming on Monday :smile: 
![cryfs](https://cloud.githubusercontent.com/assets/6888381/17442993/5aca53a2-5b06-11e6-80d4-f1345711227b.png) ![openarea](https://cloud.githubusercontent.com/assets/6888381/17443971/98689c50-5b0b-11e6-8944-cd346521ddd2.png) ![palemoon](https://cloud.githubusercontent.com/assets/6888381/17457709/c28ce37a-5bcd-11e6-993b-ce46d95c5968.png) ![xfca](https://cloud.githubusercontent.com/assets/6888381/17443026/6eb55a60-5b06-11e6-89c6-c79d3e1468b6.png)

New icons: 
cryfs.svg & cryfs-gui.svg;
openarena.svg & openarena128.svg;
palemoon.svg;
xfca.svg;

Updated icons: 
preferences-desktop-screensaver.svg



Symlinks: 
wmtweaks --> window-manager.svg; 
gnome-mpv.svg --> mpv.svg;
firefox-esr.svg --> firefox.svg;
pinta.svg --> accessories-painting.svg (probably temporary, unless you think this is sufficient)

**Comment by auroszx** [comment]
@keeferrourke thank you! Those look awesome. That icon for Pinta is pretty good, no need to make another unless you feel creative. Keep up the good work :+1:

**Comment by keeferrourke** [comment]
@auroszx check out commit 6f0213c

**Comment by auroszx** [comment]
@keeferrourke looking great, but openarena128.svg seems to be missing (or rather, a symlink to openarena.svg, which is at the right place of course). May I also request a symlink to transmission.svg called "transmission-remote-gtk.svg" ? This is for Transmission Remote, which should probably share the same icon.

**Comment by keeferrourke** [comment]
@auroszx sorry, I also noticed openarena128.svg symlink was missing, so I've fixed it in commit 9871de2. 
xcfa icon renamed to xcfa.svg in 1780cdf.
transmission.svg symlinked to transmission-gtk-remote.svg in 37914c1.

... haha gottagofast!!

**Comment by auroszx** [comment]
Great! Thank you. I would donate you something, but I may be as broke ;) _(Have a few bucks on Steam though, if you fancy something on sale)_

**Comment by keeferrourke** [comment]
@auroszx I'll never say no to free stuff :wink: &ndash; feel free to shoot me an [email](mailto:keefer.rourke@gmail.com) or otherwise [contact me](https://krourke.org/contact)! Thanks a million!

**Comment by Ufeldraku** [comment]
The battery icon in Mate stays the same, any updates on this?

**Comment by keeferrourke** [comment]
@Ufeldraku wrong issue: see #9.

**Comment by keeferrourke** [comment]
I believe all icons requested in this thread have been sufficiently taken care of. More tweaking may come in later releases, but I'm closing this for now.
