### ISSUE TITLE
XFCE4 Power Manager uses Adwaita icon 

### ISSUE THREAD

**Issue by ryzokuken** [keeferrourke/la-capitaine-icon-theme#119]
I am currently using XFCE4 in Xubuntu 16.04.2 LTS

All icons work perfectly (I have configured it to work for a dark theme) but the power manager indicator icon defaults to Adwaita and I cannot manage to fix it. If it helps, Numix and Paper work properly.

![screenshot_2017-03-05_15-01-14](https://cloud.githubusercontent.com/assets/13121330/23586125/f87544b8-01b4-11e7-8a01-dd56e3d705b5.png)

**Comment by keeferrourke** [comment]
Should be fixed now; working on my new xubuntu installation at the very least. Closing.
