### ISSUE TITLE
[request] New icons

### ISSUE THREAD

**Issue by meradoou** [keeferrourke/la-capitaine-icon-theme#12]
Hi,
I use it with KDE Plasma on arch:

- Clementine

> ./breeze/apps/48/clementine.svg
> ./breeze/apps/48/application-x-clementine.svg
> ./breeze/actions/16/x-clementine-artist.svg
> ./breeze/actions/16/x-clementine-shuffle.svg
> ./breeze/actions/22/x-clementine-shuffle.svg

- Umbrello

- KeepassX 2

**Comment by keeferrourke** [comment]
This is a duplicate issue, please see #11 for general icon requests.

**Comment by keeferrourke** [comment]
@meradoou KeePassX and KeePass2 are both themed on my system. If your system doesn't use [keepass.svg](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/keepass.svg), [keepass2.svg](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/keepass2.svg], or [keepassx.svg](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/keepassx.svg) then that's news to me. Please send me the 
   
    Icon=xxxxxxx

line from KeePass' *.desktop file located in `/usr/share/applications/`

**Comment by keeferrourke** [comment]
> apps/scalable/clementine.svg
> apps/scalable/application-x-clementine.svg

@meradoou both of these icons exist. I'll symlink `actions/16x16/media-playlist-shuffle.svg --> actions/16x16/x-clementine-shuffle.svg` in a commit this afternoon when I get home from work.

**Comment by keeferrourke** [comment]
Lastly, @meradoou when submitting icon requests, please submit the 
   
     Icon=xxxxxxx

line of your application's *.desktop file. You can find it easily by issuing
 
    cat /usr/share/applications/yourapplication.desktop |  grep Icon

And also provide a reference icon if at all possible. You'll need to do this for Umbrello.

**Comment by keeferrourke** [comment]
![umbrello](https://cloud.githubusercontent.com/assets/6888381/17350281/45fa2ae8-58f3-11e6-9be6-69e5f12023ab.png)
[umbrello-draft.svg](https://owncloud.krourke.org/index.php/s/6iZ7jNK1TSXEs45)

Umbrello concept icon, inspired by Umbrella Corp Logo from Resident Evil. This is a very rough draft and is gonna undergo a lot of revisions, but I'm looking for some initial feedback.

**Comment by keeferrourke** [comment]
@meradoou Sorry, this sorta fell off the priority list; but check out commit 577e0f1, `x-clementine-shuffle.svg` has been pushed. Still revising the umbrello icon, but I'll probably get that pushed tonight.

**Comment by keeferrourke** [comment]
closing this because I believe I've addressed this issue.
