### ISSUE TITLE
The battery icon on mate dont show it correctly on mate desktop (1.12.1 - Freebsd)  1.16.1 GTK3 Freebsd And Gentoo

### ISSUE THREAD

**Issue by javashin** [keeferrourke/la-capitaine-icon-theme#120]
![screenshot at 2017-03-05 21-31-29](https://cloud.githubusercontent.com/assets/15115613/23593958/0005755e-01ec-11e7-853a-24685944adaf.png)

I don't Know Why Is this Happening But i Failed Trying to Fix It. On Xfce4 amd Gnome 3.22 on Freebsd Works. I dont Know Why it Dont On Mate-Desktop
i hope this gets fixed i like this icon theme a lot.

**Comment by keeferrourke** [comment]
Oof. Looks like there's a *lot* of unthemed icons on your desktop. Any chance you could compile a list of them and post them here?

The battery issue is likely related to #9, #119, and/or #52 . I'm guessing that (similar to XFCE), MATE might be expecting the missing `status/scalable/gpm-primary-*` icons... I'll try to get a fix up soon (maybe by the end of the week if assignments go well)

**Comment by javashin** [comment]
Well I Dont have Gentoo Any more On FreeBSD the battery icon its working but only when the battery is not full when its at 100 % the icon looks like adwaita

**Comment by javashin** [comment]
Well I Dont have Gentoo Any more On FreeBSD the battery icon its working but only when the battery is not full when its at 100 % the icon looks like adwaita

**Comment by javashin** [comment]
![screenshot at 2017-03-08 05-03-13](https://cloud.githubusercontent.com/assets/15115613/23697084/bdf9c0c0-03bc-11e7-9e87-da9d6d8d45ce.png)

**Comment by javashin** [comment]
![screenshot at 2017-03-08 05-41-53](https://cloud.githubusercontent.com/assets/15115613/23698568/6cd6bea4-03c2-11e7-886e-fa8ee94f46e7.png)

**Comment by keeferrourke** [comment]
:+1: I will look into it.

**Comment by javashin** [comment]
I reinstalled gentoo and the icon pack works fine on xfce gnome and cinnamon and the same problem on freebsd with the battery is there too the battery icon theme is wrong when the battery is full its uses adwaita icon when its discharging and charging not 100 % the icon is ok.
![screenshot at 2017-03-13 18-10-08](https://cloud.githubusercontent.com/assets/15115613/23877478/ea4f1bce-0818-11e7-8e97-65938261ed27.png)

**Comment by surajmandalcell** [comment]
same problem here any updates?

**Comment by keeferrourke** [comment]
No updates right now. Feel free to look into it; my focus is mostly on exams right now and I don't have time to test MATE/XFCE at the moment.

**Comment by surajmandalcell** [comment]
I have exams too at this time of the year xD 
Later then m8

**Comment by javashin** [comment]
hello any updates on this ?

**Comment by keeferrourke** [comment]
@javashin I'm in the middle of finals, so I'll have some more time on my hands in a few weeks. I ask that you just sit tight for now, an update will come soon.

**Comment by surajmandalcell** [comment]
hum....
