### ISSUE TITLE
[Request] IntelliJ Idea

### ISSUE THREAD

**Issue by elvisd** [keeferrourke/la-capitaine-icon-theme#121]

**Comment by keeferrourke** [comment]
La Capitaine already includes several IntejjiJ IDEs. A few more are tabled to be included when I get a chance to add them. Please clarify if this is not the issue, and follow the request format outlined in the Wiki [here](https://github.com/keeferrourke/la-capitaine-icon-theme/wiki/Submitting-Icon-Requests).

This is likely a duplicate of issues https://github.com/keeferrourke/la-capitaine-icon-theme/issues/32 and https://github.com/keeferrourke/la-capitaine-icon-theme/issues/102.

**Comment by elvisd** [comment]
Edited the .desktop file to point to intellij icon (mine was intellij-idea)
