### ISSUE TITLE
Add new places icons

### ISSUE THREAD

**Issue by USBA** [keeferrourke/la-capitaine-icon-theme#122]
Please add new places (folder) icons. Current icons don't match with the beauty of la-capitaine's app icons.

**Comment by USBA** [comment]
This is my suggestion.   
![screenshot from 2017-03-07 18-18-53](https://cloud.githubusercontent.com/assets/19838220/23657127/a7ffa9e2-0362-11e7-80a5-05947fe5d9b9.png)

Download these places (folder) icons ---> 
[places-new.zip](https://github.com/keeferrourke/la-capitaine-icon-theme/files/824388/places-new.zip)

**Comment by keeferrourke** [comment]
I'll kindly disagree here. Feel free to use custom places icons on your machine, but I think the current folder icons are very nice, and I've put a fair bit of work into them. I shouldn't be making any changes to them in the foreseeable future, so even if you're using the latest git version, your local copy should not have conflicts when you pull.

Cheers, and thanks for the suggestion.

**Comment by demoy** [comment]
@keeferrourke  the public folder and template folder in la-capitaine currently are not themed maybe copy the grapheme (I think thats the word) without the folder change.

**Comment by keeferrourke** [comment]
@demoy I will open a separate issue and add the missing folders with emblems that are more inline with the current material-ish design.

**Comment by demoy** [comment]
Sry your right, kde just ignores them (even in breeze).

**Comment by USBA** [comment]
It's OK @keeferrourke . Thanks for your amazing work. I love this theme sooo much.
