### ISSUE TITLE
Icon Request: Incomplete downloads icon

### ISSUE THREAD

**Issue by demoy** [keeferrourke/la-capitaine-icon-theme#123]
In Firefox, Qupzilla, Transmission, Youtube-dl, etc; incomplete downloads have _.part_ added to their extensions, la-capitaine currently does not style these extensions.

 Here the breeze icon that la-capitaine defaults to in KDE:
![screenshot_20170308_095848](https://cloud.githubusercontent.com/assets/2396524/23715812/bc97ec86-03e2-11e7-98cd-8995ea4022ef.png)

A related extension is _.crdownload_ which is exclusive [as far as I know] to Chrome-browser.

**Comment by keeferrourke** [comment]
Strange, the icon preview of .part files show are themed on my machine (albeit there could be a better icon). The mimetype for both `*.part` and `*.crdownload` files is `application/x-partial-download`.

To do:
- [ ] redesign/add mimetype icon for `application/x-partial-download` files
