### ISSUE TITLE
Icon Request: Nylas N1 (Nylas Mail / Nylas Pro)

### ISSUE THREAD

**Issue by jcuenod** [keeferrourke/la-capitaine-icon-theme#124]
**Application:** Nylas N1 (not sure how this will change in the future with "Nylas Pro" and "Nylas Mail")
**Icon name:** nylas
**Context:** Mail client
**Icon reference:**
![image](https://cloud.githubusercontent.com/assets/4253884/23760574/c7a9370a-04b5-11e7-9174-bd37be246dda.png)

See also:
![image](https://cloud.githubusercontent.com/assets/4253884/23760598/d7d63c7c-04b5-11e7-8b6a-ba49b68c5097.png)
![image](https://cloud.githubusercontent.com/assets/4253884/23760603/db875b44-04b5-11e7-939a-3d2779511d44.png)
![image](https://cloud.githubusercontent.com/assets/4253884/23760608/e20a37e8-04b5-11e7-9c7c-7b29b5c61891.png)

**Comment by keeferrourke** [comment]
This was a quick icon to make, let me know what you think before I commit it.

![nylas](https://cloud.githubusercontent.com/assets/6888381/23766881/8b0f47e8-04d4-11e7-85d7-6766aa7cfd13.png)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`nylas.svg`

**Comment by jcuenod** [comment]
Looks good, the only thing I might suggest is changing the gradient in the background to match the reference gradient - but I realise that may not match the palette you have in mind for the icon set.

**Comment by keeferrourke** [comment]
I based it off of this:
 ![image](https://cloud.githubusercontent.com/assets/4253884/23760598/d7d63c7c-04b5-11e7-8b6a-ba49b68c5097.png)

But here is another version with the alternate gradient.
![nylas_alt](https://cloud.githubusercontent.com/assets/6888381/23770401/e4313f14-04e0-11e7-944b-3657db730e1b.png)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`nylas.svg`

**Comment by jcuenod** [comment]
I prefer the new one although now I'm also wondering whether it would be better to have the central bars a little brighter - this is what happens when you open design to suggestions ;) - should have just told me that's how it is... Nice job though, I really think this is one of the best icon themes for gnomeshell

**Comment by keeferrourke** [comment]
Ha well I don't mind putting in a little extra work to craft something everyone likes :)

The central bars are now just `#ffffff`, as bright as I can make them lol. This will be the icon that get's committed ;)
![nylas](https://cloud.githubusercontent.com/assets/6888381/23771667/e58ed93e-04e5-11e7-8684-7471e6bfc37f.png)

**Comment by jcuenod** [comment]
Nice, glad it's committed :)
It took me a while to figure out the 90% opacity thing - was wondering why it didn't look #fff hehe.
It's good though, I like it (and I'll just submit an issue or a pull request if I change my mind)...

**Comment by keeferrourke** [comment]
> I'll just submit an issue or a pull request if I change my mind

Always welcomed :P
