### ISSUE TITLE
Missing symlinks for loading icons in cinnamon [Wtih fix]

### ISSUE THREAD

**Issue by RaitaroH** [keeferrourke/la-capitaine-icon-theme#126]
Ok, so here is the issue: when an image/folder loads it has a default loading image. I didn't notice it was inheriting from another of my icon sets until now. Here is how to fix it:

`cd /actions/22x22/`
`ln -fs document-open-recent.svg image-loading.svg`
`ln -fs document-open-recent.svg gnome-fs-loading-icon.svg`

Now, you could use another icon for this but I just used one you already had :P 

Off-topic: In case you want them, I have made a few more icons.

**Comment by keeferrourke** [comment]
Added the missing icons in commit 8dae6b6.

If you want to share more of the icons you've made, just append them to your issue as a comment. Your contributions are always welcome, just try to keep them in the same place :)

Cheers!
