### ISSUE TITLE
[Bug] transmission icon wont scale.

### ISSUE THREAD

**Issue by demoy** [keeferrourke/la-capitaine-icon-theme#128]
![screenshot_20170313_174048](https://cloud.githubusercontent.com/assets/2396524/23878251/57c8b386-0814-11e7-8c89-99596b9debfc.png)

**Comment by keeferrourke** [comment]
Probably gonna need more information here, I don't have this issue under GNOME.

**Comment by demoy** [comment]
@keeferrourke Your right the icon, scale in other applications.  I dont understand why its the only icon that fails to scale in the taskbar. I'm closing this since I don't know how to proceed.

**Comment by keeferrourke** [comment]
@demoy what is it supposed to look like?

**Comment by demoy** [comment]
![screenshot_20170314_135015](https://cloud.githubusercontent.com/assets/2396524/23917398/311fc702-08bd-11e7-9073-59c2c5cc5737.png) @DarkknightAK here is qupzilla in the same taskbar.
