### ISSUE TITLE
[Request] Icon for WizNote

### ISSUE THREAD

**Issue by btd1337** [keeferrourke/la-capitaine-icon-theme#13]
Can you associate this icon (http://imgh.us/wiznote.svg) to Wiznote program?

Icon=wiznote

Icon for you -> http://imgh.us/wiznote.svg

**Comment by keeferrourke** [comment]
@btd1337 I can add an icon for Wiznote for sure, but I would rather go with something more along the lines of this: 

![wiznote-draft svg](https://cloud.githubusercontent.com/assets/6888381/17285071/49afa89a-578e-11e6-82c5-475417e53e0a.png)

[wiznote-draft.svg](https://owncloud.krourke.org/index.php/s/aKCz5YyBqNDswOj)

It's much more consistent with the style of other editors and notes/documents application icons in La Capitaine. The icon you are suggesting would be for editing ebooks or other similar formats &ndash; as you literally just pulled and renamed the [calibre-ebook-edit.svg](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/calibre-ebook-edit.svg) icon.

**Comment by keeferrourke** [comment]
Closing, see commit: 33170ec.
