### ISSUE TITLE
qbittorrent icon in notification not changing KDE

### ISSUE THREAD

**Issue by now-im** [keeferrourke/la-capitaine-icon-theme#130]
As you can see, in KDE task bar qbittorrent icon has changed but not in the notification are. I am not sure whether it is an issue with qbittorrent or not.

![screenshot_20170319_004348](https://cloud.githubusercontent.com/assets/22009014/24074978/5af83a36-0c3d-11e7-8800-13ba6161acc2.png)

**Comment by keeferrourke** [comment]
This is likely an issue with qbittorrent. It could probably be fixed if support was added to https://github.com/bil-elmoussaoui/Hardcode-Tray

cc: @bil-elmoussaoui

probably related to isse: #125

**Comment by keeferrourke** [comment]
@now-im if possible, also submit a bug report to the qbittorrent project, and ask them to update their packages' desktop files

**Comment by bil-elmoussaoui** [comment]
It was an upstream issue of qbittorent and I have fixed it upstream few weeks ago. As far as I can remember, the new icon name is qbittorent-tray see my PR  https://github.com/qbittorrent/qBittorrent/pull/6249

**Comment by now-im** [comment]
So, in my understanding the problem should be solved with icon path changing?

**Comment by now-im** [comment]
Closing the issue as it seems to be a problem in qbittorrent.

**Comment by bil-elmoussaoui** [comment]
@now-im It's not a problem with qbitorrent, the icon name was changed by me recently; using the new icon name will fix it ;)

**Comment by now-im** [comment]
I don't know how to manually change icon name. Using the Monochrome(Dark Theme) for tray icon style. At least that suits my taste.

**Comment by now-im** [comment]
With version 4, qbittorrent is using SVG file for every icon including tray.

**Comment by keeferrourke** [comment]
Sorry does anything need to be changed on this issue now?

**Comment by now-im** [comment]
No. I just wanted to let you know. They have redesigned couple of things. This issue will be automatically fixed in hard coded tray support.
