### ISSUE TITLE
Terminix was renamed to Tilix..

### ISSUE THREAD

**Issue by alex285** [keeferrourke/la-capitaine-icon-theme#131]
..thus can you please link to Tilix?

**Comment by keeferrourke** [comment]
Yup, this has been requested a few times already. Thanks for opening the issue though so I can track this. Is the new icon simply `tilix.svg`?

**Comment by alex285** [comment]
yeah, you need to rename this, and the gexperts.. link. i have done it already locally and it works, i just didnt pull request because it would be more work for you!

**Comment by keeferrourke** [comment]
Honestly pull requests are always welcome! Especially if you're just fixing symlinks.

**Comment by keeferrourke** [comment]
oops :^)
