### ISSUE TITLE
Tune down the brightness of folder colors

### ISSUE THREAD

**Issue by alex285** [keeferrourke/la-capitaine-icon-theme#132]
can you please reduce a little bit the lightness of the the additional folder colors? it is stronger than the defaults one (blue), specially on green

**Comment by keeferrourke** [comment]
In particular, which folder colour options do you find to be too bright? Can you provide an alternative colour pallette that you would prefer?

**Comment by alex285** [comment]
@keeferrourke basically you can close this issue if you want to, because when i opened it, i tried to re-color all my folders. for example if i make them all "Green" it is really bright and annoying on eyes. and take into account that depends on the monitor too

but in regular use, colorizing just 2-3 folders that you want to highlight works fine

however i still think that the "brightness" and "power" level of additional folders doesn't match the Blue ones. The colors which are wrong (IMO) are the 
1. Green
2. Red
3. Pink

**Comment by keeferrourke** [comment]
I'll mess around with the colour palette again some time this week. I'm in the middle of exams (why am I always in the middle of exams!), but I'll be sure to get to this when I have some spare time. Cheers!

**Comment by keeferrourke** [comment]
New folder designs were added as of commit 0f96138c16aa2708e2b1151c10d4a75bddd64033. Colour gradients and icon shape have been changed. Green, red, and pink folder gradients have been carefully redone to be more consistent with the rest of the theme.
