### ISSUE TITLE
[Gnome] Theme directory categories/symbolic of theme la-capitaine-icon-theme has no size field

### ISSUE THREAD

**Issue by Paullux** [keeferrourke/la-capitaine-icon-theme#133]
Hello,

I am on ArchLinux with Gnome and i have this error :+1: 

(nautilus:17193): Gtk-WARNING **: Theme directory categories/symbolic of theme la-capitaine-icon-theme has no size field

**Comment by keeferrourke** [comment]
Hey there @Paullux can you make sure that you're using the latest version from git? There are no entries for a categories directory in the current [index.theme](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/index.theme) file. Cheers.

**Comment by Paullux** [comment]
I use the version of AUR

**Comment by keeferrourke** [comment]
I don't maintain that, so I can't be sure that it's always up to date. I know it was improperly flagged as out of date a while ago... not sure if that has an impact. Try cloning this repository, as instructed in the README and let me know if you still have issues.

**Comment by Paullux** [comment]
I installed your theme from your git now.
