### ISSUE TITLE
Request! Darktable, Kdenlive, Dropbox 

### ISSUE THREAD

**Issue by divinae** [keeferrourke/la-capitaine-icon-theme#136]
In my opinion Kdenlive and Darktable icons should have logos of this apps.
And please create dropbox in circle icon.

**Comment by keeferrourke** [comment]
Please follow the request format outlined in the wiki.

**Comment by keeferrourke** [comment]
Referring to issue #175 for Darktable request. Please use the new bug report templates for your other requests on this issues.
