### ISSUE TITLE
[question/maybe issue] Symbolics/Dark-Theme?

### ISSUE THREAD

**Issue by DroWnThePoor** [keeferrourke/la-capitaine-icon-theme#138]
Wondering if there are dark variants of many of these icons for a dark theme. 
For instance: Your theme changes much of Inkscape's icons and they are of the dark variant, which makes theme impossible to view with my dark theme.
![inkscape](https://cloud.githubusercontent.com/assets/16339020/25081033/d441604a-2315-11e7-87dd-e24c2c8ce55c.png)
Perhaps a line in the config I could change?

**Comment by RaitaroH** [comment]
Have you configured the theme? It looks to me like you haven't. Just go to the installed folder and ./configure. (I also recloned the icon pack just to see if there was an issue in the latter commits; there aren't)
Here is what Inkscape looks like to me:
With the dark variant:
![screenshot from 2017-04-17 10 23 36](https://cloud.githubusercontent.com/assets/19552720/25082225/f6d9008a-2357-11e7-92e9-d8c35cf26b96.png)
With the default variant:
![screenshot from 2017-04-17 10 23 20](https://cloud.githubusercontent.com/assets/19552720/25082224/f6d80068-2357-11e7-9999-59de573a680d.png)

**Comment by DroWnThePoor** [comment]
I think I just cloned it, when I started I wasn't using a dark theme so it never even occurred to me, thank you I will configure it immediately.

**Comment by keeferrourke** [comment]
Thanks for checking this out. Make sure that you run `$HOME/.icons/la-capitaine-icon-theme/configure` when you change your GTK theme.

Alternatively, clone the theme into two directories, and configure one to be dark and the other to be light; this will allow for quicker theme switching.
