### ISSUE TITLE
Propose for new Thunderbird Icon

### ISSUE THREAD

**Issue by camux** [keeferrourke/la-capitaine-icon-theme#139]
IMHO, this version of thunderbird Icon is better that current one

https://icons8.com/web-app/38697/thunderbird

**Comment by keeferrourke** [comment]
okay... great. but why is that one better?

I'm all for improving the icon, but... what exactly is wrong with the current one?

**Comment by keeferrourke** [comment]
Closing due to over three months inactivity.
