### ISSUE TITLE
Some icons that need to be symlinked (Linux Mint default apps)

### ISSUE THREAD

**Issue by linusg** [keeferrourke/la-capitaine-icon-theme#142]
Just for reference, as I wrote in my Email:

`apps/scalable/mintdrivers.svg` -> `apps/scalable/jockey.svg`
`apps/scalable/xplayer.svg` -> `apps/scalable/multimedia-video-player.svg`
`apps/scalable/xviewer.svg` -> `apps/scalable/accessories-image-viewer.svg`
`apps/scalable/pix.svg` -> `apps/scalable/accessories-image-viewer.svg`

These need to be symlinked to get themed on Linux Mint, the driver manager, the default media player, the default image viewer and a photo management app.

**Comment by keeferrourke** [comment]
This should be fixed in commits ca29d149fc2d00fec4ec00829924a30f24008f3d and 0ffd452d86e4c7f94ccdca7be53c35a70a8e5931.
