### ISSUE TITLE
Python icons: Split into Python 2 and Python 3 icons and add Symlinks for 3.5 and 3.6

### ISSUE THREAD

**Issue by linusg** [keeferrourke/la-capitaine-icon-theme#143]
There's just one Python icon, however, most Linux distributions have both Python 2 and 3 installed by default. I think it would be useful to make an icon `python2.svg` and `python3.svg`, each with a small version number indicator. The `python.svg` icon can be kept, for example `idle.svg` symlinks to it. I'm not asking for a redesign, just a split of the icon and a small badge for the two new ones.

The change would mean that we would have to re-symlink the `python2.x.svg` and `python3.x.svg` files:

`apps/scalable/python2.6.svg` -> `apps/scalable/python2.svg`
`apps/scalable/python2.7.svg` -> `apps/scalable/python2.svg`
`apps/scalable/python3.0.svg` -> `apps/scalable/python3.svg`
`apps/scalable/python3.1.svg` -> `apps/scalable/python3.svg`
`apps/scalable/python3.2.svg` -> `apps/scalable/python3.svg`
`apps/scalable/python3.3.svg` -> `apps/scalable/python3.svg`
`apps/scalable/python3.4.svg` -> `apps/scalable/python3.svg`

New: Python 3.5 and 3.6:
`apps/scalable/python3.5.svg` -> `apps/scalable/python3.svg`
`apps/scalable/python3.6.svg` -> `apps/scalable/python3.svg`

**Comment by keeferrourke** [comment]
Hey @linusg, sorry for the super late response here. I restructured the symlinks back in commit 4f186bc6f9cad2c20d31e7198c597f5762829fd0, but only just got around to the redesign now.

Is this something like what you're looking for? Did I get the version indicator idea right? Let me know and I'll refine the design more before I finalize the commits.

`python.svg` | `python2.svg` | `python3.svg`
--|--|--
![python](https://cloud.githubusercontent.com/assets/6888381/25685915/92d6ac3e-3038-11e7-984d-8021f030cc21.png) | ![python2](https://cloud.githubusercontent.com/assets/6888381/25685914/92d6714c-3038-11e7-9b1c-fa5bdf9f81b7.png) | ![python3](https://cloud.githubusercontent.com/assets/6888381/25685913/92cfc22a-3038-11e7-83e3-28f2b42efb70.png)

**Comment by linusg** [comment]
This is not what I had in mind but definitively looks neat! I was thinking of  a dark indicator as with the dark python logo background of the old icon, but this is just perfect too.

Just one minor issue: could you maybe just decrease the indicator's radius so it does not touch the python's eye? Like really a little, just a few px (or whatever unit you have for your SVGs). An then move it the amount of decreased radius to the bottom and left, so it fits into an outer square like it's currently doing.

**Comment by linusg** [comment]
Eh, I meant bottom and right... you'll get what I'm trying to express here :wink:

**Comment by keeferrourke** [comment]
Updated and ready to push; sorry for the delay.

`python2.svg` | `python3.svg`
--|--
![python2](https://cloud.githubusercontent.com/assets/6888381/25763733/86ce4912-31b2-11e7-9a0d-921dce8574df.png) | ![python3](https://cloud.githubusercontent.com/assets/6888381/25763731/86b0b118-31b2-11e7-924c-dba150676e7d.png)

**Comment by keeferrourke** [comment]
I may revisit this later, but will stick with this design for now. I might switch the badge to look like the chrome "beta" label but will need to be in a better state of mind for design. Perhaps sometime next week :stuck_out_tongue:

**Comment by linusg** [comment]
IMHO you can leave it as it's now. Looks awesome!
![grafik](https://cloud.githubusercontent.com/assets/19366641/25771475/218f5f36-3253-11e7-91d3-c8ec8cc24276.png)

**Comment by FriendlyTroll** [comment]
Hi all,

there is a similiar issue when only the python 2 files are represented by python icons. If you have a python 3 script it is represented by a normal text icon.

My workaround for this is to copy the existing
```
~/.icons/la-capitaine-icon-theme/mimetypes/scalable/text-x-python.svg
```
to 
```
~/.icons/la-capitaine-icon-theme/mimetypes/scalable/text-x-python3.svg
```
and rebuilding the icon cache

```
gtk-update-icon-cache -f -t ~/.icons/la-capitaine-icon-theme/
```

Tested on Xubuntu 18.04.
