### ISSUE TITLE
Permission to link to your icon theme

### ISSUE THREAD

**Issue by bill-mavromatis** [keeferrourke/la-capitaine-icon-theme#146]
Hey Keefer, 

I am writing a layout manager for GNOME and I like your icons. I hope you are OK with my script linking to your icon theme.

Here is the said script: https://github.com/bill-mavromatis/gnome-layout-manager

I will add you on the credits too, mentioning the relevant licence. Please let me know if it's fine.

Regards,
Bill

**Comment by keeferrourke** [comment]
Hey Bill,

Absolutely feel free to link to this theme! Sorry for the late response! It would be awesome if you did so :D

**Comment by bill-mavromatis** [comment]
Thank you! I have the changes done on my testing branch, and will merge soon.
