### ISSUE TITLE
[Issue] using custom All Apps icon results in white circle

### ISSUE THREAD

**Issue by GNOME-IS-LIFE** [keeferrourke/la-capitaine-icon-theme#148]
I am trying to get a somewhat mix of a GNOME & MAC inspired look. On my way to this journey, a pothole stopped me. Since the default 9 square button of "All Apps" looks really boring, I wanted a La Capitaine style All Apps icon (will later file a request). but till then I used the rocket launcher icon from the United theme (a .svg file) and copied it into ~/.local/share/icons/La-Capitaine/actions/symbolic under the name "view-app-grid-symbolic.svg" and restarted my laptop, only to find out a white circle is the All Apps icon instead!! 
Since I LOVE your icon theme, I REALLY do not want to switch to another icon theme, yet i really want this all apps icon of mine to work.

**Comment by keeferrourke** [comment]
Could you provide screenshots to better describe your issue? I'd be happy to help you.

**Comment by keeferrourke** [comment]
@GNOME-IS-LIFE any word on this? I will close this issue soon if I don't hear anything from you.

**Comment by keeferrourke** [comment]
I'm going to close this due to inactivity and unclarity of the original problem.
