### ISSUE TITLE
[Request] icon for "All Apps"

### ISSUE THREAD

**Issue by GNOME-IS-LIFE** [keeferrourke/la-capitaine-icon-theme#149]
in my previous Issue, i wrote how I couldn't get a custom "All Apps" icon to work properly. Hear I have a different approach. Can you AWESOME devs please integrate an All Apps icon in this icon set? I would be grateful!

**Comment by linusg** [comment]
Could you please follow the example icon request [described here](https://github.com/keeferrourke/la-capitaine-icon-theme/wiki/Submitting-Icon-Requests), otherwise it's hard to start working on it.

**Comment by GNOME-IS-LIFE** [comment]
ok...

**Comment by linusg** [comment]
No need to close this, just add another comment including all the necessary information :wink:
