### ISSUE TITLE
Respect the original creators of icons

### ISSUE THREAD

**Issue by fabianalexisinostroza** [keeferrourke/la-capitaine-icon-theme#15]
ok, the artworks are GPL or CC licences, but you dont give credit to the real artworkers in your credits file.

"The creators of El General, off which La Capitaine is based https://github.com/akaifi/El-General-Gnome" // no, i'm the creator of Antu (old "El General) you link a fork not the original artworker mention

And you use super flat remix for folder icons and i don't see the mention to these artworker.

**Comment by keeferrourke** [comment]
@fabianalexisinostroza I forked from that branch of the project, not Antu. You also took your project repository down. If you have a better link for me to provide in the credits file, I'll be more than happy to do so. Would a link to your Github page be sufficient?

Failure to mention Super Flat Remix is an accidental omission on my part; I'm going to fix that immediately.

**Comment by fabianalexisinostroza** [comment]
for my icons use this https://github.com/fabianalexisinostroza/Antu

**Comment by keeferrourke** [comment]
Perfect, thanks for helping me address the issue. I just pushed commit 716cbd9. Please let me know if this is sufficient &ndash; thanks for the amazing work that this project is based on :)

**Comment by fabianalexisinostroza** [comment]
nice, this is better now ;)
