### ISSUE TITLE
LibreOffice 5.3.3 icons not modified

### ISSUE THREAD

**Issue by 1Claude** [keeferrourke/la-capitaine-icon-theme#151]
Hi,

I'm on Fedora 25 Workstation.

I installed LibreOffice 5.3.3 by downloading the .rpm from the LibreOffice web site.

LibreOffice suite is installed in /opt

Unlike other icons theme I tried, La Capitaine is not modifying the whole LibreOffice set of icons (Writer, Calc, Draw, etc.) 

I use the Copr repository. But I also tried to just copy from Git La Capitaine in /usr/share/icons with the same result.

Can you do something about it ? 

Thanks.

**Comment by linusg** [comment]
Will [this troubleshooting guide](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/Troubleshooting.md) help you?

**Comment by keeferrourke** [comment]
@1Claude you should try installing LibreOffice from the official Fedora repositories. Binaries installed from websites usually do not have *.desktop files that allow for easy theming.

LibreOffice 5.3 is not yet packaged on Fedora, but it should be soon enough if you're patient. In the meantime, either manually edit the *.desktop files located in `/usr/share/applications` according to the troubleshooting guide that @linusg linked to, or do the following:

```sh
sudo dnf remove libreoffice*
sudo dnf install libreoffice
```

**Comment by keeferrourke** [comment]
Closing this because I can't do anything about it, but feel free to discuss.

**Comment by 1Claude** [comment]
Tell me why icons like Numix Circle, Paper and others  can modify LibreOffice and not La Capitaine.

That's the question.

And please, don't ask me to install an older version of LibreOfice to solve La Capitaine problem.

**Comment by linusg** [comment]
See, the fault is not on La Capitaine's site. @keeferrourke already explained what to do. It must be your setup - works fine for me:

![libreoffice](https://cloud.githubusercontent.com/assets/19366641/26594415/d1450a1c-4567-11e7-9a52-61e9655b4e90.png)

To narrow down the problem, may you post the content of some LibreOffice .desktop files?
And maybe a screenshot of the icons with Numix enabled and one with La Capitaine enabled? Hard to believe, but behind the scenes most icons themes do the same things...

**Comment by keeferrourke** [comment]
@1Claude please paste the content of your `libreoffice-*.desktop` files. You will likley find them under `/usr/share/applications`.

**Comment by 1Claude** [comment]
What do you mean by "content" ?

By right clicking on Writer, for example, if it's what you mean, here's what I get in the /usr/share/applications

/opt/libreoffice5.3/share/xdg/writer.desktop

**Comment by keeferrourke** [comment]
@1Claude a `*.desktop` file is a text file.

For instance, if your desktop file for Libreoffice Writer is located at `/opt/libreoffice5.3/share/xdg/writer.desktop`, as you say above, then paste the contents of that file here. Do the same for the other desktop files.

**Comment by 1Claude** [comment]
I'm just going to paste the begining, the rest is just translation...  
This is for the Writer App.

[Desktop Entry]
Version=1.0
Terminal=false
Icon=libreoffice5.3-writer
Type=Application
Categories=Office;WordProcessor;X-Red-Hat-Base;X-MandrivaLinux-Office-Wordprocessors;
Exec=libreoffice5.3 --writer %U
MimeType=application/vnd.oasis.opendocument.text;application/vnd.oasis.opendocument.text-template;application/vnd.oasis.opendocument.text-web;application/vnd.oasis.opendocument.text-master;application/vnd.oasis.opendocument.text-master-template;application/vnd.sun.xml.writer;application/vnd.sun.xml.writer.template;application/vnd.sun.xml.writer.global;application/msword;application/vnd.ms-word;application/x-doc;application/x-hwp;application/rtf;text/rtf;application/vnd.wordperfect;application/wordperfect;application/vnd.lotus-wordpro;application/vnd.openxmlformats-officedocument.wordprocessingml.document;application/vnd.ms-word.document.macroenabled.12;application/vnd.openxmlformats-officedocument.wordprocessingml.template;application/vnd.ms-word.template.macroenabled.12;application/vnd.ms-works;application/vnd.stardivision.writer-global;application/x-extension-txt;application/x-t602;text/plain;application/vnd.oasis.opendocument.text-flat-xml;application/x-fictionbook+xml;application/macwriteii;application/x-aportisdoc;application/prs.plucker;application/vnd.palm;application/clarisworks;application/x-sony-bbeb;application/x-abiword;application/x-iwork-pages-sffpages;application/x-mswrite;application/x-starwriter;
Name=LibreOffice 5.3 Writer

**Comment by 1Claude** [comment]
And this is for the Starter App.

[Desktop Entry]
Version=1.0
Terminal=false
NoDisplay=false
Icon=libreoffice5.3-startcenter
Type=Application
Categories=Office;X-Red-Hat-Base;X-SuSE-Core-Office;X-MandrivaLinux-Office-Other;
Exec=libreoffice5.3 %U
MimeType=application/vnd.openofficeorg.extension;x-scheme-handler/vnd.libreoffice.cmis;
Name=LibreOffice 5.3
GenericName=Office

...

StartupNotify=true
X-GIO-NoFuse=true
StartupWMClass=libreoffice-startcenter
X-KDE-Protocols=file,http,ftp,webdav

##Define Actions
Actions=Writer;Calc;Impress;Draw;Base;Math;

[Desktop Action Writer]
Name=Writer
Exec=libreoffice5.3 --writer

[Desktop Action Calc]
Name=Calc
Exec=libreoffice5.3 --calc

[Desktop Action Impress]
Name=Impress
Exec=libreoffice5.3 --impress

[Desktop Action Draw]
Name=Draw
Exec=libreoffice5.3 --draw

[Desktop Action Base]
Name=Base
Exec=libreoffice5.3 --base

[Desktop Action Math]
Name=Math
Exec=libreoffice5.3 --math

##End of actions menu

**Comment by 1Claude** [comment]
My wild and total noob guess in that field... is that maybe the icon set is looking for LibreOffice* only, without any numbers at the end, like LibreOffice5.3.

**Comment by keeferrourke** [comment]
yep, sorry for my initial assumptions. It does seem that Libreoffice is using new icon names for their RPM distribution. I will push a fix soon.

**Comment by 1Claude** [comment]
Just glad I can help.

And find out I'm not crazy.  :-)

**Comment by keeferrourke** [comment]
@1Claude try pulling the latest changes from git. Commit 17a5e71 should fix it :)

**Comment by 1Claude** [comment]
It works!

Thanks.

**Comment by linusg** [comment]
Please, please don't use a new icon name for every new minor version, please... @LibreOffice
