### ISSUE TITLE
Some more Symlinks required for Mint

### ISSUE THREAD

**Issue by linusg** [keeferrourke/la-capitaine-icon-theme#152]
I found some more symlinks to create on Linux Mint in order to get appropriate theming:

```
apps/scalable/mintsources.svg -> apps/scalable/pk-package-sources.svg
apps/scalable/mintupdate.svg -> apps/scalable/update-manager.svg
apps/scalable/mintinstall.svg -> apps/scalable/software-center.svg
apps/scalable/software-properties-mint.svg -> apps/scalable/software-center.svg
```

Basically most of these:
```
linus@linus-vaio /usr/share/applications $ ls *mint*
mintbackup.desktop       mintNanny.desktop             mintupdate.desktop
mintdrivers.desktop      mintsources.desktop           mintupdate-kde.desktop
mintinstall.desktop      mintstick.desktop             mintupload.desktop
mintinstall-kde.desktop  mintstick-format.desktop      mint-user-guide.desktop
mintlocale.desktop       mintstick-format-kde.desktop  mintwelcome.desktop
mintlocale-im.desktop    mintstick-kde.desktop
```
When including the symlinks, La Capitaine will support the following:

| Name | Before | After |
| -------- | ------------------------  | -------------------------------  |
| `mintbackup.desktop` | Y | Y |
| `mintdrivers.desktop` | Y | Y |
| `mintinstall.desktop` | N | Y |
| `mintinstall-kde.desktop` | N | Y |
| `mintlocale.desktop` | Y | Y |
| `mintlocale-im.desktop` | Y | Y |
| `mintNanny.desktop` | N | N |
| `mintsources.desktop` | N | Y |
| `mintstick.desktop` | Y | Y |
| `mintstick-format.desktop` | Y | Y |
| `mintstick-format-kde.desktop` | Y | Y |
| `mintstick-kde.desktop` | Y | Y |
| `mintupdate.desktop` | N | Y |
| `mintupdate-kde.desktop` | N | Y |
| `mintupload.desktop` | N | N |
| `mint-user-guide.desktop` | Y | Y |
| `mintwelcome.desktop` | N | N |

So we see, mintupload, mintnanny and mintwelcome are missing. But these are different issues. Yeah, GitHub checkboxes won't work in tables, so... Y/N.

And damn Mint devs :angry:

**Comment by keeferrourke** [comment]
> `apps/scalable/software-properties-mint.svg -> apps/scalable/software-center.svg`

Damn Mint devs... `software-properties.svg` already exists, and is like the standard for pretty well every gui environment. x.x

Working on a fix now.

**Comment by keeferrourke** [comment]
should be fixed.

**Comment by linusg** [comment]
I can confirm this is fixed. Thanks! :grinning: :tada: 

![fixed](https://cloud.githubusercontent.com/assets/19366641/26592513/4450ab12-4561-11e7-9a15-b488e2d60a4d.png)

Regarding the USB stuff, that's why I marked all Y/Y. I looked into all the files, just to be sure before submitting the issue.
