### ISSUE TITLE
[File type icon] OCaml

### ISSUE THREAD

**Issue by GiBg1aN** [keeferrourke/la-capitaine-icon-theme#153]
An icon for OCaml/SML source files(.ml) is missing.

**Comment by keeferrourke** [comment]
Please follow the request format outlined in the [wiki](https://github.com/keeferrourke/la-capitaine-icon-theme/wiki/Submitting-Icon-Requests).

At a minimum, I will need to know the mimetype for the OCaml files. Probably something like `text-x-ocaml` or similar.

**Comment by keeferrourke** [comment]
Closing due to nearly two months inactivity.
