### ISSUE TITLE
[Question] LightDM icons

### ISSUE THREAD

**Issue by LunaticLock** [keeferrourke/la-capitaine-icon-theme#155]
Why this icon set doesn't appear in the lightDM icons menu?

**Comment by keeferrourke** [comment]
I don't personally use lightdm, so I can't answer this. You'll need to provide a lot more information if want any form of help. I would suggest you read the [Arch Wiki](https://wiki.archlinux.org/index.php/LightDM#GTK.2B_greeter) for lightdm. You likely need to specify your GTK and icon themes in your lightdm conf file. Best of luck.
