### ISSUE TITLE
Optimization of icons

### ISSUE THREAD

**Issue by firefoxic** [keeferrourke/la-capitaine-icon-theme#156]
Hello!
How important is it for you to leave metadata (including grids and guides) from graphic editors in icon files? If this is not critical, then it would be possible to greatly reduce the size of these files (up to 80% sometimes).
If it's interesting, I can contribute.
There is a much more complicated option: keep the sources in the development branch, and in the master

**Comment by keeferrourke** [comment]
Grid metadata isn't really all that important. I think I have up until this point been saving these files are Inkscape SVGs, but plain SVG would be a fine switch to make.

If you can help to strip the metadata from the project files to reduce the overall size this project takes in a filesystem, I'd appreciate it!

**Comment by firefoxic** [comment]
I use two automatic tools for optimization in different situations - svgo and svg-cleaner. But even after them, I often clean up a lot of things manually in the code. So, maybe it will not be fast, but I'll do it :)

**Comment by keeferrourke** [comment]
No worries about the timeline, I'm not in any hurry to get this done, but it would be nice to have :)
Cheers mate!

**Comment by keeferrourke** [comment]
@firefoxic I created a new branch for this issue: [la-capitaine-icon-theme:svgcleaner](https://github.com/keeferrourke/la-capitaine-icon-theme/tree/svgcleaner). Feel free to submit pull requests to that branch! :)

I also installed svgcleaner from cargo, for the purpose of local testing and cleaning. But this is low on my priority-list for time management.

**Comment by keeferrourke** [comment]
Currently working on cleaning the scalable application icons, which is the biggest of the beasts. Icon size reduction should be pushed tonight.
