### ISSUE TITLE
[Request] Etcher

### ISSUE THREAD

**Issue by benfeatherstone** [keeferrourke/la-capitaine-icon-theme#158]
Icon name: 9b523116af7c5f3f689627d267e06ad9.png

Context: Flash OS images to SD cards & USB drives

Icon reference: 

![9b523116af7c5f3f689627d267e06ad9](https://user-images.githubusercontent.com/7890249/27196236-41dafdc2-51cf-11e7-8e4c-87ea26f20059.png)

**appimagekit-Etcher.desktop content**

```
[Desktop Entry]
Name=Etcher
Exec="/home/ben/Documents/appimages/Etcher-1.0.0-rc.5-linux-x64.AppImage" %U
Comment=Flash OS images to SD cards & USB drives, safely and easily.
Icon=/home/ben/.cache/thumbnails/normal/9b523116af7c5f3f689627d267e06ad9.png
Type=Application
X-Desktop-File-Install-Version=0.22
X-AppImage-Comment=Generated by ./bin//etcher.wrapper
TryExec=/home/ben/Documents/appimages/Etcher-1.0.0-rc.5-linux-x64.AppImage
```

**Comment by linusg** [comment]
The ``.desktop`` file looks horrible, you may [take a look here](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/Troubleshooting.md) to understand how the theming works and works not. Same goes for some of your other Issues.

**Comment by benfeatherstone** [comment]
@linusg Clearly you have never used an appimage application before. That's what Etcher is, and that's what the .desktop file looks like that it creates. I previous had ```Icon=etcher``` in there before to make it work for Numix-Circle. 

Also I understand how theming works. However, the icon request instructions asked for the contents of the .desktop file. Not a modified version that might work to theme them. Also I searched the folder for these applications and found no result which is why I opened an issue. It's not a matter of the beginning used in the .desktop since one doesn't exist. However, if these icons do already exist and I missed them, I would have happy to have you point me in the right direction.

**Comment by linusg** [comment]
Indeed I haven't. Sorry for the confusion, and thanks for clarification :smiley: 

Am I right that these paths will always contain hardcoded icon paths? If so, it might be worth adding the application(s) to [this list here](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/Troubleshooting.md#an-application-on-my-desktop-isnt-themed).

Guess it's always fine adding a new icons to La Capitaine, but these hardcoded icons are far away from any standards. It's sad...

**Comment by benfeatherstone** [comment]
Yeah I am guessing that [Etcher](https://github.com/keeferrourke/la-capitaine-icon-theme/issues/158) and [Synergy](https://github.com/keeferrourke/la-capitaine-icon-theme/issues/161) would always be hard coded unless the developers change them to a better standard. (Maybe I will submit an issue on their projects as well)

It is sad that some applications hard code their icons. However, I am not opposed to changing the ```.desktop``` file to make icons work as long as there is one to use. :smiley:

**Comment by keeferrourke** [comment]
Would a symlink to [Usb Creator](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/usb-creator.svg) be sufficient? I feel like most people won't have Etcher and another USB/OS-image creator app installed and actively used at the same time.
I'm not personally a huge fan of the Etcher project, so I'm not really willing to redesign the icon for it.

**Comment by benfeatherstone** [comment]
I think that a symlink to USB Creator would be fine for this application. Although Ubuntu Gnome comes with a startup disk creator by default that uses the same icon already. Sorry to hear you don't like the project though.

**Comment by keeferrourke** [comment]
Added an `etcher.svg` file. I think this is the best I can do, you'll need to edit your desktop file to show the correct icon.

**Comment by dpelletier** [comment]
Hello, The AppImage for the latest Etcher (1.4.4, 64bit Linux) does not have an icon and I am unable to find your committed svg.
