### ISSUE TITLE
[Request] Retro Arch

### ISSUE THREAD

**Issue by benfeatherstone** [keeferrourke/la-capitaine-icon-theme#159]
Icon name: retroarch

Context: Frontend for retro game emulator

Icon reference: 

![retroarch](https://user-images.githubusercontent.com/7890249/27196614-ca706856-51d0-11e7-9ece-b8bba7f70e0a.png)

**retroarch.desktop content**

```
[Desktop Entry]
Version=1.0
Name=RetroArch
GenericName=Libretro Frontend
Type=Application
Comment=Multi-Engine Platform
Icon=retroarch
Exec=retroarch
Terminal=false
StartupNotify=false
Keywords=multi;engine;emulator;xmb;
Categories=Game;Emulator;
```

**Comment by benfeatherstone** [comment]
I am not going to be picky since you are the designer and it's your project, so a symlink would work for this one as well. However, something that resembled an old arcade cabinet would be cool and might be more retro. I am not a designer, so whatever is going to compliment the overall looks of the theme works for me.

**Comment by keeferrourke** [comment]
![retroarch](https://user-images.githubusercontent.com/6888381/27293827-87f9d7ec-54e5-11e7-8789-8baedd406806.png)
`retroarch.svg` added in commit https://github.com/keeferrourke/la-capitaine-icon-theme/commit/5c4b34915e0930ff39ea22eb47fbcf23e0cbbc18
