### ISSUE TITLE
add StarUML icon support

### ISSUE THREAD

**Issue by handrake0724** [keeferrourke/la-capitaine-icon-theme#168]
It would appreciated to add StarUML supprot in the icon theme.
StarUML file extension is .mdj

![appshell256](https://user-images.githubusercontent.com/18005991/27510268-32c1a996-5948-11e7-9f59-be6fce3b3609.png)

**Comment by keeferrourke** [comment]
The file extension is not enough. I need the mimetype.

**Comment by handrake0724** [comment]
mime type is application/octet-stream

**Comment by keeferrourke** [comment]
If the mimetype is not properly recognized as an unique type, then I cannot add an icon for it, sorry. Reach out to whatever project uses StarUML files and make the case that they get their file mimetypes added to `/etc/mime.types` and `/usr/share/mime`.
