### ISSUE TITLE
Support for folders colors

### ISSUE THREAD

**Issue by fcole90** [keeferrourke/la-capitaine-icon-theme#169]
Folder color is an app that allows the user to customise folder colors according to his/her needs and preferences. It would be great if La Capitaine could support it. 

How it looks and how to try it:
http://www.omgubuntu.co.uk/2017/06/quickly-change-folder-color-ubuntu

Project page:
http://foldercolor.tuxfamily.org

How to add theme support:
http://bazaar.launchpad.net/~costales/folder-color/trunk/view/head:/README

**Comment by keeferrourke** [comment]
This is a duplicate issue. See https://github.com/keeferrourke/la-capitaine-icon-theme/issues/127.

Basic Folder Color support is already integrated. Closing.
