### ISSUE TITLE
[Request] Gnome ToDo

### ISSUE THREAD

**Issue by weltenweber** [keeferrourke/la-capitaine-icon-theme#170]
Icon name: org.gnome.Todo
Context: Todo-List application

Icon reference:
![image](https://user-images.githubusercontent.com/15271679/27760879-3bc7f9fa-5e52-11e7-9766-ee44c04d21ec.png)

org.gnome.Todo.desktop content:

```
[Desktop Entry]
Name=To Do
Comment=Manage your personal tasks
Exec=gnome-todo
Icon=org.gnome.Todo
Terminal=false
Type=Application
StartupNotify=true
OnlyShowIn=GNOME;
Categories=GNOME;GTK;Utility;
Keywords=Task;Productivity;
DBusActivatable=true
X-Ubuntu-Gettext-Domain=gnome-todo
```

Thanks for an amazing icon theme and considering this request!

**Comment by keeferrourke** [comment]
commit b959755eef588f7f6690a050b2c0f0cee1f4ff35 address this issue.
