### ISSUE TITLE
Labels on some icons aren't SVG shapes but actual text

### ISSUE THREAD

**Issue by M4he** [keeferrourke/la-capitaine-icon-theme#171]
While migrating my system recently I did a little mistake by not correctly transferring the folder permissions for some of my font folders, including the "Source Sans Pro" font.

This however coincidentally revealed some issue(?) with some icons that include text labels:
![capitaine-font-issue](https://user-images.githubusercontent.com/1408105/27768070-76111e44-5f0a-11e7-8170-2174065b1ad5.png)
Some icons were rendered with strange boxes while others were fine.

Comparing the SVG code revealed that the unaffected ones (majority) have their labels included as true SVG shape definitions, the text being pre-converted `path` structures basically.  
On the other hand, the icons that had rendering issues include a `text` object that has a font defintion, e.g.
```
          <text
             sodipodi:linespacing="125%"
             id="text3508"
             y="59.341576"
             x="-31.525585"
             style="font-style:normal;font-weight:normal;font-size:15px;line-height:125%;font-family:sans-serif;text-align:start;letter-spacing:0px;word-spacing:0px;text-anchor:start;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
             xml:space="preserve"><tspan
               style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:7.5px;font-family:'Source Sans Pro';-inkscape-font-specification:'Source Sans Pro';fill:#ffffff"
               y="59.341576"
               x="-31.525585"
               id="tspan3510"
               sodipodi:role="line">c hdr</tspan></text>
```
(from `mimetypes/scalable/text-x-chdr.svg`)

The important part is the `font-family:'Source Sans Pro'` here. Since this exact font was broken on my system due to a mistake of mine, it couldn't be rendered.

I don't know if this is intended or necessary for specific icons but just wanted to report it since I happened to notice. Rendering fonts during runtime might have performance implications but I'm not sure how well the icon cache mitigates this.

On a side note, this also seems to be the reason why the `+` sign on the calculator icon always seems a bit horizontally shifted for me, because my system renders the font differently. The other signs (`=`, `x` etc.) are actually SVG `path`s except for the `+` sign!

**Comment by keeferrourke** [comment]
Thanks for pointing this out! I guess I got lazy or was tired, and missed converting some of the fonts to paths. Would you be able to compile a list of affected icons?

**Comment by M4he** [comment]
```
mimetypes/scalable/text-x-chdr.svg
mimetypes/scalable/text-x-sass.svg
mimetypes/scalable/text-x-matlab.svg
mimetypes/scalable/application-x-smb-server.svg
mimetypes/scalable/application-json.svg
mimetypes/scalable/application-x-smb-workgroup.svg
mimetypes/scalable/application-mbox.svg
mimetypes/scalable/text-x-typescript.svg
mimetypes/scalable/text-x-c++.svg
apps/scalable/accessories-calculator.svg
```

**Comment by keeferrourke** [comment]
Yeah, definitely too late at night to be doing this. RIP me.

**Comment by M4he** [comment]
Thanks for the fixes! What about the calculator icon?

**Comment by keeferrourke** [comment]
My bad.

TO DO:
- [ ] Calculator text-to-paths
