### ISSUE TITLE
[Request] Lutris

### ISSUE THREAD

**Issue by kfarwell** [keeferrourke/la-capitaine-icon-theme#176]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Lutris    | `lutris` | Application | ![](https://lutris.net/static/images/logo-big.png) |

### Desktop file
lutris.desktop

```
[Desktop Entry]
Version=1.0
Name=Lutris
Comment=Open gaming platform
Categories=Game;
Exec=lutris %U
Icon=lutris
Terminal=false
Type=Application
MimeType=x-scheme-handler/lutris;
```

**Comment by keeferrourke** [comment]
Three options here from a design perspective:
1. I can honour the original Lutris design (looks inspired by Firefox/Iceweasel icon?) [this is more challenging]
2. I can make a more generic joy-stick-like icon
3. I can modify the [gnome-games](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/gnome-games.svg) icon to fit the Lutris colourscheme / emblem

Thoughts or preferences? I'm leaning more toward option 2.

**Comment by kfarwell** [comment]
Option 2 is fine by me. The upstream logo does suck.

**Comment by keeferrourke** [comment]
Here's an initial preview found in commit 1f085c5c1e420a9b88b04260b7a8f7d7ab78a37f, I think the icon may be a little dark, but getting the gradients right is tricky. This is definitely subject to further revision.
![lutris](https://user-images.githubusercontent.com/6888381/29572172-187c24ec-8721-11e7-90a8-8292aba3dba8.png)

**Comment by keeferrourke** [comment]
Closing this for now, but further work on this issue is expected.
