### ISSUE TITLE
[Request] Nextcloud client

### ISSUE THREAD

**Issue by kfarwell** [keeferrourke/la-capitaine-icon-theme#177]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Nextcloud desktop sync client | `Nextcloud` | Application | ![](https://ftp2.halpanet.org/source/_dev/nextcloud-client.git/nextcloudtheme/theme/colored/Nextcloud-icon-512.png) |

### Desktop file
nextcloud.desktop

```
[Desktop Entry]
Categories=Utility;X-SuSE-SyncUtility;
Type=Application
Exec=nextcloud
Name=Nextcloud desktop sync client 
Comment=Nextcloud desktop synchronization client
GenericName=Folder Sync
Icon=Nextcloud
Keywords=Nextcloud;syncing;file;sharing;
X-GNOME-Autostart-Delay=3
```

**Comment by keeferrourke** [comment]
Here's a preview, the base of the gradient was taken from Nextcloud's official logo [here](https://nextcloud.com/wp-content/themes/next/assets/img/common/logo_nextcloud.svg).

![nextcloud](https://user-images.githubusercontent.com/6888381/28857724-75d98822-7719-11e7-8bb4-eefe6bb4dc99.png)
`Nextcloud.svg`
