### ISSUE TITLE
[Update] to the new firefox nighly icon

### ISSUE THREAD

**Issue by louisgrasset** [keeferrourke/la-capitaine-icon-theme#180]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Firefox Nightly    | `firefox-nightly` | Application | ![visualelements_150](https://user-images.githubusercontent.com/9489181/29002017-ca8d315c-7a98-11e7-94a2-a1726d17afae.png)  |

### Desktop file

```
[Desktop Entry]
Name=Firefox Nightly
GenericName=Web Browser
Icon=firefox-nightly-icon
Type=Application
Categories=Application;Network;
MimeType=text/html
Encoding=UTF-8
Exec=firefox-nightly %u
Terminal=false
MultipleArgs=false
StartupWMClass=Firefox




```

**Comment by keeferrourke** [comment]
Updated both the regular Firefox and Nightly icons to reflect the new simplified geometry. Gradients have been tweaked slightly.

| Firefox | Firefox Nightly |
| :---: | :---: |
| ![firefox](https://user-images.githubusercontent.com/6888381/29008333-144a9ccc-7ae3-11e7-9277-fc0c84add795.png) | ![firefox-nightly](https://user-images.githubusercontent.com/6888381/29008364-a3f45e08-7ae3-11e7-8e77-b04810b8fb63.png) |
| `firefox.svg` | `firefox-trunk.svg` |

See commit 3954881ee12a1eee523fa4953cbf824543d24db0.
