### ISSUE TITLE
[Request] Kleopatra

### ISSUE THREAD

**Issue by now-im** [keeferrourke/la-capitaine-icon-theme#187]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Kleopatra   | `org.kde.kleopatra.desktop ` | Application | ![kleopatra](https://user-images.githubusercontent.com/22009014/29488389-a9590130-852b-11e7-9ec7-5578f63ad70d.png)|

### Desktop file
[Desktop Entry]
Type=Application
Categories=Qt;KDE;Utility;
Exec=kleopatra
Icon=kleopatra
Name=Kleopatra
GenericName=Certificate Manager and Unified Crypto GUI
Terminal=false
StartupNotify=true
X-DocPath=kleopatra/index.html
X-DBUS-ServiceName=org.kde.kleopatra
```

```

**Comment by now-im** [comment]
This application has icon in notification area which has not changed. is there any way to change it?

**Comment by keeferrourke** [comment]
@now-im not as of yet. I have not added [hardcode-tray](https://github.com/bil-elmoussaoui/Hardcode-Tray) support to La Capitaine yet. See issue #125. This is planned for the 0.6.0 release, but I do not currently have a timeline

**Comment by now-im** [comment]
Okay, i know this project is big for one man. Take your time. But i am coverned about the size. 170mb is quite big for this and new icon request are flooding.

**Comment by keeferrourke** [comment]
@now-im there is a pull request waiting that optimizes out a lot of extraneous data from most SVG files, which should reduce the size of this project by a fair bit, I have to manually merge it though, and I simply don't have the time to deal with it right now.

I know 170mb is a lot, but quite frankly there are a LOT of applications out there which people want to be themed. I aim to provide as complete of an icon theme as possible, as that obviously comes at the cost of space. I think that is a fair trade-off.

**Comment by now-im** [comment]
That's true. Go along with your plan, this project is no less than papirus icon or paper. I would help but i don't have technical knowledge in this side. Thanks for your effort.

**Comment by keeferrourke** [comment]
I am looking into how to optimize this theme better :+1: thanks for your feedback

**Comment by now-im** [comment]
Congratulations, La Capitane is now at 120mb, this is pretty considerable. Nice work!

**Comment by keeferrourke** [comment]
More size reductions coming soon :)
