### ISSUE TITLE
[Request] Qt Designer

### ISSUE THREAD

**Issue by now-im** [keeferrourke/la-capitaine-icon-theme#189]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Qt Designer   | `designer.desktop` | Application | 	![qtproject-designer](https://user-images.githubusercontent.com/22009014/29492240-5db7c164-8597-11e7-89f2-585a018d4ade.png)|

### Desktop file

```
[Desktop Entry]
Name=Qt Designer
GenericName=Interface Designer
Comment=Design GUIs for Qt applications
Exec=designer
Icon=QtProject-designer
MimeType=application/x-designer;
Terminal=false
Type=Application
Categories=Qt;Development;





```

In the help post of .5 release I mentioned two inconsistent qt application icon. I am posting them now.

**Comment by keeferrourke** [comment]
I'll be releasing v0.5.0 within the next week or so. I'll try to get these requests satisfied before I do so.
