### ISSUE TITLE
[Request] Deepin Show Desktop

### ISSUE THREAD

**Issue by now-im** [keeferrourke/la-capitaine-icon-theme#197]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Show Desktop    | `deepin-toggle-desktop.desktop` | Application | ![deepin-toggle-desktop](https://user-images.githubusercontent.com/22009014/29657992-2f7c53c2-88db-11e7-9b65-272b0dc3f509.png)|

### Desktop file

```
[Desktop Entry]
Categories=GNOME;GTK;System;
Comment=Show desktop or show windows
Exec=/usr/lib/deepin-daemon/desktop-toggle
GenericName=Show Desktop
Icon=deepin-toggle-desktop
Name=Show Desktop
OnlyShowIn=Deepin;
Terminal=false
Type=Application
X-AppStream-Ignore=true
```

**Comment by Riotism** [comment]
Can we symlink to ../places/scalable/desktop.svg?

**Comment by keeferrourke** [comment]
I think that should work fine.
