### ISSUE TITLE
[Request] Deepin Movie

### ISSUE THREAD

**Issue by now-im** [keeferrourke/la-capitaine-icon-theme#203]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Deepin Movie   | `deepin-movie.desktop` | Application | ![deepin-movie](https://user-images.githubusercontent.com/22009014/29659723-f2327284-88e0-11e7-89f3-18f0fb2c26a7.png)|

### Desktop file

```
[Desktop Entry]
Categories=AudioVideo;Player;
Comment=Play your video collection
Exec=deepin-movie %U
GenericName=Media Player
Icon=deepin-movie
MimeType=application/ogg;application/vnd.apple.mpegurl;application/vnd.rn-realmedia;application/x-extension-mp4;application/x-flac;application/x-matroska;application/x-ogg;application/xspf+xml;image/vnd.rn-realpix;misc/ultravox;video/3gpp;video/dv;video/mp2t;video/mp4;video/x-m4v;video/mp4v-es;video/mpeg;video/msvideo;video/ogg;video/quicktime;video/vnd.rn-realvideo;video/webm;video/x-anim;video/x-avi;video/x-flc;video/x-fli;video/x-flv;video/x-matroska;video/x-mpeg;video/x-ms-asf;video/x-msvideo;video/x-ms-wmv;video/x-nsv;video/x-ogm+ogg;video/x-theora+ogg;x-content/video-dvd;x-content/video-svcd;x-content/video-vcd;x-scheme-handler/mms;x-scheme-handler/rtmp;x-scheme-handler/rtsp
Name=Deepin Movie
StartupNotify=true
Type=Application
```

With this my post streak ends. I posted most available applications. Some icons are beautiful on their own, I leave them on your judgement whether to change them or not.

**Comment by keeferrourke** [comment]
Agreed :) some of these Deepin icons are really nice, and will probably serve as some inspiration for redesigns in the future! Thanks for your help.

**Comment by now-im** [comment]
Some arch linux user is not being able to update git package properly. So I have made a point release package.  Besides, arch maintenaners don't adopt git packages officialy. It can be found here:
https://aur.archlinux.org/packages/la-capitaine-icon-theme/
In ths release link kindly avoid v0.5.0 numbering. Use 0.5.0 if possible. It removes some packaging hassle.

**Comment by Riotism** [comment]
We already have an icon for Deepin Media Player. Can we symlink to deepin-media-player.svg?

**Comment by keeferrourke** [comment]
@Riotism I'll try to find some time tonight to give these proper attention.
