### ISSUE TITLE
configure not working when installed from aur

### ISSUE THREAD

**Issue by Amaunator** [keeferrourke/la-capitaine-icon-theme#204]
on antegros kde when installed via yaourt from aur configure script not working. when I change permissions and run it as root from its folder it won't change icons for dark theme in eg. file manager menus. can you create dark theme separately? meanwhile going back to papirus-dark

**Comment by keeferrourke** [comment]
I don't see a need for creating a separate dark theme, and I do maintain or endorse the AUR package. Please clone the theme from git.
