### ISSUE TITLE
Please, restore Krusader's icon so it wouldn't have the same one as Dolphin

### ISSUE THREAD

**Issue by michaldybczak** [keeferrourke/la-capitaine-icon-theme#205]
In older version, Krusader and Dolphin got different icons. Now it's one and the same, which creates two the same icons next to each other on my dock. Or am I the only one using both file managers (system one and Krusader)?

Old Krusader icon was great and see no reason why this was changed. Or maybe it was just overlooked somehow?

**Comment by keeferrourke** [comment]
I believe I made this change under the premise that no system would ever have two file managers installed along-side one another.

In the case of systems that do... desktop environments usually label application entries and windows. I am unlikely to "fix" this, since consistency across platforms is what I am aiming for. You can modify your local copy of the theme by downloading the old version of the file, and placing it in the apps/scalable directory.

**Comment by michaldybczak** [comment]
This is very bold premise. Some file managers are different and offer different functionality so having two file managers is possible and desirable for some usage cases. No matter how great dolphin is, krusader has some options that dolphin misses (like remembering of last place you were in + much more) and in general, krusader is just better so it's more fit for work where file manipulations are on constant basis (shortcuts, moving files and better compressed files handling, easy access to ftp or ssh on a server through favorites, etc). I still like to use dolphin for home stuff because it feels more in place UI wise.

If I would run gnome, I would need krusader even more, because "files" is so options void.

Also, krusader is NOT A SYSTEM FILE MANAGER, it's a GENERAL FILE MANAGER. Sure, it's tied more to Plasma, but it's just a separate program and you totally miss the icon. So if you treat it as such, then it should deserve own icon.

Moreover, La Capitaine was one of very few icon packs that worked with Krusader, while all others just don't recognize it and go with some ugly icon that doesn't fits anywhere, so I always had to reject those icons. Now that great feature of La Capitaine is gone. It's not so bad because it uses default file manager icon so it's still usable but... not ideal.

I just don't see how one icon more would hurt anyone? If one can request new icons for specific applications, then I request icon for krusader. It already exists so it should be easy to add it again. Please, consider it.

Anyway, I updated the icon pack so how do I get old one with the icon I need? I didn't anticipate this change and I do backups of home folder, while La Capitaine install is on root (installed it with package manager).

**Comment by keeferrourke** [comment]
Alright, you've made your case. I've fixed this issue, cheers.

**Comment by michaldybczak** [comment]
Oh, wow. Thank you!

http://imgur.com/a/4jmqh

La Capitain is complete again :D
