### ISSUE TITLE
Tag version 0.5.0

### ISSUE THREAD

**Issue by LaurentTreguier** [keeferrourke/la-capitaine-icon-theme#206]
Commit bbfb1a5829a94fefcb242a48a9fb2b898b222519 and [Milestone 0.5.0](https://github.com/keeferrourke/la-capitaine-icon-theme/milestone/1) seem to indicate that version 0.5.0 is finished, so tagging the version would be pretty logical and would close the milestone. Having tags also help in packaging (since I am maintaining the Fedora/EPEL package), although I will probably use a later commit directly to benefit from fixes for missing icons.

**Comment by keeferrourke** [comment]
Hey @LaurentTreguier I am not quite done, but a v0.5.0 tag and release is coming soon! Sorry it's been a long time coming, but expect it in the next few days! :)

**Comment by LaurentTreguier** [comment]
@keeferrourke Okay ! 👍

**Comment by keeferrourke** [comment]
New release made today! 🎉

**Comment by LaurentTreguier** [comment]
Great news ! A new RPM is being built right now 🎊
