### ISSUE TITLE
[Request] [Priority-low] Plasma theme

### ISSUE THREAD

**Issue by somniumAeternam** [keeferrourke/la-capitaine-icon-theme#21]
The icons look very nice. But in Plasma 5 they are not used in the system tray, because of the special theming engine.

In order to use these icons in the system tray and other related contexts (overlays), you need a separated theme with these icons. You could use the standard breeze theme. An example with Antü icons is shown here: https://www.kde-look.org/p/998639

**Comment by keeferrourke** [comment]
Noted; if you could provide a screenshot to better describe the issue that would be great. I'm not sure why KDE needs a separate theme for its system tray, but I'll look into it.

**Comment by somniumAeternam** [comment]
I attached a screenshot. But there is not much to see. If you user the plasma theme Breeze, then the breeze icons are used for status, system tray etc.
![screenshot_20160809_131827](https://cloud.githubusercontent.com/assets/9334916/17514621/e50746bc-5e33-11e6-9a50-609619dda8a1.png)

I have also attached the example for breeze with Antü icons. The theme mainly consists of just the icon folder with svgz-files
[breeze-antu.tar.gz](https://github.com/keeferrourke/la-capitaine-icon-theme/files/408785/breeze-antu.tar.gz)

**Comment by keeferrourke** [comment]
Is it important that they be svgz? Is it possible to just use the existing SVGs in this repo?

**Comment by somniumAeternam** [comment]
This is not possible, because in these svgz-files are different layers of one icon. For example there is only one file for battery and audio. But inside these files are different layers with alle the different states. See the breeze-antu-theme. I would do it, but I don't know how.

**Comment by keeferrourke** [comment]
Ah... This is why I hate KDE. I'll try to take a look at it this week, but no promises for a prompt update. I'm going to be on a plane on Saturday and won't be able to work on this for a week until I return home.

**Comment by somniumAeternam** [comment]
I also don't know, why they are doing this. I will ask in their mailing list. Maybe it is somehow possible to use the other icons. I have also read, that they are planing to change the theming behaviour in order to make it simpler. We will see.

**Comment by DarkknightAK** [comment]
Hi,
to be honest, I'm also not a fan how icons work for plasma themes. if you need help, I know how you can make a plasma theme.

**Comment by keeferrourke** [comment]
@DarkknightAK thanks for the offer, but I think I might just close this issue. It's been inactive for a pretty long time, and I don't like how KDE is using a non-standard approach to theming status icons. Hopefully they fix this upstream, but I don't think it's necessary or a good idea to support this. The breeze icons in plasma5 look fine with La Capitaine.
