### ISSUE TITLE
Icon Request: FeedReader

### ISSUE THREAD

**Issue by bil-elmoussaoui** [keeferrourke/la-capitaine-icon-theme#210]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| FeedReader | `org.gnome.FeedReader` | `org.gnome.FeedReader.desktop` | ![FeedReader](http://i.imgur.com/L8w2qWt.png)| la-capitaine-icon-theme |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by Riotism** [comment]
Symlink to internet-news-reader.svg?

**Comment by keeferrourke** [comment]
Will do.
