### ISSUE TITLE
How to change the show-app gnome icon?

### ISSUE THREAD

**Issue by mllamazing** [keeferrourke/la-capitaine-icon-theme#229]
I want to replace the show-apps icons of gnome:
![image](https://user-images.githubusercontent.com/5461023/30176089-74290912-9401-11e7-812e-04c2ef10d6d4.png)

I tried by `cp startupmanager.svg show-apps.svg` inside `$HOME/.icons/la-capitaine-icon-theme/apps/scalable` folder but before refreshing does not change anything.

**Comment by keeferrourke** [comment]
GNOME uses `view-grid-symbolic.svg` as far as I know.
