### ISSUE TITLE
Spotify on a light background

### ISSUE THREAD

**Issue by Jazqa** [keeferrourke/la-capitaine-icon-theme#231]
As you can see from the pictures below, Spotify's edges are too dark and do not blend to a light background. Other circular icons are fine and even the green part of Chrome's icon looks good on a light background. Spotify's icon is also slightly larger than other circular icons, cutting the bottom edge off by a few pixels.

![screenshot_20170912_093127](https://user-images.githubusercontent.com/18004783/30311365-8d13ff1e-979d-11e7-8b87-69532d77bbc4.png)

![screenshot_20170912_093828](https://user-images.githubusercontent.com/18004783/30311489-24882eb0-979e-11e7-815c-a33db71d43f1.png)

**Comment by keeferrourke** [comment]
fixed! thanks for pointing this out! I'm in the process of normalizing all icons to 44x44 sizes. Slow process, but that's one more off the to-do list!
