### ISSUE TITLE
Kfind icon not working

### ISSUE THREAD

**Issue by now-im** [keeferrourke/la-capitaine-icon-theme#232]
In the la-capitaine folder, i found Kfind icon but it is not the one in the app menu.
![spectacle x11428](https://user-images.githubusercontent.com/22009014/30423537-f6350b8c-9964-11e7-8931-b13fc2778d94.png)
This is what I am getting. Address me if you need any output.

**Comment by now-im** [comment]
[Desktop Entry]
Exec=kfind %u
Icon=kfind
X-DocPath=kfind/index.html
Type=Application
Terminal=false
Name=KFind
GenericName=Find Files/Folders
X-KDE-StartupNotify=true
OnlyShowIn=KDE;
Categories=Qt;KDE;Utility;
X-DBUS-ServiceName=org.kde.kfind

**Comment by keeferrourke** [comment]
Should be fixed now.

**Comment by now-im** [comment]
Awesome job. Problem fixed.
