### ISSUE TITLE
[Request] a new icon for KDE Discover app

### ISSUE THREAD

**Issue by trmdi** [keeferrourke/la-capitaine-icon-theme#242]
![spectacle kn8637](https://user-images.githubusercontent.com/11857205/30627269-4774ef60-9df9-11e7-8159-22a9ff7caf32.png)

You can see the Discover icon ( the 3rd icon from right to left) is shorter than others.

### Application information

| Application name | Icon name  | Context     | Icon reference | Suggest 
| ---------------- | :--------- | :---------- | :------------- | :------------- |
| Discover    | `plasmadiscover` | Application |  ![default icon](http://svgur.com/i/35y.svg)  |![suggest icon](https://cdn4.iconfinder.com/data/icons/miu-flat-social/60/app_store-64.png) [Source](https://www.iconfinder.com/icons/287607/app_store_icon#size=256)

### Desktop file
/usr/share/applications/org.kde.discover.desktop
```
[Desktop Entry]
Name=Discover
MimeType=
Exec=plasma-discover %F
Icon=plasmadiscover
Type=Application
X-DocPath=plasma-discover/index.html
InitialPreference=5
NoDisplay=false
GenericName=Software Center
Categories=Qt;KDE;System;
Keywords=program;software;repository;package;install;remove;update;apps;applications;

**Comment by keeferrourke** [comment]
Please follow the request format outlined in the Wiki. Without specific information such as the actual icon name, I am unable to correct this issue as I have little to no time on my hands at the moment.

**Comment by trmdi** [comment]
Sorry @keeferrourke, added specific info.

**Comment by keeferrourke** [comment]
This was an easy issue to fix, so I've taken care of it. Closing. I'll be cherry picking easy requests over the next few weeks, but I'm *super* stressed lately so please make sure all future requests have the requested information.

Thanks!
