### ISSUE TITLE
[Request] Kvantum Manager

### ISSUE THREAD

**Issue by now-im** [keeferrourke/la-capitaine-icon-theme#243]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Kvantum Manager    | `kvantummanager.desktop` | Application | ![kvantum 2](https://user-images.githubusercontent.com/22009014/30645140-985c2136-9e36-11e7-937d-53d8203d35af.png)|

### Desktop file

```
[Desktop Entry]
Version=1.0
Name=Kvantum Manager
Comment=A simple GUI for installing, selecting and manipulating Kvantum themes
Exec=kvantummanager
Icon=kvantum
Terminal=false
Type=Application
Categories=Qt;Utility;Settings;DesktopSettings;LXQt;X-XFCE-SettingsDialog;X-XFCE-PersonalSettings;X-GNOME-PersonalSettings;
X-KDE-StartupNotify=false
```

**Comment by keeferrourke** [comment]
This is a theme manager, correct? Would a symlink to `theme-config.svg` suffice?

**Comment by now-im** [comment]
I think so.

**Comment by now-im** [comment]
Updated to latest git. System link now working.

**Comment by now-im** [comment]
Updated to latest git. System link is not working.

**Comment by keeferrourke** [comment]
Yup, looks like I didn't read your issue correctly. In the future, in the `Icon name` column of the table, don't put the name of the desktop file, but rather put what you find on the `Icon=` line of the desktop file.

To illustrate this, your table in the report should have looked like:

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Kvantum Manager    | `kvantum` | Application | ![kvantum 2](https://user-images.githubusercontent.com/22009014/30645140-985c2136-9e36-11e7-937d-53d8203d35af.png)|

**Comment by keeferrourke** [comment]
@now-im please pull the latest commit 81a15fb and let me know if the icon is properly themed.

**Comment by now-im** [comment]
Problem fixed. :+1:
