### ISSUE TITLE
PKGBUILD in AUR removed

### ISSUE THREAD

**Issue by r3b311i0n** [keeferrourke/la-capitaine-icon-theme#244]
The git version of the icon theme has been [removed](https://aur.archlinux.org/packages/la-capitaine-icon-theme-git) from the AUR. Only the [stable](https://aur.archlinux.org/packages/la-capitaine-icon-theme/) version exists.

**Comment by keeferrourke** [comment]
Please message the package maintainer about this. I do not use Arch Linux, and any packages are made by the community.

I'll be sure to update the README about this however.

**Comment by r3b311i0n** [comment]
It seems like the maintainer has removed his account (looks like all of his other packages are gone as well). Would it be OK if I upload a PKGBUILD to the AUR?

**Comment by keeferrourke** [comment]
@r3b311i0n absolutely! please do :)

**Comment by r3b311i0n** [comment]
@keeferrourke Right, I've added it. The link remains the same; no need to change the README.
