### ISSUE TITLE
Slowdown after last update

### ISSUE THREAD

**Issue by dzift** [keeferrourke/la-capitaine-icon-theme#247]
distro: Arch XFCE

Hi, ever since I updated the package 3 days ago there has been a slowdown when opening home folder. If I remove the package or change to other icon theme all is good so it's definitely something going on. It's a 0.5s delay every time I am navigating to home.

I tried:
- Installing from AUR -git package.
- Installing from AUR non-git package.
- Cloning this repo in ~/.icons

**Comment by keeferrourke** [comment]
hmmm... probably related to https://github.com/keeferrourke/la-capitaine-icon-theme/issues/228

**Comment by keeferrourke** [comment]
If you try temporarily removing the following icons (should fall back to GNOME), does the lag go away?

    user-home.svg
    folder-script.svg
    folder-temp.svg

**Comment by dzift** [comment]
I removed them from `~/.icons/la-capitaine-icon-theme/places/scalable/` and there was an improvement. However there is still a tiny lag which is gone as soon as I switch to any other icon theme.

**Comment by keeferrourke** [comment]
Is the other icon theme raster or vector?

**Comment by keeferrourke** [comment]
ran svgcleaner over the places/scalable directory and remade user-home, folder-script, folder-temp in commit 7531ed4.

please pull this commit and let me know if the problem persists.

**Comment by dzift** [comment]
Much better now. I was comparing with Faenza which looks to have svg's aswell.

**Comment by keeferrourke** [comment]
Can I close this then?
