### ISSUE TITLE
[Bug] Dark icon on dark panel sound muted

### ISSUE THREAD

**Issue by mrluizandre** [keeferrourke/la-capitaine-icon-theme#253]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Unity top panel    | `audio-volume-muted-panel` | Dark Top Panel |  See screenshot below |

![screenshot from 2017-10-11 00-24-29](https://user-images.githubusercontent.com/8496448/31420997-38836c52-ae1b-11e7-830c-3dd80d3fb40d.png)

I'm using the theme **Arc-flatabulous-darker** on Ubuntu 16.04 with Unity, it is a theme with a dark top panel, the bug shows when I mute the sound or set it to minimum.

**Comment by keeferrourke** [comment]
This should be fixed now.

**Comment by mrluizandre** [comment]
Thanks so much, it looks quite better now.
