### ISSUE TITLE
[Request] R

### ISSUE THREAD

**Issue by now-im** [keeferrourke/la-capitaine-icon-theme#256]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| R    | `/usr/share/pixmaps/r.png` | Application | ![7290a4f8-7cbe-11e6-87ff-02751830ef74](https://user-images.githubusercontent.com/22009014/32002768-14786d3a-b9bf-11e7-8053-748644571d70.png) |

### Desktop file

```
[Desktop Entry]
Name=R
GenericName=environment for statistical computing
Comment=language and environment for statistical computing and graphics
Exec=R
Icon=/usr/share/pixmaps/r.png
DocPath=/usr/lib/R/doc/html/index.html
StartupNotify=true
Terminal=true
Type=Application
Categories=Math;Science;Education
```

I was surprised to see one of the best statistical and mathematics tools was not requested.

**Comment by keeferrourke** [comment]
There exists an icon for R already, located [here](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/rlogo_icon.svg). Please note that your desktop file makes use of hard-coded paths and needs to be modified according to the [SUPPORT](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/.github/SUPPORT.md) document.

**Comment by now-im** [comment]
I didn't know that. Will try to fix it manually.

**Comment by now-im** [comment]
Fixed it.
