### ISSUE TITLE
Atom snap icon

### ISSUE THREAD

**Issue by cairinmichie** [keeferrourke/la-capitaine-icon-theme#257]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Atom   | `Atom` | Snap Application | This icon has already been designed			   |

### Desktop file

```
[Desktop Entry]
Name=Atom
Comment=A hackable text editor for the 21st Century.
GenericName=Text Editor
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/atom_atom.desktop /snap/bin/atom %U
Icon=/snap/atom/50/usr/share/pixmaps/atom.png
Type=Application
StartupNotify=true
Categories=GNOME;GTK;Utility;TextEditor;Development;
MimeType=text/plain;
```

This is a follow up to #254. Hope this is more informative.

**Comment by linusg** [comment]
More informative, maybe. But if would have read the [`SUPPORT`](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/.github/SUPPORT.md) document, you would know what's going on. In your case, the icon's path is hardcoded to a PNG. Only way to resolve this is changing the line starting with `Icon=` to `Icon=atom`.

**Comment by cairinmichie** [comment]
Thanks @linusg .
