### ISSUE TITLE
[Request] RStudio

### ISSUE THREAD

**Issue by now-im** [keeferrourke/la-capitaine-icon-theme#259]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| RStudio    | `rstudio` | Application | ![rstudio](https://user-images.githubusercontent.com/22009014/32019899-634e0196-b9f0-11e7-9193-b99cd0ad3f57.png) |

### Desktop file

```
[Desktop Entry]
Exec=/usr/lib/rstudio/bin/rstudio %F
Icon=rstudio
Type=Application
Terminal=false
Name=RStudio
Categories=Development;
MimeType=text/x-r-source;text/x-r;text/x-R;text/x-r-doc;text/x-r-sweave;text/x-r-markdown;text/x-r-html;text/x-r-presentation;application/x-r-data;application/x-r-project;text/x-r-history;text/x-r-profile;text/x-tex;text/x-markdown;text/html;text/css;text/javascript;text/x-chdr;text/x-csrc;text/x-c++hdr;text/x-c++src;

```

**Comment by now-im** [comment]
Because of search mistake, I have posted it again. Sorry for that. Can the icon be improved a bit?

**Comment by keeferrourke** [comment]
You should notice this icon exists [here](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/rstudio.svg). How would you suggest improvement? The current design seems to be inline with La Capitaine design guidelines and honours the original icon rather well in my opinion.

Suggestions for improvement are welcome of course :)

**Comment by now-im** [comment]
Yes, thats true. I think using a bit deeper color would emphasize the shade. 
Currently it's okay. As it is a developer icon most people won't use it anyway.

**Comment by keeferrourke** [comment]
I'll look into redesigning it
