### ISSUE TITLE
Support for Harcode-tray

### ISSUE THREAD

**Issue by arifcatalyst** [keeferrourke/la-capitaine-icon-theme#260]
Please add support for Harcode-tray [https://github.com/bil-elmoussaoui/Hardcode-Tray](url)

**Comment by linusg** [comment]
Instead of wasting the maintainer's time, one could look  up the open issues. #125 is exactly the same, opened by the author of above tool.

**Comment by now-im** [comment]
It will most peobably come to fruition in version 0.6. Look forward to it!

**Comment by keeferrourke** [comment]
Closing as duplicate of #125.
