### ISSUE TITLE
[Request] Change Telegram icon

### ISSUE THREAD

**Issue by arifcatalyst** [keeferrourke/la-capitaine-icon-theme#262]
`cat /usr/share/applications/telegramdesktop.desktop | grep 'Icon='
`Icon=telegram

Reference icon

![telegram-icon-1](https://user-images.githubusercontent.com/26674272/32297267-aa44e13a-bf74-11e7-8c26-575d780e8e01.png)

**Comment by keeferrourke** [comment]
no

**Comment by arifcatalyst** [comment]
At least tell me, how do I do that ?

**Comment by keeferrourke** [comment]
@arifcatalyst please read the documentation provided in this repo, and the associated wiki.
