### ISSUE TITLE
[Request] Qtpass

### ISSUE THREAD

**Issue by now-im** [keeferrourke/la-capitaine-icon-theme#264]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| QtPass    | `qtpass` | Application | ![29699581-4eff59dc-895e-11e7-944e-62146f0f5d16](https://user-images.githubusercontent.com/22009014/32661935-f36f60a8-c652-11e7-9482-7ee788a0e3d3.png) |

### Desktop file

```
[Desktop Entry]
Type=Application
Name=QtPass
Version=1.0
GenericName=Password Manager
Comment=GUI for the standard unix password store
Comment[nl_NL]=GUI voor de standaard unix wachtwoord opslag
Exec=qtpass
Icon=qtpass
Terminal=false
Categories=Security;Utility;
Keywords=Password;Manager;QT;

```

**Comment by keeferrourke** [comment]
Oh, this was addressed by #333. Closing again. Great work @now-im :)
