### ISSUE TITLE
La Capitaine Dark - feature request

### ISSUE THREAD

**Issue by michaldybczak** [keeferrourke/la-capitaine-icon-theme#267]
I love La Capitaine icons and I use them on all Linux systems. It's one of the best designed and complete icons sets out there but there is some quite huge gap -> lack of dark option.

Will there be dark version of the icon theme for dark themes/panels? At the moment La Capitaine has some problems because it's suited for white/light themes/panels only. For example, in latte-dock, sound icon is not showing correctly (dark icon on dark background) when dark theme (breeze dark) is on. On Lxqt sound and battery icons are dark - always, so when using dark panel they become hardly visible and so on. Probably the same issue is on xfce. Luckily Plasma and Gnome use in panels icons from their desktop themes so the La Capitaine issue is avoided but in some areas it still persist.

Here is the case with latte-dock:
https://github.com/psifidotos/Latte-Dock/issues/774

So once again, we're waiting for Dark version to make La Capitaine complete, thanks!

**Comment by keeferrourke** [comment]
There is a dark version. Please read the relevant documentation in the README and the Wiki.

Simply run the included `configure` script from the root of this repository before applying your theme.

**Comment by michaldybczak** [comment]
Great but where is this script? This is first time I hear about such solution and it's an interesting one but the downsize is, it's not apparent. I also had troubles finding wiki you mentioned but finally it seems I found it:

https://github.com/keeferrourke/la-capitaine-icon-theme/wiki

however, there's... nothing there. I see only 3 pages. Am I missing something?

**Comment by linusg** [comment]
Come on... take a better look at the root of this repo. You want to go with [this one](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/configure).

`cd` into the cloned repo, issue `./configure` and adapt as you wish.

**Comment by michaldybczak** [comment]
Thanks. However, I don't think it worked:

```
Use icons for dark GTK+ themes? [y/N] y
rm: can't remove '/home/user/.icons/la-capitaine-icon-theme/devices/scalable': Is directory
rm: can't remove '/home/user/.icons/la-capitaine-icon-theme/panel/16': Is directory
rm: can't remove '/home/user/.icons/la-capitaine-icon-theme/panel/24': Is directory
rm: can't remove '/home/user/.icons/la-capitaine-icon-theme/places/16x16': Is directory
rm: can't remove '/home/user/.icons/la-capitaine-icon-theme/status/scalable': Is directory
Updated theme to use icons for dark GTK+ themes.
Use icons for a dark coloured panel? [y/N] y
Updated theme to use dark icons for the panel.
Could not determine distribution logo.
Use distributor logo from desktop environment? [y/N] y
Updated distributor logo.
Updated package archive icons.
Updated desktop mimetype icons.
```

Also, I had to use configure file from here, because somehow the version on my computer was only looking for system logo and kipped the whole dark version thing. I guess I will have to switch to git version.
Anyway, sound icon is still dark on dark, so nothing has changed.

**Comment by keeferrourke** [comment]
@michaldybczak 
> Thanks, but where is this script? This is first time I hear about such solution and it's an interesting one but the downsize is, it's not apparent.

If you would read the README, there is a dedicated [section](https://github.com/keeferrourke/la-capitaine-icon-theme#use-a-dark-gtk-theme) which explains the configuration script, and how to set up the dark theme. I don't know how I could possible be more clear, but if you think I can be, let me know how I can improve the docs.

> however, there's... nothing there. I see only 3 pages. Am I missing something?

Nope... that's the wiki. This is an icon theme, not an operating system. Honestly I think the amount of documentation I've written for this thing is *overkill*.

> ```rm: can't remove '/home/user/.icons/la-capitaine-icon-theme/devices/scalable': Is directory
rm: can't remove '/home/user/.icons/la-capitaine-icon-theme/panel/16': Is directory
rm: can't remove '/home/user/.icons/la-capitaine-icon-theme/panel/24': Is directory
rm: can't remove '/home/user/.icons/la-capitaine-icon-theme/places/16x16': Is directory
rm: can't remove '/home/user/.icons/la-capitaine-icon-theme/status/scalable': Is directory
```

Looks like your system is evaluating the symbolic links as proper directory paths. Make sure you haven't aliased `rm` to something silly, and that you haven't modified the directory structure. This is unsupported.

Try cloning from git again and running the configure script. You shouldn't have any issues...
