### ISSUE TITLE
[Question] Emotes look weird even though the svg file is ok... huh?

### ISSUE THREAD

**Issue by RaitaroH** [keeferrourke/la-capitaine-icon-theme#268]
Yo! Me again. 
So looking at your icons and noticed:
![screenshot from 2017-11-28 20 25 58](https://user-images.githubusercontent.com/19552720/33337126-a7f192be-d47a-11e7-9904-1321b780cb89.png)
They look like that even if I open them as a picture (including GIMP). They are fine if I open them in the browser or in inkscape.
Just wondering... why is this happening? XD
Pretty sure is something on my end but maybe you saw it before.

Side note: I kinda think they look really funny as they are right now XD
face-smile-slight for example is just SLIGHTly funny.

**Comment by RaitaroH** [comment]
No really this is so funny... I can't XD 👍

**Comment by keeferrourke** [comment]
that is the strangest behaviour I've ever seen. I was working on redesigning the faces a while ago but lost my work when my computer bit the dust. We'll keep this issue open for the memes and also a reminder to hopefully redraw these darn fellas over christmas

**Comment by RaitaroH** [comment]
So you don't know what this is then... it most likely is something weird on my end because the svg itself is alright. Not sure :P

**Comment by keeferrourke** [comment]
yep definitely a you-problem 😜 
![screenshot from 2017-11-29 13-58-41](https://user-images.githubusercontent.com/6888381/33393528-72621090-d50d-11e7-91a4-6cf63bb7273c.png)

**Comment by RaitaroH** [comment]
If anything look at it as inspiration for new emojis XD

**Comment by RaitaroH** [comment]
You can close the issue if you want.

**Comment by RaitaroH** [comment]
@keeferrourke Not a problem in KDE Neon anymore
![image](https://user-images.githubusercontent.com/19552720/34353149-39df3f18-ea2f-11e7-8db2-1fca0123d2f9.png)
