### ISSUE TITLE
Icon Request: GNOME Shell integration

### ISSUE THREAD

**Issue by bil-elmoussaoui** [keeferrourke/la-capitaine-icon-theme#271]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| GNOME Shell integration | `org.gnome.ChromeGnomeShell` | `org.gnome.ChromeGnomeShell.desktop` | ![GNOME Shell integration](https://i.imgur.com/hdLQ5cO.png)| la-capitaine-icon-theme |

This issue was automatically created using [IconRequests](https://github.com/bil-elmoussaoui/Icon-Requests).

**Comment by keeferrourke** [comment]
would a symlink to [desktop-environment-gnome](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/desktop-enviroment-gnome.svg) be sufficient?

**Comment by bil-elmoussaoui** [comment]
yeah :)
