### ISSUE TITLE
0.5.0 Color Change - Might As Well Be Another Iconset...

### ISSUE THREAD

**Issue by sla0101** [keeferrourke/la-capitaine-icon-theme#277]
I'm sorry to say I don't like the color change to the folders, this blue, that was created for 0.5.0.

This is also the first time I've seen someone that has created an iconset, that changed the main color, which IMHO throws off the idea of the iconset name, as this is La Capitaine, in my mind, that was the look before, so this might as well be another iconset with a different name.

Anyhow, I wish you stuck to the previous look, and maybe worked slight on that blue, maybe changing it's hue every so slightly to still feel like La Capitaine...

**Comment by keeferrourke** [comment]
Closing as this conversation is neither productive nor constructive.
