### ISSUE TITLE
Icon Request : Create archive

### ISSUE THREAD

**Issue by ghost** [keeferrourke/la-capitaine-icon-theme#285]
![screenshot_2018-01-12_19-02-28](https://user-images.githubusercontent.com/29171250/34877324-a0064454-f7cb-11e7-824e-33400297a30d.png)

Im sorry...i couldnt find the exact location of the image,so i just edited it out from a context menu..

here it is...
![screenshot_2018-01-12_19-08-16](https://user-images.githubusercontent.com/29171250/34877424-febaced4-f7cb-11e7-823a-4633122f39b2.png)

thank u soooo much for making these icons..they are beautiful as hell...

**Comment by keeferrourke** [comment]
@yaoghu this is XFCE with what file manager and archive manager? I may be able to hunt it down...

Can you send me some details of your OS and DE?

**Comment by yaoghu** [comment]
@keeferrourke oh ok...
the file manager i use is thunar..
the archieve manager is file-roller

distro is arch
and like u said...DE is xfce.

after posting the request...i took a look at the adwaita/gnome icons and still couldnt ID it....which probably cannot be the case,otherwise there wouldnt be an icon...

**Comment by yaoghu** [comment]
hey...i took a look at paprius's icon theme

and there was a add-archive image(which is the one i get in a context menu) in the "actions" folder

linking the image below...
![archive](https://user-images.githubusercontent.com/29171250/34945595-e3795d10-fa29-11e7-95b3-cbddf7397c2e.jpg)

**Comment by keeferrourke** [comment]
@yaoghu can you check if commit 917ffa9 fixes this issue?

**Comment by yaoghu** [comment]
@keeferrourke hey...so i grabbed the latest commit and checked it .....and sorry to say...but it still doesnt fix the issue...

no worries tho...still a baller theme!!

**Comment by keeferrourke** [comment]
curious; this problem doesn't occur with the Papirus theme at all?
could you link me to the source of the image? To me it looks like La Capitaine isn't missing any `add-*-archive` images from a quick search through the Papirus repo.

**Comment by yaoghu** [comment]
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/22x22/actions/archive.svg

there u go...btw...
i changed your archive image name to archive.svg...still no effect
