### ISSUE TITLE
KDE not rendering discover icon properly

### ISSUE THREAD

**Issue by now-im** [keeferrourke/la-capitaine-icon-theme#294]
Plasma discover icon name and reference are correct but for some reason in application menu it is different.
in /usr/share/application it is previewing correctly.
![image](https://user-images.githubusercontent.com/22009014/35052685-6513d2e8-fbd2-11e7-8f79-0f509d904906.png)
As you can see the icon is not as you have designed. #242

**Comment by keeferrourke** [comment]
that is... strange. KDE's SVG engine has given me troubles in the past, and I'm not sure why it's failing to render part of the asset. I don't have time to look into this right now, but maybe @Riotism can help?

**Comment by Riotism** [comment]
@now-im The Plasma Discover icon was added after the latest release. Are you using the latest commit?

**Comment by Riotism** [comment]
@now-im I misread the question. I'll look into the SVG file.

**Comment by now-im** [comment]
@riotism I am using the latest discover. Problem is somewhere else.

**Comment by Riotism** [comment]
@now-im @keeferrourke Submitted PR #297. Please test it out.

**Comment by keeferrourke** [comment]
Merged PR #297. Thanks for all your help @Riotism ! :beers:

**Comment by now-im** [comment]
@Riotism well done. problem solved.
