### ISSUE TITLE
Geogenra icon not working

### ISSUE THREAD

**Issue by now-im** [keeferrourke/la-capitaine-icon-theme#312]
@Riotism kindly have a look.
![image](https://user-images.githubusercontent.com/22009014/35470604-b01d399a-0376-11e8-9673-fe3c7427ea6d.png)

[Desktop Entry]
Encoding=UTF-8
Type=Application
Name=GeoGebra
Comment=Dynamic mathematics software with interactive graphics, algebra and spreadsheet
Exec=geogebra
Icon=geogebra
Terminal=false
StartupNotify=false
Categories=Education;Science;Math;
MimeType=application/vnd.geogebra.file;application/vnd.geogebra.tool;

**Comment by Riotism** [comment]
PR submitted.

**Comment by now-im** [comment]
problem fixed.
