### ISSUE TITLE
[Request] Icon for JetBrains IDEs

### ISSUE THREAD

**Issue by btd1337** [keeferrourke/la-capitaine-icon-theme#32]
Icons for Jetbrains IDE's are missing.

Example of .desktop
icon=clion

IDE's:
clion
phpstorm
pycharm
intellij
webstorm
rubymine
appcode
datagrip
resharper
resharper-c++

All icons are avaliable here: https://www.jetbrains.com/products.html?fromMenu

**Comment by keeferrourke** [comment]
Probably will just use recoloured versions of the `org.gnome.Builder` icon for a consistent look and feel.
If this isn't good enough, complain here before I add them to the repo :stuck_out_tongue:

**Comment by btd1337** [comment]
You can provide a preview?

**Comment by keeferrourke** [comment]
Take a look at the GNOME Builder icon [here](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/builder.svg). 

I plan to recolor with the simplified gradients used in the Jetbrains IDEs, and add each short name to the respective icons (ex. IJ, PS, etc.) where the curly braces are on the Builder icon. No promises on a timeline since I have midterms coming up.

**Comment by keeferrourke** [comment]
Alright, here's the preview!

![appcode svg](https://cloud.githubusercontent.com/assets/6888381/19250811/4fd68a96-8f0a-11e6-84a2-54b03cadca46.png) &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; ![clion svg](https://cloud.githubusercontent.com/assets/6888381/19250815/58058f5a-8f0a-11e6-8d05-1b4351e8595e.png) &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; ![datagrip svg](https://cloud.githubusercontent.com/assets/6888381/19250901/b651b94e-8f0a-11e6-9bb6-42e31bfd489a.png) &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; ![intellij svg](https://cloud.githubusercontent.com/assets/6888381/19250855/879e9ba8-8f0a-11e6-87c7-37306a078b16.png) &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;  ![phpstorm svg](https://cloud.githubusercontent.com/assets/6888381/19251099/a14d65ec-8f0b-11e6-9637-c82cac34ab60.png) 
`appcode`  &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;`clion`  &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;`datagrip`    &nbsp;&nbsp;&nbsp;&nbsp;`intellij`  &nbsp;&nbsp; &nbsp;`phpstorm`

![pycharm svg](https://cloud.githubusercontent.com/assets/6888381/19251707/ada7ff7a-8f0e-11e6-921c-8457b4cf41c7.png) &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;  ![resharper svg](https://cloud.githubusercontent.com/assets/6888381/19251938/ed9f8b88-8f0f-11e6-87f8-758f8decfe88.png) &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;  ![resharper-c svg](https://cloud.githubusercontent.com/assets/6888381/19252059/bacc9c90-8f10-11e6-9338-c11b0692760f.png) &nbsp;&nbsp;&nbsp;  &nbsp;&nbsp;&nbsp; ![rubymine svg](https://cloud.githubusercontent.com/assets/6888381/19252556/750245e0-8f13-11e6-9328-8f7574cba628.png) &nbsp;&nbsp;&nbsp;  &nbsp;&nbsp;&nbsp; ![webstorm svg](https://cloud.githubusercontent.com/assets/6888381/19252699/3be0e6da-8f14-11e6-953a-59a24a22d1b9.png)
`pycharm` `resharper` `resharper-c++` `rubymine` `webstorm`
