### ISSUE TITLE
Icon request: Minecraft

### ISSUE THREAD

**Issue by loutr** [keeferrourke/la-capitaine-icon-theme#322]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Minecraft    | `minecraft-launcher` | Application | 	![minecraft-launcher](https://user-images.githubusercontent.com/21224281/35486880-befec254-0474-11e8-95e0-ac9f300a3b02.png)		   |

### Desktop file
```
[Desktop Entry]
Type=Application
Version=1.0
Name=Minecraft Launcher
Comment=Official Minecraft Launcher
Exec=/opt/minecraft-launcher/minecraft-launcher.sh
Path=/opt/minecraft-launcher
Icon=minecraft-launcher
Terminal=false
Categories=Game;Application;
```

**Comment by undefinedDarkness** [comment]
Any luck with this?
