### ISSUE TITLE
Clip black issue

### ISSUE THREAD

**Issue by now-im** [keeferrourke/la-capitaine-icon-theme#331]
I tried to fix it on my own but I do not have enough skill to do it. I have hunted down the problematic icons.

- [ ] goa-account-google.svg

- [ ] google-earth.svg

- [x] google-drawings.svg

- [x] google-sheets.svg

- [x] google-slides.svg

- [x] google-docs.svg

- [ ] google-earth-pro.svg

- [ ] icon.svg

**Comment by keeferrourke** [comment]
@now-im could you edit your issue to describe what you mean by "clip black issue"? Perhaps include some screenshots?

**Comment by now-im** [comment]
Ungroup the icon > then mark all > object > clip > release.
As far as I know only KDE users are seeing this.
@riotism should know it.

**Comment by Riotism** [comment]
I'll work on this once I have dealt with the mimetype icons, since the issue with mimetype is license related.
