### ISSUE TITLE
Missing "audio" icon in Dolphin's "Search" section of sidebar

### ISSUE THREAD

**Issue by Tichy** [keeferrourke/la-capitaine-icon-theme#335]
It's evident expecially at >= 32px size, but it can be noticed also at 22 and 16.
The icon is missing, and it falls back to breeze.

![screenshot_20180201_143958](https://user-images.githubusercontent.com/2348771/35681548-031a4d6e-075e-11e8-9327-0abe60ff63cb.png)

**Comment by Riotism** [comment]
Are you using the latest commit? I have recently added some symlinks for the music folder icon.

**Comment by Tichy** [comment]
I was using the set released on opendesktop, ver 0.5.0. I now installed from git, but in this case the icon is missing.

![screenshot_20180202_071331](https://user-images.githubusercontent.com/2348771/35719205-960b3bd0-07e8-11e8-87ad-55391af55f9b.png)

**Comment by now-im** [comment]
I confirm the bug.

**Comment by Riotism** [comment]
I have pushed several bug fixes. Please get the latest commit and see if it's fixed.

**Comment by now-im** [comment]
no it is not.

**Comment by Tichy** [comment]
Now it's fixed for 32 and 48px icons, but it shows the colorful icon instead of the symbolic one for 16 and 22px
![screenshot_20180203_105623](https://user-images.githubusercontent.com/2348771/35766078-3c8694b2-08d1-11e8-8458-5d4887efba5d.png)![screenshot_20180203_105644](https://user-images.githubusercontent.com/2348771/35766079-3ca5f618-08d1-11e8-8c60-dc545c27a9bb.png)![screenshot_20180203_105658](https://user-images.githubusercontent.com/2348771/35766080-3cc355aa-08d1-11e8-81f7-6374cdba2084.png)

**Comment by now-im** [comment]
here is the problem I am facing using KDE dark theme.
![screenshot_20180203_182021](https://user-images.githubusercontent.com/22009014/35767117-0675b030-0910-11e8-9de3-5a3511bc5872.jpeg)
![screenshot_20180203_182604](https://user-images.githubusercontent.com/22009014/35767118-06b6c19c-0910-11e8-9868-7e5ee0a2037e.jpeg)

**Comment by Tichy** [comment]
In your screens I also see that the "pictures" icon is darker. Maybe like the one used for light themes.

**Comment by Riotism** [comment]
I have pushed more symlinks for symbolic icons. As to the darker pictures icon, please open a new bug.

**Comment by Tichy** [comment]
Just checked. Now it's all fine for the audio icon. I close this issue. Thanks.
