### ISSUE TITLE
Symbolic Link Left over qbittorrent icons

### ISSUE THREAD

**Issue by now-im** [keeferrourke/la-capitaine-icon-theme#345]
Qbittorrent got redesigned. Almost all of its icon can be covered by this theme only some is left. I can't find the action icon name, otherwise, I would do it myself. All necessary icon is available just symbolic link them.
![20180208_112420](https://user-images.githubusercontent.com/22009014/35957013-54d33412-0cc3-11e8-9bae-71dbe4dd4459.png)
![20180208_112454](https://user-images.githubusercontent.com/22009014/35957014-55145e4c-0cc3-11e8-9c56-d9c06e07aa2d.png)
Second one can be ignored if it is too much hassle.

**Comment by keeferrourke** [comment]
I don't have the time to dig through the application sources to find the correct icon names. Please look at the qbittorrent sources and locate the names of the icons that are missing.

**Comment by now-im** [comment]
I have tried for quite a while. This arch linux package souce list perfectly lists the locations.
https://www.archlinux.org/packages/community/x86_64/qbittorrent/files/
All I am getting is the main and system tray icon. If I could get the place I would do it myself. 
Any other place should I look at?
@riotism any idea?

**Comment by now-im** [comment]
Okay, I have cloned their git repo. May get the result soon.
