### ISSUE TITLE
Some problems in xfce

### ISSUE THREAD

**Issue by Kalle72** [keeferrourke/la-capitaine-icon-theme#35]
Hello,

first of all: Your icon theme looks really great! Thanks for that and your efforts!!!

Second: I found some problems (I use xfce on gentoo and use viewizard's ebuild):

1) Radiotray has 4 icons: radiotray, radiotray_on, radiotray_off, radiotray_connecting. At the moment the latter 3 are radiotray's original icons while you changed the first. I would suggest to exchange the latter three by your radiotray icon in different colours, e.g. yellow for connecting, grey for off ...

2) Xfce uses in the panel not the symbolic icons, but the regular ones (Compare the examples at the end ). Now the problem is that some icons of your theme have no regular version and the symbolic version is also used in the regular case (xyz.svg = xyz-symbolic.svg). Therefore the panel looks inconsistent. (E.g. the screenshooter has a regular picture while clipman, battery, volume and nm-applet have not)

To overcome this with hopefully minimal efforts, I have the following suggestions: 

A) Battery: One could use the regular versions of the elementary xfce theme as regular versions in your theme. I think they fit very well into the look.

B) Volume: Here one could use your "multimedia-volume-control" icon in different colours for audio-volume-....svg

C)  Nm-applet: The icon (if connected) itself is good, but one does not see it well, because it is white. So I would again suggest some colours. E.g. green for connection and red for disconnection. Can be the same problem for the wlan icons, but unfortunately I have no wlan, so I cannot test this.

D) Clipman seems to use the edit-paste icon. One could eventually use the icon which occurs in clipman's configuration dialogue. 
![clipman](https://cloud.githubusercontent.com/assets/14296454/18127507/1225f48c-6f81-11e6-8381-07e90968f1fe.png)

![example1](https://cloud.githubusercontent.com/assets/14296454/18127000/16d4ebc6-6f7e-11e6-968c-f76607c73261.png)
![example2](https://cloud.githubusercontent.com/assets/14296454/18127002/19c6a248-6f7e-11e6-84be-f7bd37d6fbdc.png)
![example3](https://cloud.githubusercontent.com/assets/14296454/18127003/1bd5f43a-6f7e-11e6-8f1c-7afa466442ca.png)

I hope my write-up was not too long!
With kind regards 
Kalle

**Comment by keeferrourke** [comment]
Awesome, thanks for pointing this out! And the more detail you provide, the easier it is for me to fix it ;)

I'll try to get this fixed soon!

**Comment by Kalle72** [comment]
Thanks a lot. I have two more ;-)

1) Xfce has no icon for the power manager --> One should link gnome-power-manager to xfce4-power-manager-settings.

2) Glabels has no icon --> One should link glabels-3.0 (it's really the icons name!) to easytag, because this icon fits perfectly. 

Thanks again!

**Comment by Kalle72** [comment]
And one more I forgot:

Evince with your theme has a much bigger window-decoration (pictures below) as with gnome's Adwaita theme. It seems that evince uses one of the following icons which aren't existing in your theme: "accessories-text-editor-symbolic", "accessories-text-editor-symbolic.symbolic".

With your theme it looks like evince uses in face of the missing icons the "accessories-text-editor" icon instead with a kind of "monochrome mode" which makes the icon bigger as it should. 

Therefore I would suggest to add "accessories-text-editor-symbolic", "accessories-text-editor-symbolic.symbolic" as a monochrome version of your  "accessories-text-editor" 

![adwaita](https://cloud.githubusercontent.com/assets/14296454/18165964/a0250094-7048-11e6-9ac5-76a1f8937ca6.png)
![example](https://cloud.githubusercontent.com/assets/14296454/18165965/a026e5b2-7048-11e6-8e99-a1984b37fce8.png)

Best regards 
Kalle

PS: I think now I mentioned everything I found ;-)

**Comment by keeferrourke** [comment]
@Kalle72 going backwards here.. I've fixed `apps/symbolic/accessories-text-editor.svg` and associated symlinks in commit 7d92c48; evince should render the "annotate" icon at the correct size now. I've opted to make this a pencil shaped icon, because it better communicates the editing/annotating behaviour it's most often used for.

5e717f1 should add the xfce-power-manager-settings and glabels-3.0 icons.

bc550c7 should add the radiotray_* icons.

The other suggestions you've made in your first post (re: battery, audio, wifi icons) will be implemented later, when I have a bit more extra time.

**Comment by keeferrourke** [comment]
Regarding the nm-applet icons, it never occurred to me to not make them white. GNOME recolours status icons, so I never noticed this to be an issue. 

A "dark" icon theme variant with light status/action/symbolic icons is supposed to be in the works anyway re: #4, so I guess I can get started on that by using the existing nm-applet icons.

I'll provide dark versions of the nm-applet icons (for contrast against light backgrounds/themes) in an update soon. Expect it in a day or so :)

**Comment by Pival81** [comment]
I'm also having some problems on xfce with the numix theme:
![selezione_005](https://cloud.githubusercontent.com/assets/15673222/18610680/9809ac84-7d22-11e6-9671-ba368a3686ab.png)
I think we really need a dark variant, as noted in #4

**Comment by keeferrourke** [comment]
@Pival81 I'm aware of the issue, and am working on a fix, but it's a slow burn. There are a lot of icons that need light variants and I'm in school, so my work takes priority... but it will come in an update eventually.

**Comment by keeferrourke** [comment]
closing this for now as believe I addresses all the major issues here... again, the dark variant will come at a later date &ndash; hopefully after midterms.
