### ISSUE TITLE
gnome tweaks tool wrong icon in debian 9

### ISSUE THREAD

**Issue by cedjo** [keeferrourke/la-capitaine-icon-theme#352]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| MyApplication    | `app-icon` | Application | 			   |

### Desktop file

```
# Paste your desktop file below.
# Do NOT include non-English translation strings.

[Desktop Entry]
Name=Tweaks
Comment=Tweak advanced GNOME 3 settings
Icon=org.gnome.tweaks
Exec=gnome-tweaks
Terminal=false
Type=Application
StartupNotify=true
StartupWMClass=gnome-tweaks
Categories=GNOME;GTK;Settings;
# Translators: Search terms to find this application. Do NOT translate or localize the semicolons! The list MUST also end with a semicolon!
Keywords=Settings;Advanced;Preferences;Extensions;Fonts;Theme;XKB;Keyboard;Typing;
OnlyShowIn=GNOME;Unity;Pantheon;


```

The icon is not displayed correctly in Debian 9 (Gnome 3.26.2) 
Adding a symbolic link like this corrected the issue:
ln -s ../scalable/gnome-tweak-tool.svg ./org.gnome.tweaks.svg

in the apps/symbolic folder.

Cheers

**Comment by keeferrourke** [comment]
should be fixed now.
