### ISSUE TITLE
Icon Request: Bitwarden

### ISSUE THREAD

**Issue by linusg** [keeferrourke/la-capitaine-icon-theme#353]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Bitwarden    | `bitwarden` | Password manager | ![image](https://user-images.githubusercontent.com/19366641/36923015-2fb30e24-1e6a-11e8-816f-f2b166c489cb.png) |

### Desktop file

```
[Desktop Entry]
Name=Bitwarden
Comment=A secure and free password manager for all of your devices.
Exec="/opt/Bitwarden/bitwarden" %U
Terminal=false
Type=Application
Icon=bitwarden
Categories=Utility;
```

**Comment by keeferrourke** [comment]
Hopefully commit db68fe is sufficient :)

**Comment by linusg** [comment]
I think so 😃
Thanks for the fast symlink!
