### ISSUE TITLE
Request - Extend support to Pantheon

### ISSUE THREAD

**Issue by btd1337** [keeferrourke/la-capitaine-icon-theme#36]
Pantheon needs minor adjustments on Arch Linux, Is it possible to do that?

Basically adjustments are the indicators icons.

Icons that need adjustments: indicator of **sound**, **mail**,  **power**.

**_La Capitaine icons_**
![screenshot from 2016-09-09 23-08-13](https://cloud.githubusercontent.com/assets/11943860/18407332/b616bafe-76e3-11e6-8ddf-9053b0158078.png)

**_Elementary OS icons_**
![screenshot from 2016-09-09 23-09-12](https://cloud.githubusercontent.com/assets/11943860/18407334/c9c76f3a-76e3-11e6-9ae2-18a0f810071f.png)

**Comment by keeferrourke** [comment]
I'm going to need the names of these icon files in order to make a fix.

**Comment by btd1337** [comment]
These are the icons: 

https://www.dropbox.com/sh/07ex6nt1i3t5tmc/AACRRfem80KqkqIc539bm-_Ia?dl=0

**Comment by keeferrourke** [comment]
I'll try to get this fixed this weekend!

**Comment by keeferrourke** [comment]
I got busy with school, but I'll try to fix this this weekend if I find time... no guarantees though, I'm about to get slammed with midterms.

**Comment by keeferrourke** [comment]
This should have been fixed in f67424fb3bcc7a84111b6cd939e52e4d23c9c4a1 when I added the inherit property to `index.theme`. Specific adjustments to eOS icons will come later, stay tuned.

**Comment by cemetary** [comment]
@keeferrourke 

 This was the first thing I tried. Adding Inherits=elementary,breeze,gnome not working. :-(

![wingpanel_001](https://cloud.githubusercontent.com/assets/10538213/20445605/59e3cc1a-ad9b-11e6-8317-d22c94535f97.jpg)

**Comment by keeferrourke** [comment]
@cemetary do you mind explaining exactly what is wrong with your posted screenshot? Those icons are all displaying properly.

**Comment by cemetary** [comment]
@keeferrourke 

Al right, sorry, my bad.

They say that a picture is worth a thousand words, so I will try to clarify the point with these three screenshots.

**elementary Loki (default icon theme):**
![elementary loki default](https://cloud.githubusercontent.com/assets/10538213/20730204/c484b518-b64a-11e6-975a-e55bfbed2264.png)

**Papirus icon theme:**
![papirus](https://cloud.githubusercontent.com/assets/10538213/20730230/e1f23332-b64a-11e6-9641-6178f849dd85.png)

**La Capitaine icon theme**
![la capitaine](https://cloud.githubusercontent.com/assets/10538213/20730269/0ad099f6-b64b-11e6-848b-82e7b174b20e.png)


Will there be a workaround to homogenize the size of the icons? Honestly, I do not have the technical skills to try to solve this problem. :-!

Thanks. :-)

**Comment by keeferrourke** [comment]
@cemetary hahaha my bad, I'll try to get it fixed soon.

**Comment by btd1337** [comment]
Adding this file to the folder actions/24 Its indicator normalizes the size.
[system-shutdown-symbolic.svg.zip](https://github.com/keeferrourke/la-capitaine-icon-theme/files/671610/system-shutdown-symbolic.svg.zip)

**Comment by keeferrourke** [comment]
@btd1337 I recently adjusted the sizing and padding of a *lot* of icons, is the here still an issue?

Sorry I haven't got around to adding your zipped icons yet... Stay posted I guess :)

**Comment by btd1337** [comment]
Unresolved issue.

PS: Only a small feedback: Try to vary more the colors of your icons. See how the blue color has prevailed too much.

![la-capitaine](https://cloud.githubusercontent.com/assets/11943860/22090359/3a531d0c-ddd8-11e6-9baa-f3dc62728db3.jpeg)

Compare with OS X icons

![captura de tela de 2017-01-18 23 49 05](https://cloud.githubusercontent.com/assets/11943860/22090459/ce11a1a8-ddd8-11e6-84f4-e479ee7ef62b.jpeg)

That was just a suggestion for you to improve more and more.

**Comment by keeferrourke** [comment]
Noted. Improving the colour scheme is a difficult thing to achieve as I cannot ever be sure which suite of applications you'll install. Typically I try to keep them distinct, but there's really not much one can do.

To-do on this issue:

- [] add support for attached zip of icons (see previous comments)
- [] double check sizing/padding is correct for all icons

**Comment by btd1337** [comment]
Don't use both the blue color is already good start.

**Comment by btd1337** [comment]
Changes for improving color balance on elementary OS

```
cd apps/scalable/

rm preferences-desktop.svg
ln -s preferences-system.svg preferences-desktop.svg

rm system-software-install.svg
ln -s software.svg system-software-install.svg

rm multimedia-audio-player.svg
ln -s rhythmbox-alt.svg multimedia-audio-player.svg
#! or zynaddsubfx.svg

rm notes.svg
ln -s wiznote.svg notes.svg

rm feedreader.svg
ln -s internet-news-reader.svg feedreader.svg
```


![captura de tela de 2017-02-05 19 56 44](https://cloud.githubusercontent.com/assets/11943860/22630231/4c190a8e-ebdd-11e6-95fe-43b18ddb060a.jpeg)

**Comment by keeferrourke** [comment]
@btd1337 I can't endorse the changes you've made as they're specific to your set up only. I have however symlinked `internet-new-reader.svg` to `feedreader.svg` per your request, as that icon didn't actually exist.

**Comment by keeferrourke** [comment]
@btd1337 check out commit https://github.com/keeferrourke/la-capitaine-icon-theme/commit/de7d034c26304b78cd5cfa9728fa704d10c5124e, it should hopefully (finally) fix the sizing issues you've been having with the Pantheon desktop.

The symbolic status icons were a mess.

**Comment by btd1337** [comment]
Closed? The problem has not yet been fixed.

![captura de tela de 2017-02-15 00 35 10](https://cloud.githubusercontent.com/assets/11943860/22958606/773181ba-f317-11e6-9a9e-d7b21dddbec3.jpeg)

**Comment by keeferrourke** [comment]
Reopened... Evidently more investigation required. I don't understand what can possibly be wrong with Pantheon though.

**Comment by keeferrourke** [comment]
Closing this as conversation appears to have moved to #241 .
