### ISSUE TITLE
[Request] Meld Diff Viewer

### ISSUE THREAD

**Issue by BenJetson** [keeferrourke/la-capitaine-icon-theme#362]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Meld   | `meld` | Application | ![image](https://user-images.githubusercontent.com/10427974/38399177-b0c6e956-3916-11e8-86b6-91416c174376.png) |

### Desktop file

```
[Desktop Entry]
Name=Meld
GenericName=Diff Viewer
X-GNOME-FullName=Meld Diff Viewer
Comment=Compare and merge your files
Keywords=diff;merge;
Exec=meld %F
Terminal=false
Type=Application
Icon=meld
MimeType=application/x-meld-comparison;
StartupNotify=true
Categories=GTK;Development;
X-GNOME-Bugzilla-Bugzilla=GNOME
X-GNOME-Bugzilla-Product=meld
X-GNOME-Bugzilla-Component=general
```

Just wanted to say thanks for the awesome amount of work that went into making all of these icons. They make GNOME look great! :smiley:

**Comment by BenJetson** [comment]
Awesome work, @zencubic! The Meld icon looks great.

**Comment by zencubic** [comment]
@BenJetson Thanks!
