### ISSUE TITLE
No ticks on checkboxes elementary-os (Not a icon request!)

### ISSUE THREAD

**Issue by surajmandalcell** [keeferrourke/la-capitaine-icon-theme#369]
#### On elementary-os which uses gtk-3.22 the check-boxes does not appear tho i only tested it in firefox other apps like chrome are also affected. Here are some screenshots for better explanation.  
![checkboxproblem_sample1](https://user-images.githubusercontent.com/11650177/40275570-ba2c449c-5c10-11e8-8d0f-7f9b38b17578.png)
---
![checkbox_sample2](https://user-images.githubusercontent.com/11650177/40275571-ba60947c-5c10-11e8-82d4-7a3ab6ef290e.png)
---
See? no ticks in checkbox.

**Comment by LvLs9** [comment]
Hm... I use elementary OS 0.4.1, but with gtk-3.18 all checkboxes is OK. For example, standart Scratch text editor on screen.

![image](https://user-images.githubusercontent.com/34302242/40276030-4d3e50ee-5c08-11e8-86c6-bf65c1624139.png)

**Are you using elementary OS 5.0 which in beta?**

**Comment by surajmandalcell** [comment]
Yup, 5.0 it is. But here's the catch when i change the themes either default or any other like arc or adapta the checkbox stays same but when i change icon theme and wolla! ticks come back.

Btw I'm working on my theme and came up with the issue heres the repo for the project if you need more info or such. https://github.com/surajmandalcell/elementary-x

**Comment by keeferrourke** [comment]
You are confusing GTK and icon themes on this issue. Try a different GTK theme like [Arc](https://github.com/horst3180/arc-theme) if you don't like the default styling on elementary OS.

**Comment by surajmandalcell** [comment]
Ok for once ill explain then its up to you if you want to re-open this issue or not
For this recent test i used https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

#### Here's what i did to test the problem source  

- elementary default gtk theme + elementary default icon theme = Tick shows
- elementary default gtk theme + la capitaine icon theme = Tick does not show
- elementary-x gtk theme + elementary default icon theme = Tick shows
- elementary-x gtk theme + la capitaine icon theme = Tick does not show  

---
Tick shows ![](https://user-images.githubusercontent.com/11650177/40277381-ebe5b7e0-5c3b-11e8-9edd-884302884ba1.png)


Tick does now show ![](https://user-images.githubusercontent.com/11650177/40277401-294f0ad2-5c3c-11e8-9449-a156a2fd9483.png)

**Comment by keeferrourke** [comment]
I cannot reproduce this issue. On Fedora Workstation 28, with `elementary-theme-gtk3` and `elementary-icon-theme` installed from the official repositories, this is how the same page shows with Firefox 60.0. Before I took each screenshot, I restarted both GNOME Shell and Firefox.

![image](https://user-images.githubusercontent.com/6888381/40282333-ac97c722-5c22-11e8-9326-b6b2d29764fa.png)
<small>**Figure 1a**. Elementary GTK and Elementary icons.</small>

![image](https://user-images.githubusercontent.com/6888381/40282369-36f470c8-5c23-11e8-941b-bee65751ba1e.png)
<small>**Figure 1b**. Elementary GTK and La Capitaine (latest commit from master)</small>

![image](https://user-images.githubusercontent.com/6888381/40282421-d8bc674e-5c23-11e8-9994-51c5eb4bd816.png)
<small>**Figure 1c**.  [Arc-OSX-White GTK](https://github.com/LinxGem33/X-Arc-White) and Elementary icons.</small>

![image](https://user-images.githubusercontent.com/6888381/40282396-825706b6-5c23-11e8-9108-6434a42f5fc5.png)
<small>**Figure 1d**.  Arc-OSX-White and La Capitaine (latest commit from master). My usual set up.</small>

As you can see,  from the figures, the styling of the checkboxes in Firefox is dependant on the GTK theme, not the icon theme. Something is probably happening on your system that is not updating your theme resources properly.

**Comment by keeferrourke** [comment]
Indeed the problem appears to be with your custom GTK theme https://github.com/surajmandalcell/elementary-x.

![image](https://user-images.githubusercontent.com/6888381/40282509-59f50356-5c25-11e8-9ff0-ed3e61e423b7.png)
<small>**Figure 2a**. Your GTK theme "Elementary-x" with Elementary icons.</small>

![image](https://user-images.githubusercontent.com/6888381/40282521-83f4e202-5c25-11e8-8f8a-712fe24a57dc.png)
<small>**Figure 2b**. Your GTK theme "Elementary-x" with La Capitaine (latest commits from master).</small>

**Comment by surajmandalcell** [comment]
Damn it fixed itself somehow, just letting you ppl know ;-;
