### ISSUE TITLE
Missing Icons in ElementaryOS 0.4 "Loki" 

### ISSUE THREAD

**Issue by arshubham** [keeferrourke/la-capitaine-icon-theme#37]
The missing icons are: 
In System Settings
- Parental Controls
- Applications
- Elementary Tweaks 
     - Launcher 
     - Cerbere
![screenshot from 2016-09-10 11 46 01](https://cloud.githubusercontent.com/assets/14235191/18408396/4d57981c-774c-11e6-8a37-f08c06364b07.png)
![screenshot from 2016-09-10 11 46 46](https://cloud.githubusercontent.com/assets/14235191/18408395/4d545274-774c-11e6-8c7e-166d51aab112.png)
In Applications

-  Screenshot icon
![screenshot from 2016-09-10 11 48 24](https://cloud.githubusercontent.com/assets/14235191/18408405/a3c42cd8-774c-11e6-855b-d7803f1e8c7f.png)

- in Photos - crop , straighten etc icons are missing
![screenshot from 2016-09-10 11 50 40](https://cloud.githubusercontent.com/assets/14235191/18408418/ec2367f0-774c-11e6-8059-35bf39c07f91.png)

Others - 
Settings icon in epiphany and other eOS apps need a better icon
Better icon needed for calculator
Libre Office icons are missing

**Comment by keeferrourke** [comment]
I need the names of the files that these icons use, or I cannot implement a fix. Follow the guidelines outlined in the readme for submitting icon requests.

**Comment by keeferrourke** [comment]
Regarding settings icons, define a "better" icon. Design is subjective, and that is hardly a useful observation.

**Comment by keeferrourke** [comment]
@arshubham I can't do anything about this unless you provide the required icon names, please let me know what's missing, this issue has sat quiet for 20 days.

**Comment by keeferrourke** [comment]
I'm closing this because it's over a month old and OP hasn't given useful feedback. Feel free to bring to my attention again later though.

**Comment by keeferrourke** [comment]
Managed to fix this in f67424fb3bcc7a84111b6cd939e52e4d23c9c4a1, retheming of the elementary OS icons will come later, as I've addressed in #36
