### ISSUE TITLE
Need quick information/fix

### ISSUE THREAD

**Issue by surajmandalcell** [keeferrourke/la-capitaine-icon-theme#370]
Need : filename/symbolic link name for the power icon
Details : as addressed in issue #64 and #241 the app indicators and status bar icons are a bit messed up in pantheon. So i am making a temporary workaround. I did change all icons except the power icon which i need help with. Please do tell which file/link is responsible for it so i can edit and normalize the size of it. Thanks in advance

Default elementary icon theme
![elementary](https://user-images.githubusercontent.com/11650177/40403872-53234250-5e72-11e8-9f57-a060f856aa98.png)

My patched la-capitaine icon theme
![la-capitaine](https://user-images.githubusercontent.com/11650177/40403893-6ec0f3c2-5e72-11e8-9abe-4b5f48b64a19.png)

**Comment by keeferrourke** [comment]
I honestly don't know what the naming scheme is for icons that Pantheon uses. I'm probably not going to be much help here. If you do figure out how to normalize the icons for Pantheon without breaking other desktops, let me know and/or submit a PR.

**Comment by surajmandalcell** [comment]
Here is my fixed la-capitaine icon script used in my gtk theme  

**What does it do?**
```
1. Clones your repo
2. Copies status/24 icons from elementary os icon theme to la-capitaine panel/24 folder
3. Deletes 2 occurrences of system-shutdown-symbolic.svg
4. Sets first fallback theme to elementary for better compatibility
```
It is a workaround which works fine in all general cases and happen to fix a lot of problems with wingpanel icons.
https://github.com/surajmandalcell/elementary-x/blob/master/install_fixed_icons.sh

**Comment by LvLs9** [comment]
In dependency of percentage not every time the battery-icon is shown in the right way.

For example, when battery have 35-40%, icon is empty.

**Comment by surajmandalcell** [comment]
Closing issue for now
