### ISSUE TITLE
PPA discontinued?

### ISSUE THREAD

**Issue by vaskark** [keeferrourke/la-capitaine-icon-theme#372]
Just wondering about the status of the ppa. Will it be online again soon?
Thanks.

**Comment by keeferrourke** [comment]
Hi there, I don't maintain the PPA, so I can't really comment on it. How long has it been down for?

The only official method for installation that I can endorse is as follows:
```
git clone https://github.com/keeferrourke/la-capitaine-icon-theme $HOME/.icons/la-capitaine
```

**Comment by keeferrourke** [comment]
@igor-dyatlov maintains the PPA. perhaps he has information?

**Comment by igor-dyatlov** [comment]
[PPA](https://launchpad.net/~dyatlov-igor/+archive/ubuntu/la-capitaine) repository works.
