### ISSUE TITLE
Bug: Network Manager Applet icon broken (on VPN)

### ISSUE THREAD

**Issue by null-von-sushi** [keeferrourke/la-capitaine-icon-theme#376]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| network-manager-applet-indicator    | `???` | Application/Bug | 	???	   |

### Desktop file

```
# Paste your desktop file below.
# Do NOT include non-English translation strings.
[Desktop Entry]
Name=Network
Comment=Manage your network connections
Icon=nm-device-wireless
Exec=nm-applet
Terminal=false
Type=Application
NoDisplay=true
NotShowIn=KDE;GNOME;
X-GNOME-Bugzilla-Bugzilla=GNOME
X-GNOME-Bugzilla-Product=NetworkManager
X-GNOME-Bugzilla-Component=nm-applet
X-GNOME-UsesNotifications=true

```

Not an icon request, but a bug report. The icon for network manager has a huge key overlay hiding the actual network-manager/wifi icon. This seems to only happen on secure VPN connections.
![nm](https://user-images.githubusercontent.com/13616397/43037298-4fa512be-8d04-11e8-9f0c-c1e47155d68b.png)
PS: Sorry if I didn't fill out the table correctly

**Comment by keeferrourke** [comment]
What desktop environment is this?

**Comment by null-von-sushi** [comment]
Screenshot was taken on Budgie. I am pretty sure this is DE-independent though? I also have KDE installed, and running `nm-applet` there seems to give me the same (except a lot blurrier)
![image](https://user-images.githubusercontent.com/13616397/43053256-9e337338-8e23-11e8-9f78-e67de58235da.png)

**Comment by keeferrourke** [comment]
Hmm, you're right. I'll take a look at it and see what I can find. Gnome completely replaces the wireless indicator with the 'key' VPN icon, it doesn't overlay them.

I'll try to tweak the design to be a bit clearer this week.

**Comment by null-von-sushi** [comment]
Yeah, it would be nice to not have to use gnome though :stuck_out_tongue: 
Thanks for taking a look! :slightly_smiling_face:

**Comment by keeferrourke** [comment]
Heh. I spent some time yesterday migrating to KDE because I was getting tired of the GNOME memory leaks and crashes :joy:. I'll try to get this bug squashed by the end of the week, but I'm a bit impeded since I broke my wrist Friday >.<

**Comment by keeferrourke** [comment]
Fixed :smile: here's what my Budgie panel looks like now.

![image](https://user-images.githubusercontent.com/6888381/43372140-707e64b4-9352-11e8-9f8f-78d05b0112a4.png)

**Comment by null-von-sushi** [comment]
Thank you very much for fixing it !
