### ISSUE TITLE
Reduce redundancies with panel and status icons, fix keyboard indicator colours

### ISSUE THREAD

**Issue by sankarsana** [keeferrourke/la-capitaine-icon-theme#38]
This is the best theme fore me! Thank you very much!

But i have litle bug on my unity panel (ubuntu 16.04).

![2016-09-14 23-23-40_1](https://cloud.githubusercontent.com/assets/13602327/18529036/2533abc4-7ad4-11e6-9ce5-6314b40ac904.png)

**How to fix it?** Maybe I'm doing something wrong?

**Comment by jmrfrosa** [comment]
Same problem here, had to revert to previous release.

**Comment by newfobject** [comment]
I have found a solution.

- Download the previous version
- Unpack it
- Copy panel folder from previous version to your theme folder
- unity --reset-icons in terminal(maybe not needed)

**Comment by keeferrourke** [comment]
@newfobject I removed the panel folder (and merged it into status) because I didn't believe it was used by any environments anymore. I'll put it back. @sankarsana Thanks for reporting this.

**Comment by keeferrourke** [comment]
Hopefully fixed in cacb662. I've added `panel/` back.

**Comment by sankarsana** [comment]
But they are white.:(
![2016-09-16 08-18-26_1](https://cloud.githubusercontent.com/assets/13602327/18576088/d6da4244-7be6-11e6-8aca-317cee2bdc63.png)

I especially found the light panel theme early. Do I have to move to the dark now?
(Sorry for my English.)

**Comment by keeferrourke** [comment]
@sankarsana the panel icons are white because I restored theme from an old commit -- they were removed because it was noted that they didn't match the rest of the theme.

I believe `status/` has all the same icons as are found in `panel/` but I think it's some weird Ubuntu-ism that the `panel/` folder is required. I'm going to look at what some other themes have done and play with some symlinks to try to fix it... I'm just busy as I've just started back at school again. Please bear with me. I'll do some refactoring when I get a solid chance to do so.

**Comment by keeferrourke** [comment]
@sankarsana check out commit 44e68fdedfce88fd4921d6024e1e9a213be3f9f3 and see if that fixed your panel icons under Unity. I've recoloured them all to be dark grey (matching other status icons in the theme) instead of white.

**Comment by sankarsana** [comment]
@keeferrourke now everything is fine! Thank you very much!
But I recoloured keyboard Indicators in `panel/`. They looked too dark.
Renamed bluetooth icons.
Added `status/symbolic/diodon-panel.svg`
![2016-09-18 21-40-44](https://cloud.githubusercontent.com/assets/13602327/18618148/2aca638a-7de9-11e6-84dc-59026c93c4d0.png)

**Comment by keeferrourke** [comment]
@sankarsana would you mind letting me know what files you renamed to get your bluetooth icon to work right? I can add the proper symlinks in another commit. 

Also, could you please provide `status/symbolic/diodon-panel.svg` so that I may update the theme so that other users of diodon may also have a completely themed experience?

**Comment by sankarsana** [comment]
I create temporary [repository](https://github.com/sankarsana/changesIn_la-capitaine-icon-theme/tree/master/status/symbolic) for your convenience.
`diodon-panel.svg` - not the best. And `bluetooth-paired.svg` - i do not like even more (i slap together).
Could you draw them yourself in accordance with the style?

**Comment by keeferrourke** [comment]
@sankarsana honestly I thought the use of the panel directory was obsoleted. It must be some Ubuntu-sm that I have to account for with regards to the `panel/16` and `panel/24` directories. When I merged the content of `panel/` to `status/` and dropped the `panel/` directory in commits c9a4aa32546bbf1f51f0ac91bb96d9b9aea3268b and ff2ac67401fd36de1a1dcae10af50de77d0327ed it broke your Unity panel... so it must be necessary for some reason.

I'll look into cleaning up the theme over the few weeks and see if it can better organised.

**Comment by keeferrourke** [comment]
phase one of the Great Clean Up&trade; : 
 * deleted `panel/24/indicator-keyboard-*` in commit 3620d0b as suggested by @sankarsana 

Hoping this reduces redundancies and doesn't have any adverse affects on the the usability of this theme. AFAIK it should be fine, dups of all the icons are in `panel/16/`

**Comment by keeferrourke** [comment]
Should be completely fixed at this point, as of the commits that resolved issue #4. More redundancy checking needs to be done, but I'm fairly certain the main points of this issue have been addressed. Closing for now.
