### ISSUE TITLE
Gnome crashes on Ubuntu 18.04

### ISSUE THREAD

**Issue by diogodomanski** [keeferrourke/la-capitaine-icon-theme#388]
I installed La Capitaine Icon Theme in a fresh installation of Ubuntu 18.04. Everytime any system dialog was opened (for example, a "Save as..." dialog for a download in Firefox, or the dialog to choose a new printer to be added), gnome crashes, my user's session was closed and the login screen was shown.

I took sometime to realize that the problem was related to the icon theme - in this case, whenever the theme La Capitaine was active.

It would be great if this issue was fixed.

**Comment by keeferrourke** [comment]
Please make sure that you are using the latest version (0.6.0) which addresses a very similar error. If you continue to have this problem on 0.6.0, I'll need a bit more information (a stack trace of an affected process would be nice).

**Comment by keeferrourke** [comment]
Possibly related to #375

**Comment by keeferrourke** [comment]
@osilkin98 I would imagine that your crashes come from a theme that is missing an icon called `window` which is the default icon that mutter assigns if it can't find anything else (but doesn't appear to be present in the `gnome` icon theme :man_shrugging:).

The fixes the closed #375 should also close this issue. Please update to the latest version of La Capitaine. Feel free to reopen this if you continue to have issues on 0.6.0+
