### ISSUE TITLE
Request icons for .rar and C header file

### ISSUE THREAD

**Issue by handrake0724** [keeferrourke/la-capitaine-icon-theme#39]
Thanks for the great work.

After installing it, I have found icons for rar file and C/C++ header file is missing.

**Comment by keeferrourke** [comment]
Can you please post the mimetypes here? I can make those really quick.

**Comment by handrake0724** [comment]
It looks like
text/x-c++hdr
text/x-chdr

Thanks.

**Comment by keeferrourke** [comment]
> rar is fine, which is in the mimetype folder but is not assigned properly.

what do you mean by this? if the mimetype icon is not assigned properly, that would suggest to me that rar is not fine.

**Comment by handrake0724** [comment]
At first, I thought rar icon was missing but the icon was there in mimetype folder of la-capitaine-icon. So, rar issue is about #40. that is why I said rar is fine.
Thus, missing icon is text/x-c++hdr and text/x-chdr.

**Comment by keeferrourke** [comment]
Still not sure on the rar mimetypes,  but c and c++ header mimetype icons should be fixed now. Sorry it took so long.

Closing this issue, but as always, if there's an issue - ping me and I'll reopen it.
