### ISSUE TITLE
Ubuntu 18.04 gnome-tool'icons isn't useful

### ISSUE THREAD

**Issue by amosniu** [keeferrourke/la-capitaine-icon-theme#391]
In Ubuntu 18.04,gnome-tweak-tool's icons can't prettified，please repair,Thanks.

**Comment by amosniu** [comment]
And my installed version is 0.5.0,terminal's information is "la-capitaine-icon-theme is the latest version",can you tell me what's wrong witn me?thanks.

**Comment by amosniu** [comment]
And in Ubuntu 18.04,pycharm-community's icons can't prettified,but in Fedora 28,it works.

**Comment by keeferrourke** [comment]
Please update to 0.6.0. You can find the release on OpenDesktop here: https://www.opendesktop.org/p/1148695/
