### ISSUE TITLE
 Symbolic link for .ttf absent in KDE

### ISSUE THREAD

**Issue by demoy** [keeferrourke/la-capitaine-icon-theme#392]
(https://user-images.githubusercontent.com/2396524/44005101-3853ac34-9e33-11e8-9e33-f2d7a9fc1543.png)
(viewing application: Dolphin, KDE default filemanager)
Note: This issue is not present in Gnome.

Doing some simple searching Dolphin appears to expect [/mimetypes/*/font-ttf.svg] which is absent in La Capitaine. 

EDIT: sorry for not following the require format it was too confusing for me.

**Comment by keeferrourke** [comment]
https://github.com/keeferrourke/la-capitaine-icon-theme/commit/498b4fa8812048ef7e16ba4a3bbfbeb008ee2e7c should fix this. Hopefully.
