### ISSUE TITLE
Crashes Linux Mint 19 desktop (Cinnamon)

### ISSUE THREAD

**Issue by tchuyev** [keeferrourke/la-capitaine-icon-theme#393]
Installed from PPA:
$ sudo add-apt-repository ppa:dyatlov-igor/la-capitaine
$ sudo apt update
$ sudo apt install la-capitaine-icon-theme

Applying the icon theme would work no problem in current session.

However, Linux Mint 19 desktop (Cinnamon) crashes upon reboot: the only way to recover is to revert back to previous theme (e.g. Mint-Y)

**Comment by copperly123** [comment]
this happened to me too, Linux mint 19 cinnamon. As soon as I installed the icons and restarted cinnamon the whole thing crashed into this really broken mess. I managed to revert the icons and get it back to normal. this had happened before when I first installed Linux mint 19 but I never found the problem back then (I was doing a lot of programs installing and stuff that could've been the problem too) and resorted to a timeshift.

**Comment by nocode99** [comment]
I faced this problem as well and you can go into recovery mode and disable the theme.

**Comment by keeferrourke** [comment]
Hi there, prior to release version 0.6.0, a critical `window` icon was missing and caused crashes under some GTK-based environments. I cannot guarantee that third party repositories are up-to-date, so I recommend that you install the icon theme by cloning the repository or downloading from [releases](https://github.com/keeferrourke/la-capitaine-icon-theme/releases/tag/v0.6.0).

As it seems that @igor-dyatlov's PPA is out of date, I will de-list it from the README for the time being.

If you update to version 0.6.0, you'll find that you aren't affected by crashes any more, along with other improvements.
