### ISSUE TITLE
Link to recommended theme is broken

### ISSUE THREAD

**Issue by linusg** [keeferrourke/la-capitaine-icon-theme#397]
The theme you recommend in the readme seems no longer to live at https://github.com/LinxGem33/OSX-Arc-White, the user https://github.com/LinxGem33 doesn't exist anymore (changed name? left GitHub?).
This one claims to be a modified version of said theme: https://github.com/fusion809/macOS-Arc-White - I will leave the decision whether the theme recommendation should be updated or removed up to you.

**Comment by wowbaggerBR** [comment]
Actually, the developer decided to put an end to the project. He left GitHub, but the themes are all available to download on GitLab - allthough without any updates since April. 

https://www.gnome-look.org/p/1167049/

https://gitlab.com/LinxGem33/X-Arc-White

**Comment by linusg** [comment]
I used to had a dark macOS-ish theme too - after upgrading to Mint 19 The window borders would not be affected by the theme anymore. Thanks for the suggestion, "this" looks nice too!

**Comment by keeferrourke** [comment]
I'll probably just remove the theme recommendation in this case then. I won't recommend a theme that doesn't support more than just GNOME -- but I may start using @wowbaggerBR's suggestion myself :stuck_out_tongue:
