### ISSUE TITLE
snap installed pycharm can't prettify

### ISSUE THREAD

**Issue by amosniu** [keeferrourke/la-capitaine-icon-theme#400]
In Fedora 28,I install pycharm by snap,but the icon theme can't prettify,please repair,thanks

**Comment by linusg** [comment]
Most likely the icon is hard-coded to a png file, which you can only fix yourself. Read in the SUPPORT document for more information.

**Comment by keeferrourke** [comment]
Thanks for addressing this @linusg  :smile:
