### ISSUE TITLE
Please remove the icons of dead, discontinued and deprecated apps

### ISSUE THREAD

**Issue by gusbemacbe** [keeferrourke/la-capitaine-icon-theme#404]
Hello @GeovaneSchmitz, @keeferrourke, @linusg!

Please, remove the icons of dead, discontinued and deprecated apps, like AIM, Emesene (oh my Force, why did you put it? It is dead a decade ago!), Whatsie, Yahoo Messenger (discontinued two months ago).

Do you want to keep the corpses in your icon theme?

And do not forget of updating the README file, because `pacaur` and `yaourt` are discontinued and unsafe, you have to replace for `yay`.

**Comment by linusg** [comment]
I have no clue why you've mentioned me... I'm neither a collaborator nor a maintainer in this project, just a contributor.
I personally don't think this is an huge issue as each icon file is either just a few kB in size or even just a symlink. However that's not up to me to decide, as I've said. After all many icons land in this repository because there are active users of an application *requesting it*.

Why don't you go ahead and make a PR if you see a high priority issue in this? @keeferrourke will either appreciate the time you've saved him or decline the proposal anyway.

j.m.2.c.

**Comment by gusbemacbe** [comment]
> I have no clue why you've mentioned me... I'm neither a collaborator nor a maintainer in this project, just a contributor.

AH, sorry. I thought you are a collaborator. Sorry!

> After all many icons land in this repository because there are active users of an application requesting it.

It is impossible, the servers of AIM, Copy, MSN Messenger, Yahoo Messenger and other dead apps have already stopped of working The users will not be able of entering that. 

> Why don't you go ahead and make a PR if you see a high priority issue in this? @keeferrourke will either appreciate the time you've saved him or decline the proposal anyway.

Only if he wants, I will do for him. I won't pull request without his authorisation or approval.

**Comment by keeferrourke** [comment]
Despite the fact that those services are no longer in use, there are almost certainly applications that still those icons. What are other major icon projects doing? Last I check Numix still had those icons... and I'd rather maintain compatibility with those few apps that might still rely on these.

**Comment by gusbemacbe** [comment]
Hi @keeferrourke 

> there are almost certainly applications that still those icons. 

Where is the verb you have missed? I am trying to understand this sentence. 

> Last I check Numix still had those icons... 

Then I was going to report to Numix Team. In my [Suru++ 20](https://github.com/gusbemacbe/suru-plus), I have removed all the icons of dead applications. In our [Suru++ Ubuntu](https://github.com/Magog64/suru-plus), we also have removed them.

**Comment by gusbemacbe** [comment]
The app Emesene, which is MSN Messenger, is shut down. The official site of Emesene (http://blog.emesene.org/) is also shut down.

At Github, the latest version of Emesene stopped of being developed was in 2012, exactly in that MSN was declared extinct by Microsoft. 

See https://github.com/emesene/emesene/issues/1590, which Emesene will no longer work since the server have been shut down by Microsoft. In other comments, members of the project declared their project to be abandonware.

I checked the Ubuntu Package Search, Emesene has been removed from Ubuntu 14.04.

* See the official article of AOL, saying the service **is officially shut down and no longer work.**: https://help.aol.com/articles/aim-discontinued
* In the official article of Yahoo, it says officially that **you'll no longer be able to access your chats and the service will no longer work**: https://help.yahoo.com/kb/SLN28776.html

* Copy shows the advice: https://www.copy.com/
