### ISSUE TITLE
Minecraft launcher icon causes crashes on GNOME

### ISSUE THREAD

**Issue by pitcer** [keeferrourke/la-capitaine-icon-theme#406]
Searching Minecraft launcher in GNOME Activities causes desktop environment crash. Removing first gradient layer of icon or removing icon completely resolves the problem. Occurs on GNOME 3.28 and 3.30.

I think this icon was added by a mistake. Addition is in unrelated commit eada8a8 and file is an Inkscape project, not raw svg.

**Comment by keeferrourke** [comment]
oof. ok. I definitely didn't mean to commit that, since I was toying with a few designs and weighing them against an existing PR for the Minecraft icon.

I'll remove it from the project for now. Thanks for pointing this out!
