### ISSUE TITLE
[Bug] status/panel icons incorrectly sized

### ISSUE THREAD

**Issue by cemetary** [keeferrourke/la-capitaine-icon-theme#42]
![screenshot from 2016-10-02 17 30 24](https://cloud.githubusercontent.com/assets/10538213/19024704/a11fb714-88c6-11e6-9a2a-0d8b69a3c4cd.png)

Hi, there.

In elementary Loki I have these two big icons in panel.

**Comment by keeferrourke** [comment]
@cemetary aware of the issue. It's a problem for at least several status/panel icons and a few applications/places icons &ndash; and I'm going to try to fix the sizing issues... but that requires manually going through hundreds of SVGs to fix them. 

If you need a quick fix locally, try resizing `status/symbolic/audio-*` and `panel/16/system-devices-panel.svg` to 16x16. If eOS uses a larger size they should scale up appropriately...

Honestly I blame a lot of desktop environments for not knowing how to resize SVGs properly. This seems to be an issue at least in Budgie and Pantheon, if not others.

**Comment by keeferrourke** [comment]
This issue seems similar to #36, I'll try to get it resolved when I go to tackle it in the near future.

**Comment by cemetary** [comment]
Thanks. :)

**Comment by keeferrourke** [comment]
This *should* be fixed by commit https://github.com/keeferrourke/la-capitaine-icon-theme/commit/de7d034c26304b78cd5cfa9728fa704d10c5124e.
