### ISSUE TITLE
[request] Operating systems icons

### ISSUE THREAD

**Issue by daltones** [keeferrourke/la-capitaine-icon-theme#43]
This is not a request for application or file type, but I think it would be nice.

Like many other people, I have a Windows installed inside a VM. When I was using Numix I saw that there's an icon with the MS Windows logo, so I associated that icon to my VM shortcut.

So my suggestion/request is for icons of logos of other OS, like the ones of Linux Distributions already existing.

Oh, and thanks for this great theme! 😃

**Comment by keeferrourke** [comment]
@daltones noted, any operating systems in particular?

off the top of my head I can think of:
 * Windows 8/10
 * Windows XP/Vista/7
 * older Windows(??) could this just be symlinked to Windows 7 and below?
 * various BSDs
 * Android (?)

Is this list too comprehensive? not comprehensive enough? how would you like the icons named?

Let me know.

**Comment by daltones** [comment]
@keeferrourke actually I was thinking just in a generic Windows icon. But if you could make all these, great!

Numix Circle has just a `windows` icon.

**Comment by keeferrourke** [comment]
solid, I'll add this to my to-do.

**Comment by dyrnade** [comment]
Having NixOS logo also would be good too.

https://nixos.org/

**Comment by keeferrourke** [comment]
@dyrnade can you post the output of `lsb_release -si` on NixOS?

**Comment by dyrnade** [comment]
You better go with this ID=nixos because NixOS kinda different :D

cemg@nixos ~> cat /etc/os-release 
NAME=NixOS
ID=nixos
VERSION="16.09.741.354fd37 (Flounder)"
VERSION_ID="16.09.741.354fd37"
PRETTY_NAME="NixOS 16.09.741.354fd37 (Flounder)"
HOME_URL="http://nixos.org/"

**Comment by keeferrourke** [comment]
@dyrnade check out commit 419e9bc, I've updated the `configure` script to support NixOS. NixOS distributor logo is located at `places/scalable/distributor-logo-nixos.svg`

**Comment by dyrnade** [comment]
@keeferrourke Thats cool.Thank you very much :D
