### ISSUE TITLE
[bug] Some icons with low resolution

### ISSUE THREAD

**Issue by daltones** [keeferrourke/la-capitaine-icon-theme#44]
I'm using Gnome 3.20 with default 1.0 scale factor. I noticed these icons with low resolutions:

When plugging a headphone:
![captura de tela de 2016-10-10 12-56-28](https://cloud.githubusercontent.com/assets/5603632/19242993/1614e280-8eec-11e6-9323-e93125163496.png)

And when pressing play/pause media key when it doesn't make sense:
![captura de tela de 2016-10-10 12-55-46](https://cloud.githubusercontent.com/assets/5603632/19243064/6bf602b0-8eec-11e6-8ead-49617bd31e01.png)

Note that other icons of media keys actions are okay:
![captura de tela de 2016-10-10 12-55-04](https://cloud.githubusercontent.com/assets/5603632/19243101/926f4a1e-8eec-11e6-8bd8-a8cb81994641.png) 
![captura de tela de 2016-10-10 12-55-32](https://cloud.githubusercontent.com/assets/5603632/19243112/9b2e22d8-8eec-11e6-914a-8673a24632b6.png)

Thanks!

**Comment by keeferrourke** [comment]
weird! they *should* scale properly, but I'll look into it. guess I'm adding these to the list of icon that need to be resized... thanks for the report.

**Comment by keeferrourke** [comment]
This *should* be fixed now! Sorry it took so long to deal with, it seems that GNOME symbolic icons are used *everywhere* and must be scalable to a huge range of sizes.

**Comment by daltones** [comment]
Yeah! I can confirm that it's fixed! 😃 

Thanks!
