### ISSUE TITLE
[Icon Request] Stacer

### ISSUE THREAD

**Issue by DMNerd** [keeferrourke/la-capitaine-icon-theme#440]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Stacer   | `stacer` | Linux System Optimizer and Monitoring | ![stacer](https://user-images.githubusercontent.com/7889445/53089403-c6a39600-350c-11e9-8b56-70acf23ce305.png) |

### Desktop file

```
# Paste your desktop file below.
# Do NOT include non-English translation strings.
[Desktop Entry]
Name=Stacer
Exec=stacer
Comment=Linux System Optimizer and Monitoring
Icon=stacer
Type=Application
Terminal=false
Encoding=UTF-8
Categories=Utility;
```

Edit:
[Link](https://github.com/oguzhaninan/Stacer) to the project's gitgub

**Comment by TN3rd** [comment]
I am no designer, but I tought something like this might suit this kind of icon style (sorry, my first time with inkscape). 
![stacer](https://user-images.githubusercontent.com/7889445/53286186-eb954480-376a-11e9-987b-25943e9ebf7b.png)

**Comment by TN3rd** [comment]
I am not designer, but I tought this could suit this kind of icon set (sorry, my first time with inkscape)
![stacer](https://user-images.githubusercontent.com/7889445/53286209-3616c100-376b-11e9-8155-1de44460c033.png)

**Comment by TN3rd** [comment]
![stacer](https://user-images.githubusercontent.com/7889445/53291943-83228380-37bb-11e9-93c8-9024369cbc50.png)
Ver 2.0
