### ISSUE TITLE
[Gnome Extension Support Request] Dynamic Battery

### ISSUE THREAD

**Issue by DMNerd** [keeferrourke/la-capitaine-icon-theme#442]
I don't think this request can be formulated in the default request template. I'd like to see support for [Dynamic Battery](https://extensions.gnome.org/extension/1213/dynamic-battery/) Gnome extension. It itself is supposed to have support for some Icon packs ([Info from their gitlab](https://gitlab.com/exalm/gnome-shell-extension-dynamic-battery/)), so it would definitely be possible as a general improvement. Thank you for your work!

**Comment by keeferrourke** [comment]
@TN3rd it looks like (according to the README of that project and a brief look at their sources) that the extension bundles the icons itself and does not allow standard theming of it. You'll need to open an issue on that project and request support for La Capitaine (not vice versa as done here).

> To request support of any other themes, open an issue here. The only condition is that it should be under a free license so I can modify and bundle the battery icons with the extension.

You can let `exalm` know that they're free to redistribute and bundle these icons under the terms of the GPLv3 and MIT licenses.

Cheers!
