### ISSUE TITLE
SVG recolouring

### ISSUE THREAD

**Issue by MarseilleDev** [keeferrourke/la-capitaine-icon-theme#46]
# How me make white icons in top-bar?
![whiteIcons](https://cloud.githubusercontent.com/assets/19198757/19410520/532183ae-92f7-11e6-84a6-d79acd902513.png)

**Comment by keeferrourke** [comment]
You will need to recolour them yourself. At the moment La-Capitaine does not support dark GTK themes. This is a planned improvement, but will take some time as I'm busy with midterms. See issue #4.

**Comment by Elbullazul** [comment]
sorry to get in this conversation, but it seems that by editing yourself the SVGs and replacing whatever icon color in them by 'bebebeff' it will recolor the SVG according to the fg color of the theme

just saying, someone told me that, but I've never tried yet

**Comment by keeferrourke** [comment]
@Elbullazul do you have a source on that? many of the symbolic icons in La Capitaine are already coloured as #bebebe will full opacity (ff). If that's the case, I may make it more of an issue to recolour all symbolic icons to that colour.

**Comment by Elbullazul** [comment]
@keeferrourke a long-time icon theme maintainer suggested me this solution when I ran into the same issue. Also, the original gnome theme has this fix to avoid bugs in shell (or gtk-derived desktops): [further details](https://askubuntu.com/questions/148955/why-do-the-gnome-symbolic-icons-appear-darker-in-a-running-application/154780)

this could also save you time from forking a new theme with light symbolic icons

**Comment by keeferrourke** [comment]
@Elbullazul thanks so much for the helpful response! this should help resolve issue #4 and improve compatibility with gtk themes in general :)

I'm going to reclose this issue, and open a new one that pertains only to recolouring symbolic and action icons.

**Comment by MarseilleDev** [comment]
@keeferrourke 

![dark](https://cloud.githubusercontent.com/assets/19198757/19649781/bbe8d3fa-9a0f-11e6-8094-81993bfeef7a.png)
![white](https://cloud.githubusercontent.com/assets/19198757/19649782/bbea7ba6-9a0f-11e6-90e9-b79905492ade.png)

Where are these white icons? How their turn on?

**Comment by Elbullazul** [comment]
oh oh, @MarseilleDev that's your GTK theme having problems, probably

which theme are you using?

**Comment by MarseilleDev** [comment]
@Elbullazul [Flatabulous](https://github.com/anmoljagetia/Flatabulous.git)

**Comment by Elbullazul** [comment]
gtk seems ok, it's a unity thing then

same thing should happen with other icon themes, right?

**Comment by MarseilleDev** [comment]
@Elbullazul No, for different icons all is good!

**Comment by Elbullazul** [comment]
then it's unity having problems...

**Comment by MarseilleDev** [comment]
@Elbullazul Hi! I'm updated Ubuntu to 16.10 but anyway I have it's problem with icons):
![Dark icons](https://cloud.githubusercontent.com/assets/19198757/19918870/dfb25d84-a0df-11e6-9854-a42e2c85f3ba.png)
![White icons](https://cloud.githubusercontent.com/assets/19198757/19918871/dfb3392a-a0df-11e6-85c7-dc00b33304c9.png)

**Comment by Elbullazul** [comment]
then it seems Unity washes colors to white on dash view.
