### ISSUE TITLE
gnome-control-center changed its icon name

### ISSUE THREAD

**Issue by genericusername3** [keeferrourke/la-capitaine-icon-theme#466]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Gnome Settings (gnome-control-center)    | `gnome-settings` / `org.gnome.Settings` now | - | 			   |

### Desktop file
`/usr/share/applications/gnome-control-center.desktop`
``` 
[Desktop Entry]
Name[en_GB]=Settings
Name=Settings
# Translators: Do NOT translate or transliterate this text (this is an icon file name)!
Icon[en_GB]=org.gnome.Settings
Icon=org.gnome.Settings
Exec=gnome-control-center
Terminal=false
Type=Application
StartupNotify=true
Categories=GNOME;GTK;System;
OnlyShowIn=GNOME;Unity;
X-GNOME-Bugzilla-Bugzilla=GNOME
X-GNOME-Bugzilla-Product=gnome-control-center
X-GNOME-Bugzilla-Component=shell
X-GNOME-Bugzilla-Version=3.32.0.1
# Translators: Search terms to find this application. Do NOT translate or localize the semicolons! The list MUST also end with a semicolon!
Keywords[en_GB]=Preferences;Settings;
Keywords=Preferences;Settings;
```

The icon name for gnome-control-center aka. Gnome Settings has recently changed to `org.gnome.Settings` on my distro (Manjaro Linux). Could you please add a soft link to `gnome-settings` or `preferences-system`? 
(Untill then, I'll just change the .desktop file every time gnome-control-center updates)

**Comment by zencubic** [comment]
@genericusername3 You probably got an older version. This is fixed in the master branch already

**Comment by genericusername3** [comment]
Oh ok nevermind then
