### ISSUE TITLE
[Request] Icon for Slingscold

### ISSUE THREAD

**Issue by btd1337** [keeferrourke/la-capitaine-icon-theme#47]
Icon for Slingscold is missing.

Slingscold is a free alternative to Launchpad to Mac OS.

Icon=/usr/share/icons/slingscold.png

![slingscold](https://cloud.githubusercontent.com/assets/11943860/19412496/23f48ea4-92ee-11e6-9b00-524e88a8e3f6.png)

**Comment by keeferrourke** [comment]
Alright, I added the slingscold icon under `apps/scalable/slingscold.svg` Note that if your desktop file actually specifies a .png, you'll need to edit the file to remove the .png extension.

I redesigned the Launcher icon as well, and symlinked this to slingscold. Update in commit e9e8af2

Preview:
![launcher svg](https://cloud.githubusercontent.com/assets/6888381/19438845/c4f1af1a-9449-11e6-9d2f-617db557c729.png)

**Comment by btd1337** [comment]
Cool!
