### ISSUE TITLE
Battery indicator not using correct icon (Ubuntu 19.04)

### ISSUE THREAD

**Issue by blumn2** [keeferrourke/la-capitaine-icon-theme#474]
I have noticed recently that the battery icon will not correctly reflect the current percentage of the battery. For example, when the battery is at 67%, it will show the battery as full. All of the icons are IN the icon folder that I downloaded, yet the battery indicator seems to only use the 100%, 80%, and 20% levels. I'm not sure if this is an icon-related issue, or if I'm barking up the wrong tree entirely.

Example below:
![image](https://user-images.githubusercontent.com/45048997/57336502-206f3180-70f4-11e9-971b-6caaafc1163f.png)

Thank you so much!

**Comment by keeferrourke** [comment]
Which desktop environment are you using?

**Comment by blumn2** [comment]
I am using GNOME 3.32

**Comment by keeferrourke** [comment]
Is this still an issue? I just pushed an update which fixes the battery icons on GNOME 3.34.

**Comment by blumn2** [comment]
No, this is no longer an issue! Thank you!
