### ISSUE TITLE
Do not use Plank icon for Latte-dock

### ISSUE THREAD

**Issue by trmdi** [keeferrourke/la-capitaine-icon-theme#483]
Currently, the icon for Latte-dock is just a symlink to the Plank icon:
`apps/scalable/latte-dock.svg -> plank.svg` (1)

![image](https://user-images.githubusercontent.com/11857205/59960142-caace800-94ed-11e9-8c37-3dbba2490137.png)

It doesn't look very good compared to the original one provided by Latte itself:
![image](https://user-images.githubusercontent.com/11857205/59960199-e1077380-94ee-11e9-833c-32dca33aece5.png)

And the style of that one doesn't look too different with the design of la-capitaine:
![image](https://user-images.githubusercontent.com/11857205/59960225-7440a900-94ef-11e9-9f8d-ccedf11cb7d9.png)

So I suggest to remove that symlink (1) to plank.

**Comment by keeferrourke** [comment]
Hm thanks for pointing this out! Definitely not on brand! Adding this to the TODO.
