### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by XEmpty** [keeferrourke/la-capitaine-icon-theme#484]
Hi , i just have a question about project its a dead? i see 11 month ago a milestone 7.x 
Any information about that?

**Comment by linusg** [comment]
@keeferrourke might just be busy (who isn't?), the project is definitely not _dead_:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/19366641/60086033-48613580-9732-11e9-947a-85271ab75465.png">

**Comment by keeferrourke** [comment]
Hi @XEmpty I'm not dead and neither is this project! As @linusg has shown, there have been a bunch of commits consistently over the last few months.

I don't work on this full time! See @cashapp for my full time work lol :)

Life is busy! I still have plans for this project (and also many others haha) and some super sweet additions are added all the time by cool people like @stefano-b and @zencubic!
