### ISSUE TITLE
Scaling the icons

### ISSUE THREAD

**Issue by radu-b** [keeferrourke/la-capitaine-icon-theme#487]
Is there a way to scale up the icons in GNOME? I've changed the font sizes to match my screen resolution, and I'm curious if there is a way (a system setting, or by editing the theme) to bring the icons to a matching size (1.5x).

I'm talking about the black icons in the screenshot below:

![Screenshot from 2019-07-24 20-19-01](https://user-images.githubusercontent.com/7292229/61877268-58b62d00-aef7-11e9-8f2a-26c522b44c28.png)

Thanks!

**Comment by keeferrourke** [comment]
Interesting! Check out [this file](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/index.theme) and bump the sizes of all the `$thing/symbolic` icons. I think that should do what you want :)

Sorry for the late reply!

**Comment by radu-b** [comment]
Thanks, I'll try and let you know.

**Comment by radu-b** [comment]
Yes, that did it! I had to set both the Size and MinSize under each symbolic category (I used size 24), and it looks great now.
