### ISSUE TITLE
[Request] Add Terminix icon

### ISSUE THREAD

**Issue by btd1337** [keeferrourke/la-capitaine-icon-theme#5]
Create a simbolic link for Terminix.

Use xterm.svg for this.

Green on black is nice :+1:

**Comment by keeferrourke** [comment]
@btd1337 Terminix is not packaged on either of the main distributions I use (Ubuntu and OpenSUSE), can you please provide me the name of the Terminix icon? You can find it in the .desktop file located in `/usr/share/applications` on a line that looks like this:
     
    Icon=xxxxxxx

I would assume I should just be linking `xterm.svg` to `terminix.svg` but sometimes applications have weird icon names...

**Comment by btd1337** [comment]
Icon=terminix

**Comment by keeferrourke** [comment]
Added in commit [2f2f9390](https://github.com/keeferrourke/la-capitaine-icon-theme/commit/2f29390)

apps/scalable/terminix.svg --> apps/scalable/xterm.svg
