### ISSUE TITLE
[Request] Restore previous Firefox icon

### ISSUE THREAD

**Issue by ctipper** [keeferrourke/la-capitaine-icon-theme#505]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Firefox    | `firefox.svg` | Application | 			   |

### Desktop file
Machine not available right now, sorry
```
# Paste your desktop file below.
# Do NOT include non-English translation strings.




```

The recent firefox icon update was a mistake in my opinion. The icon stares at me from my docking panel every day and it is an irregular size and an irregular shape. I had no issues with the previous one.

The one referenced in this closed issue looks nice
<https://github.com/keeferrourke/la-capitaine-icon-theme/issues/180>

**Comment by linusg** [comment]
Not sure if this would be the right thing to do, Firefox's logo change decision was made by Mozilla, not @keeferrourke - he just went ahead and changed it before they will in Firefox stable.

Maybe a possible solution would be to include the old logo as `firefox-alt` so people could go ahead and edit their `.desktop` files and use it...

**Comment by ctipper** [comment]
I assume you are referring to this announcement <https://blog.mozilla.org/opendesign/firefox-the-evolution-of-a-brand/>

Thing is, the new logo looks nothing like what has been announced and Mozilla haven't even started using the new design. So what's the problem?

**Comment by ctipper** [comment]
<https://design.firefox.com/photon/visuals/product-identity-assets.html>

**Comment by linusg** [comment]
That's a misunderstanding here - I'm not the owner of this repo, and I don't make any decisions about this. I'm just a guy with an opinion on your proposal, which I've now expressed - so I'll be quiet for the time being :wink:

**Comment by keeferrourke** [comment]
@ctipper: maintainer here!

There are a few applications for which I keep alternative versions for, but it's not exactly desirable imo. Now the fact is that the Firefox icon has seen a lot of changes over the years, and @linusg is correct in that I just updated the icon based on what is already available in nightly. I did the *same thing* when the icon was updated for Quantum (the one that you want me to restore).

Other icon themes have followed my example, Papirus [did the same thing](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/64c1a0af80f357b9a5c2466f348cbc953a03b152) one day after I updated La Capitaine, and they do not maintain an alternative version.

As a counter-point, is there anything that I could do to *update* the new icon to better suit your tastes? If there is really nothing, I can restore the quantum icon. Just bear in mind that it won't be a reversion.

**Comment by ctipper** [comment]
I like the idea of having the quantum icon as an alternative. I now know that the new icon is going to be released in Firefox 70 so I’m on a losing wicket as far as that is concerned, but really the negative space is a mistake I don’t know what they were thinking. The comments the announcement were about 50% negative too but I’m guessing they just plough on there’s little I can see will change their minds. I could say more but my wish is to just have a copy of the old icon available I don’t see you need to revert any changes.

--
Sent with Spark

**Comment by stefano-b** [comment]
I think that when dealing with icons for well-known applications and that have a distinctive and recognizable look, the brand identity should be respected and, albeit with some minor style modifications to better fit in the icon theme, the icon should be as similar as the original as possible.

I think that this is important for two reasons: first, like I said, to respect a brand identity (often brands also publish brand guidelines that details how logos, icons, colors, etc. should be used, usually with examples of do's and don't's). Second, from an user point of view, to keep visual consistence to what they are already used to see.

This particular case of Firefox is not a arbitrary choice of this icon theme, but a full rebrand from Mozilla. Keeping this theme with an outdated icon while the original and other icon packs have the new updated one would not be the ideal solution, IMHO.

As a personal opinion, I've nothing against keeping the old ones as alternatives anyway, if Keefer feels like it.

**Comment by ctipper** [comment]
Hadn't expected the amount of pushback I received, so closing the issue. The introduction of the new Firefox branding two months ahead of schedule was a surprise now it is available across all platforms I am closing this issue. If I had one suggestion it would be to adhere more closely to the official design, which uses more gradients and colours.

**Comment by keeferrourke** [comment]
Hey @ctipper I don't mean to ignore this issue, I'm just busy with midterms right now. I will look into making the FF60 logo available again, and update the icon now that Mozilla has release FF70. It will just a bit of time from me, which I'm having difficulty finding at the moment.

**Comment by ctipper** [comment]
I think you can close this issue now it's been over a year and I've got used to it I hadn't been following mozilla design discussions and it was a surprise when they changed the logo. But your theme is fine, makes my desktop look nice and I wish it was in the core distributions.
