### ISSUE TITLE
Confusing display orientaion icons in KDE Display confguration page

### ISSUE THREAD

**Issue by sasannnn** [keeferrourke/la-capitaine-icon-theme#509]
With La Capitaine enabled, orientation icons on KDE Display configuration page are confusing since "upside down" and "90° Counterclockwise" don't use distinct icons.
Here who it looks like with La Capitaine:
![Screenshot_20191027_161646](https://user-images.githubusercontent.com/57077450/67643475-35739300-f8d5-11e9-9c12-49ba61b44866.png)
With breeze dark:
![Screenshot_20191027_161544](https://user-images.githubusercontent.com/57077450/67643489-52a86180-f8d5-11e9-8968-3cf937b8696b.png)

**Comment by keeferrourke** [comment]
OOF. I agree this is a major issue. Do you happen to know the name of that icon? Is it `view-preview` or something else?

**Comment by stefano-b** [comment]
This could be probably be solved with a little edit of the "eye" icon, like this:

![Screenshot_20200717_143404](https://user-images.githubusercontent.com/36746429/87786783-dc6cd600-c83a-11ea-9908-8f3bb148fea8.png)

I've already corrected this in my personal setup, I can do a PR for this but it is probably better to solve the build error from #555

**Comment by marchingon12** [comment]
@keeferrourke I may be wrong but I searched a bit and found this (so far...)

![Screenshot_20201019_154852](https://user-images.githubusercontent.com/41235480/96459572-c98ae880-1211-11eb-9251-350010220e14.png)

`x-shape-image` could be the one we're trying to find?

**Comment by keeferrourke** [comment]
@marchingon12 does #566 not fix the issue?

**Comment by marchingon12** [comment]
Oh no, I think I didn't understand it correctly at first and wrote without thinking through at some point. Forgive me for adding unnecessary confusions, #566 does indeed fix the issue until you come up with a better one :D

**Comment by keeferrourke** [comment]
I'll close this, I'm happy with Stefano's fix :)
