### ISSUE TITLE
Icon for Screenshot

### ISSUE THREAD

**Issue by pranavkamath** [keeferrourke/la-capitaine-icon-theme#51]
This is a request for creating an icon for Screenshot.
Thank you.

**Comment by keeferrourke** [comment]
This is an invalid request. "Screenshot" is about as ambiguous of an application name as it gets, you did not provide an icon design reference, or the application's .desktop file.

I can't do anything to help you, unless you help me.

**Comment by keeferrourke** [comment]
Closing because this request is invalid, and it has not been updated.
