### ISSUE TITLE
KDE dark icons

### ISSUE THREAD

**Issue by arthurflor23** [keeferrourke/la-capitaine-icon-theme#517]
Hi!
I use Arch with KDE dark theme mode and installed from AUR repository (git package), some icons appear in the 'light way' when click right button in some menus/widgets:

![image](https://user-images.githubusercontent.com/11759042/70402211-646f3f80-1a11-11ea-87ef-301429766179.png)

![image](https://user-images.githubusercontent.com/11759042/70402217-6afdb700-1a11-11ea-8a01-e74781806a6b.png)

I also cleaned the cache, but nothing changed.

Anyway, great icon theme package!
Thanks a lot

**Comment by arthurflor23** [comment]
Just reboot the system.. oh God

**Comment by keeferrourke** [comment]
Hah glad a reboot fixed it for ya ;)
