### ISSUE TITLE
Bitwig Studio icon

### ISSUE THREAD

**Issue by ckam03** [keeferrourke/la-capitaine-icon-theme#53]
Bitwig.com
![bitwig](https://cloud.githubusercontent.com/assets/23270157/20205846/6018d4fc-a799-11e6-9b46-4807a72fd19f.png)

**Comment by ckam03** [comment]
https://www.bitwig.com/en/bitwig-studio.html

**Comment by keeferrourke** [comment]
@ckam03 you need to submit the name of the icon as well. See the README, if you want an icon themed then please don't make my life difficult :)

**Comment by ckam03** [comment]
I did didn't I? Bitwig Studio.

**Comment by keeferrourke** [comment]
No, you did not. It's great to know what the application is called, but I need to know the file name for the icon as well.

You can do this by running 
```
cat /usr/share/applications/<application name>.desktop | grep "Icon="
```

**Comment by keeferrourke** [comment]
I've updated the README to be more clear on how to submit icon requests, see the suggested format.

**Comment by keeferrourke** [comment]
Closing this because it is an invalid and inactive request.
