### ISSUE TITLE
[Request] Gnome Extensions

### ISSUE THREAD

**Issue by zencubic** [keeferrourke/la-capitaine-icon-theme#530]
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| Gnome Extensions    | `org.gnome.Extensions` | Application | ![extensions](https://user-images.githubusercontent.com/27775731/76309651-7c36b800-62cd-11ea-8eff-54f5c2a49367.png)|

### Desktop file

```
[Desktop Entry]
Type=Application
Name=Extensions
Icon=org.gnome.Extensions
Comment=Configure GNOME Shell Extensions
Exec=/usr/bin/gnome-shell-extension-prefs %u
Categories=GNOME;GTK;
OnlyShowIn=GNOME;

```

**Comment by keeferrourke** [comment]
Nice! Is this new?

**Comment by zencubic** [comment]
Just got the application on Arch with Gnome 3.36 included by default
