### ISSUE TITLE
Support for Recent Files in cinnamon menu

### ISSUE THREAD

**Issue by s1-ranjan** [keeferrourke/la-capitaine-icon-theme#547]
I am missing Recent files icons in the cinnamon menu. Please have a look in the image below, 
![Recent-Files](https://user-images.githubusercontent.com/20767253/76937426-cd245d00-691a-11ea-93ba-ae4d40c7d996.png)
I tried to figure out the proper folder location and the file name but I don't find any working solution, so I hope somebody in the community can fix this broken link in order to render the proper icon in cinnamon menu.

**Comment by keeferrourke** [comment]
To be clear, there is supposed to be an icon to the left of the text `Recent Files`, but it is missing?

**Comment by s1-ranjan** [comment]
@keeferrourke , **YES** you are correct there should have been icon beside Recent Files.

**Comment by s1-ranjan** [comment]
This bug can be fixed by creating a link called folder-recent.svg to folder-temp.svg in the places/scalable folder location.

**Comment by keeferrourke** [comment]
Should be fixed now! Sorry for taking _forever_ to do this.
