### ISSUE TITLE
problem with build: 'error: unable to create symlink'

### ISSUE THREAD

**Issue by frosth555** [keeferrourke/la-capitaine-icon-theme#555]
Hi, I have problem build it after last update. 
I've got:

> LANG=C git clone https://github.com/keeferrourke/la-capitaine-icon-theme.git
> Cloning into 'la-capitaine-icon-theme'...
> remote: Enumerating objects: 74, done.
> remote: Counting objects: 100% (74/74), done.
> remote: Compressing objects: 100% (68/68), done.
> remote: Total 18647 (delta 30), reused 10 (delta 5), pack-reused 18573
> Receiving objects: 100% (18647/18647), 54.06 MiB | 1.02 MiB/s, done.
> Resolving deltas: 100% (11854/11854), done.
> error: unable to create symlink apps/scalable/applications-system.svg: File name too long
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry with 'git restore --source=HEAD :/'

first bad commit:
[https://github.com/keeferrourke/la-capitaine-icon-theme/commit/5457889892a5568b9862d242329b11245fc0853c](url)

btw, thx for your work sir

**Comment by keeferrourke** [comment]
TODO:
 -[ ] revert PR https://github.com/keeferrourke/la-capitaine-icon-theme/pull/529/files

**Comment by stefano-b** [comment]
Hi @keeferrourke, there are a couple small PR's that I plan to do, but I think that it would be better to wait until this problem has been solved. What do you think about it?

**Comment by keeferrourke** [comment]
Should be fixed now. Sorry for the long delay with addressing this!
