### ISSUE TITLE
GParted icon + Donation

### ISSUE THREAD

**Issue by kunamashina** [keeferrourke/la-capitaine-icon-theme#56]
Could you please create an icon for the "gparted" app ?

Willing to donate some cash to you so you can work more on this icon set, please contact me @ ismuskuna@gmail.com to follow through

I have some more requests afterwards

**Comment by auroszx** [comment]
Not the author, but... Doesn't `gparted` already have an icon? I see one at `/usr/share/icons/la-capitaine-icon-theme/apps/scalable/gparted.svg`. Or do you want a more specific one?

**Comment by kunamashina** [comment]
http://imgur.com/3qn1ANu

gparted.svg shares it's icon with the rest of disk utilities found on my pc

I wanted a more specific one :)

**Comment by keeferrourke** [comment]
@kunamashina I got your emails and I'll work on differentiating gparted from other disk utilities! watch your inbox and keep an eye out for a commit coming soon!

**Comment by keeferrourke** [comment]
updated in https://github.com/keeferrourke/la-capitaine-icon-theme/commit/38fa0b5.

@kunamashina please open another issue, or email me for any additional requests
