### ISSUE TITLE
"distributor-logo" icons are spread over two directories

### ISSUE THREAD

**Issue by stefanobartoletti** [keeferrourke/la-capitaine-icon-theme#570]
As the title says, `distributor-logo-*.svg` icons are currently placed in two directories, in `apps/scalable` and in `places/scalable`; some are duplicates, some are present in only one dir.

I don't know if this is wanted or if it is a problem, but considering that the plain `distributor-logo.svg` symlink is present on `places/scalable`, it seems that this is the proper place.

Is this something to fix?

**Comment by keeferrourke** [comment]
Thanks for noticing this! They should probably all be under `places`. I'd accept a PR to fix this :)
