### ISSUE TITLE
[Request] DraftSight, Signal and Wunderlist icons

### ISSUE THREAD

**Issue by cemetary** [keeferrourke/la-capitaine-icon-theme#58]
Amazing icons theme!

Just wondering if you can add the following icons.

**Application: DraftSight**
Icon name: dassault-systemes.draftsight
Context: CAD drawing app
Icon reference: 
![captura de pantalla de 2016-11-21 20-33-58](https://cloud.githubusercontent.com/assets/10538213/20508949/cb19eacc-b02a-11e6-9977-6b301a1d3fc4.png)

**dassault-systemes_draftsight.desktop content**
```
[Desktop Entry]
Name=DraftSight
Comment=Editing CAD images
GenericName=DraftSight
Exec="/opt/dassault-systemes/DraftSight/Linux/DraftSight"
Path=/opt/dassault-systemes/DraftSight/Linux
Type=Application
Terminal=false
Icon=dassault-systemes.draftsight
MimeType=image/vnd.dwg;image/vnd.dwt;image/vnd.dxf;application-vnd.dassault-systemes.draftsight-dwg;application-vnd.dassault-systemes.draftsight-dwt;application-vnd.dassault-systemes.draftsight-dxf
Categories=Application;Graphics;2DGraphics;RasterGraphics;
```

**Application: Signal Private Messenger**
Icon name: Signal Private Messenger
Context: Google Chrome App for messaging
Icon reference: 
![captura de pantalla de 2016-11-21 20-35-46](https://cloud.githubusercontent.com/assets/10538213/20508990/0bea4952-b02b-11e6-984b-7fd1d1c52359.png)

**chrome-bikioccmkafdpakkkcpdbppfkghcmihk-Default.desktop content**
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Signal Private Messenger
Exec=/opt/google/chrome-unstable/google-chrome-unstable --user-data-dir=/home/cemetary/.config/google-chrome-unstable --profile-directory=Default --app-id=bikioccmkafdpakkkcpdbppfkghcmihk
Icon=chrome-bikioccmkafdpakkkcpdbppfkghcmihk-Default
StartupWMClass=crx_bikioccmkafdpakkkcpdbppfkghcmihk
```

**Application: Wunderlist for Chrome**
Icon name: Wunderlist for Chrome
Context: Google Chrome App for tasks management.
Icon reference: 
![captura de pantalla de 2016-11-21 20-36-53](https://cloud.githubusercontent.com/assets/10538213/20509035/52d01356-b02b-11e6-9bd1-f67b69a5f64e.png)

**chrome-ojcflmmmcfpacggndoaaflkmcoblhnbh-Default.desktop content**
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=Wunderlist for Chrome
Exec=/opt/google/chrome-unstable/google-chrome-unstable --user-data-dir=/home/cemetary/.config/google-chrome-unstable --profile-directory=Default --app-id=ojcflmmmcfpacggndoaaflkmcoblhnbh
Icon=chrome-ojcflmmmcfpacggndoaaflkmcoblhnbh-Default
StartupWMClass=crx_ojcflmmmcfpacggndoaaflkmcoblhnbh
```

**Application: Nomacs**
Icon name: nomacs
Context: Image Viewer.
Icon reference: 
![captura de pantalla de 2016-11-21 20-34-42](https://cloud.githubusercontent.com/assets/10538213/20509059/92f1fa26-b02b-11e6-9aed-f31363b21022.png)

**nomacs.desktop content**
```
[Desktop Entry]
Name=Nomacs
GenericName=Image Viewer
Comment=An image viewer
Exec=nomacs %F
Terminal=false
Icon=nomacs
Type=Application
Categories=Graphics;RasterGraphics;Viewer;2DGraphics;
MimeType=image/gif;image/jpeg;image/png;image/bmp;image/x-eps;image/x-ico;image/x-portable-bitmap;image/x-portable-graymap;image/x-portable-pixmap;image/x-xbitmap;image/x-xpixmap;
GenericName[de]=Bildbetrachter
Comment[de]=Ressourcenschonender, plattformübergreifend verwendbarer Bildbetrachter mit Unterstützung für verschiedenste Formate
Name[pt]=Nomacs
GenericName[pt]=Visualizador de imagens
Comment[pt]=Um visualizador de imagens desenvolvido em Qt
```

I hope I have made the request correctly.
Cheers, and thank you. :-)

**Comment by keeferrourke** [comment]
Cheers mate! This is a perfect example of the request format I'm looking for! Thanks for making my life easy :grin:

I'm going to link to this request in `README.md` as an example for future requests.

I'll start working on getting these icons themed, just have a little patience as exams seem to be never-ending/
