### ISSUE TITLE
[Request] Missing redshift status and firewalld applet icons

### ISSUE THREAD

**Issue by Fenisu** [keeferrourke/la-capitaine-icon-theme#6]
Redshift app has an icon but the taskbar icon isn't there. It uses the default ugly one.
The icons are:
`redshift-status-on.svg`
`redshift-status-off.svg`
The same happens with the firewalld-applet application. It uses the default firewall icon for the taskbar.
The icons are:
`firewall-applet.png`
`firewall-applet-error.png`

**Comment by keeferrourke** [comment]
@Fenisu can you provide references for what these icons should look like?

**Comment by Fenisu** [comment]
Sorry for such a bad report.
The firewalld applet icons are those inside this directory:
https://github.com/t-woerner/firewalld/tree/qt-gui/src/icons/scalable/apps

Right now I've manually set firewall-applet.svg as the firewall-config.svg found in the package, so it looks as the firewall icon when yo usearch for firewall in Activities in Gnome3, but the firewall error should be like the same icon but in red.

The redshift icon as ON (redshift-status-on.svg) can be the same redshift.svg icon, but when redshift is off, it should be the same icon but in blue.

**Comment by keeferrourke** [comment]
Added requested redshift and firewall-applet icons, this issue should be fixed in commit [590dbc9](https://github.com/keeferrourke/la-capitaine-icon-theme/commit/590dbc9).

@Fenisu You should pull the latest commits and let me know if this is fine.

**Comment by keeferrourke** [comment]
I've tested both on my local Ubuntu installation, so I'm going to close this. If Redshift or Firewall-applet have issues on other systems, we can reopen the issue.
