### ISSUE TITLE
[Request]  .spec file icon (mimetype)

### ISSUE THREAD

**Issue by jatin-cbs** [keeferrourke/la-capitaine-icon-theme#602]
Some examples of spec file icons.

![Screenshot from 2021-04-17 10-53-09](https://user-images.githubusercontent.com/40650341/115102865-6208e800-9f6b-11eb-80c7-ba5b0fc680f7.png)

![Screenshot from 2021-04-17 10-53-38](https://user-images.githubusercontent.com/40650341/115102906-92e91d00-9f6b-11eb-88c0-0c08622dc922.png)

Spec files is a text file that the rpmbuild utility uses to actually build an RPM. It contains information like dependencies, package name etc.

**Comment by keeferrourke** [comment]
Hey @jatin-cbs what is the name of the spec file mimetype? This will help me name the new icon file correctly.

**Comment by jatin-cbs** [comment]
text-x-rpm-spec.svg
