### ISSUE TITLE
Bugzilla:1950614 for Fedora packages

### ISSUE THREAD

**Issue by jatin-cbs** [keeferrourke/la-capitaine-icon-theme#603]
https://bugzilla.redhat.com/show_bug.cgi?id=1950614

The issue is, Redhat configuration is currently the default in the icon theme. We can't run configuration file in mock. And manually running configuration and using it as source will cause this to be done every single time for all supported Fedora releases. 

Possible solutions - 
1. Making the script more Mock friendly.
2. Making Fedora configuration the default.
3. Having different branch for Fedora configuration which we can use as the source in package build.

**Comment by keeferrourke** [comment]
Hey @jatin-cbs I read through the linked bugzilla issue, but I'm not sure what Mock is, or how you would want me to make the configuration script "more friendly" to that tool. Can you please advise?

(Sorry for the delayed reply, I'm just finishing up exams for my final semester of school.)

**Comment by tim77** [comment]
Mock it is a systemd-nspawn container for building software on Fedora/RHEL/CentOS.

- https://github.com/rpm-software-management/mock/wiki
- https://fedoraproject.org/wiki/Using_Mock_to_test_package_builds

**Comment by jatin-cbs** [comment]
@keeferrourke I personally think rpm has its own logo as artem pointed out on the bugzilla. 

Example of such icons - 

![Screenshot from 2021-04-23 22-54-37](https://user-images.githubusercontent.com/40650341/115908226-82fb9c80-a487-11eb-858a-4f279a655c09.png)
![Screenshot from 2021-04-23 22-57-55](https://user-images.githubusercontent.com/40650341/115908243-8b53d780-a487-11eb-97bd-91e21c7d65c8.png)

It refers to RPM meters in cars. It will eliminate the need of different fedora red hat configuration. Also it will be a standard rpm icon in the style of la-capitaine mimetypes. I don't think there is any other configuration differences between the two distros for the icon theme.

**Comment by keeferrourke** [comment]
Ok so @jatin-cbs what exactly is the issue here?

Is it that you want me to change the configuration script (if so, in what way?), or is it that my mimetypes should be using a different (default but configurable? non-configurable?) icon for RPMs?

**Comment by keeferrourke** [comment]
Follow-up question: Where are these example mimetype icons from? Are they displaying an official logo, or is this artistic license?

At least according to Wikipedia / rpm.org, [this](https://upload.wikimedia.org/wikipedia/commons/0/00/RPM_Logo.svg) appears to be the official logo for the package manager.

**Comment by jatin-cbs** [comment]
The issue that there is different configuration for fedora and redhat, and configuration script won't be able to run in mock as stated. I can ask artem for configuration file changes. However we think that its more practical to simply change the .rpm mimetype logo to something more standard rather than fedora / redhat logos. 

These icons are from Qogir and white sur theme respectively. they are artistic not official logo but inspired from the standard official rpm logo as you stated which resembles a rpm meter.

**Comment by keeferrourke** [comment]
Okay thanks. I'm hesitant to remove the customization options for these mimetypes, but I'd be happy to add a different default RPM mimetype icon that closely resembles the official RPM logo, then still allow for the configuration script to overwrite this with distro-specific icons.

@jatin-cbs I'll link this issue in a PR later today, and tag you for review to make sure it's an ok solution for the bugzilla bug.

**Comment by jatin-cbs** [comment]
@keeferrourke Distro logos are creative way and some people do like it.  

So what i recommend is that by default having a new standard rpm mimetype icon. 
However if someone wants to run a configure script he can then be able to integrate it with his distro, Fedora/ Redhat or SUSE.

**Comment by jatin-cbs** [comment]
Currently 

`rpm.svg`  and  `application-x-rpm-redhat.svg`

are the same icon which makes redhat the default icon. Just change rpm.svg to a newer standard icon :)

**Comment by keeferrourke** [comment]
#605 Should address the immediate issue of RedHat branding showing up in Fedora. I'm still unsure _why_ the configure script isn't compatible with the Mock tool though, and how this causes possible packaging issues.

I'd like to make this easy to package, so @jatin-cbs @tim77 let's talk about possible changes to the configuration script in a new issue. Feel free to open a new bug at your leisure.

All the best!

**Comment by jatin-cbs** [comment]
Its settled and i don't think any changes are necessary. 
Everything that can be done in mock can be done without mock. Mock runs rpmbuild in an isolated environment consisting of a minimal set of packages. Those package doesn't include what it required to see the distribution logo. If artem run it on his own system it will build the package without any issue. Its nothing wrong about the config script. See Mock as just a fedora container with very minimal packages or chroot which may not satisfy everything :)

**Comment by tim77** [comment]
I hope i fixed or at least improved current build in Fedora but need to test ([f34 only](https://bodhi.fedoraproject.org/updates/FEDORA-2021-a464f0e896) for now). At least distro vendor should configured correctly.

This is partial fix for RH#1950614 since we wait for https://github.com/keeferrourke/la-capitaine-icon-theme/pull/605 merged.

**Comment by keeferrourke** [comment]
Alright #605 is merged to master! Thanks all!

**Comment by keeferrourke** [comment]
@tim77 FYI, I just cut a new release (first time in >2 years :flushed:)

**Comment by tim77** [comment]
> @tim77 FYI, I just cut a new release (first time in >2 years flushed)

Great! :+1: I would like if we switch to releases instead of git snapshots TBH. Not a big issue, but this more practical.
