### ISSUE TITLE
Accessibilty

### ISSUE THREAD

**Issue by GiBg1aN** [keeferrourke/la-capitaine-icon-theme#61]
Accessibility Icon on Gnome 3 bar (3.22) gets replaced by a white square.

**Comment by keeferrourke** [comment]
I need (a) a screenshot to illustrate this issue, and (b) if possible, the name of the icon that is affected.

In addition, are you running the latest from git, or one of the release tarballs?

**Comment by GiBg1aN** [comment]
I'm running release tarballs version, anyway, i see that you the icon i need exists, you put it in control panel, its called "access.svg". The problem is that when i enable some accessibility options the icon should spawn in the "status bar"(that one with battery and wifi icons), and it spawn as a white square, I'll attach screenshots ASAP. Ty for answering.

**Comment by GiBg1aN** [comment]
![after](https://cloud.githubusercontent.com/assets/5871979/20786605/50144686-b7a7-11e6-8d26-3566db905dfc.png)
![before](https://cloud.githubusercontent.com/assets/5871979/20786606/5018a67c-b7a7-11e6-9719-8e33fc62be39.png)

**Comment by keeferrourke** [comment]
@GiBg1aN I can't seem to find this icon anywhere >.< there is `apps/scalable/access.svg` but this is not the correct context for the status bar. Removing it also doesn't seem to cause the square to fall back to the default gnome icon.

@DarkknightAK do you have any insight?

**Comment by GiBg1aN** [comment]
In my gnome and Adwaita dirs there is `apps/scalable/preferences-desktop-accessibility-symbolic.svg` could it be what we are looking for?

**Comment by keeferrourke** [comment]
@GiBg1aN that's what I would think, but this image is already located at `apps/symbolic/preferences-desktop-accessibility-symbolic.svg`. 

![preferences-desktop-accessibility-symbolic](https://cloud.githubusercontent.com/assets/6888381/20957013/542a97fc-bc1b-11e6-8f9e-e6e898904150.png)

I'll mess around with it and hopefully have a fix up soon. I'm in the middle of final exams so working on this isn't top priority at the moment.

**Comment by GiBg1aN** [comment]
NP man, good luck! If i find a solution I'll let you know!

**Comment by keeferrourke** [comment]
Fixed the image! The accessibility menu should display properly now! :grin:

**Comment by GiBg1aN** [comment]
Good job, TY!
