### ISSUE TITLE
Dark Icons in KDE Plasma 5.22

### ISSUE THREAD

**Issue by Dony93** [keeferrourke/la-capitaine-icon-theme#612]
Hi, i am having problems with icons on dark themes, application icons are ok but MIME-type icons are all black. I will put some example screens.
![2-06-2021_10-58_1](https://user-images.githubusercontent.com/86654819/123769215-57eb5a00-d8c9-11eb-9b43-9488920eacbd.png)
![2-06-2021_10-57](https://user-images.githubusercontent.com/86654819/123769218-591c8700-d8c9-11eb-8f3f-c012ff842e37.png)

I did run the ./configure script and that is the output:
Could not determine distribution logo.
Use distributor logo from desktop environment? [y/N] y
Updated distributor logo.
Updated package archive icons.
Updated mimetype icons.

Not sure if i did right but anyway nothing changed still all black. 
Tried also to re-apply the pack and still same.

NOTE: I am using default Dark Breeze theme with a custom set of color i did myself.

**Comment by keeferrourke** [comment]
what version are you using? the latest version on master should not have this issue, unless there has been a major regression recently.

**Comment by Dony93** [comment]
Hi, sorry for the delay in replying to you. I am using the latest version of the icon pack v0.6.2

**Comment by keeferrourke** [comment]
@Dony93 please try cloning from this github repo and let me know if this is still an issue. I've been bad at cutting regular releases for [OpenDesktop](https://www.opendesktop.org/).

**Comment by Dony93** [comment]
That Worked, thank you! Apparently i guess downloading it from the store wasnt updated. I also had a different output this time on the configure file.
