### ISSUE TITLE
Shadows go out of icons

### ISSUE THREAD

**Issue by alexl-kde** [keeferrourke/la-capitaine-icon-theme#62]
![image](https://cloud.githubusercontent.com/assets/22029700/20768124/023cdfaa-b73d-11e6-8e35-b56e3815ffc1.png)

**Comment by keeferrourke** [comment]
I'm going to need more information than that. What desktop environment are you using? did you clone directly from master?

These shadows should be clipped to the shape of the icon, and render appropriately on GNOME 3.20.

**Comment by keeferrourke** [comment]
@alexl-kde can you pull the latest from master and let me know if the shadowing issue is gone as of 408def7 ?

I was "clipping" the shadows with another object before, but I've now converted the shadows to fixed paths. They should not render outside the icon anymore.

**Comment by alexl-kde** [comment]
As expected the shadow are fixed when converted to path. There are just two SVG renderers, the GNOME one (rsvg) and the Qt one, that doesn't support advanced SVG features like mask, blur and other filters. So it doesn't depend by the DE, everything uses Qt (Plasma, Lxqt and all the Qt apps) are affected ;-)
I checked Chrom* icons but the bug report is intended for all icons with shadow, you know it, do you?

**Comment by keeferrourke** [comment]
it's understood that all icons with clipped shadows will be affected by this issue. I'll leave it open until all are fixed. It's going to be a while before I can clean this up completely however.

**Comment by keeferrourke** [comment]
Should be fixed now for all icons that use shadowing!
