### ISSUE TITLE
Nautilus Folder icon problem - Gnome 3 (Fedora 25) 

### ISSUE THREAD

**Issue by KarBoraN** [keeferrourke/la-capitaine-icon-theme#63]
Nautilus folder icon problem.
For solution.
```sh
cd Sierra/apps/scalable
ln -s file-manager.svg org.gnome.Nautilus.svg
```

Thanks for icon theme . Thats very nice !

**Comment by keeferrourke** [comment]
@KarBoraN the `apps/scalable/org.gnome.Nautilus.svg` already exists in La Capitaine as of https://github.com/keeferrourke/la-capitaine-icon-theme/commit/85fd0256fe2b27e5972c6098ba70167285a0a882 back in October.

**Comment by KarBoraN** [comment]
Ohh ok 👍 . when you should update download link on gnome-look.org.
Thanks.

**Comment by keeferrourke** [comment]
Hmm... v0.3.1 and onward should have the fix. I don't recommend downloading old versions, but because this theme is still evolving I leave old versions kicking around for reference. Perhaps I'll clarify that only new releases are supported on gnome-look.org's product page.

Cheers.
