### ISSUE TITLE
White icons.

### ISSUE THREAD

**Issue by MarseilleDev** [keeferrourke/la-capitaine-icon-theme#65]
# Where is icons for dark themes?😩

![Dark_theme](https://cloud.githubusercontent.com/assets/19198757/21086866/8a1a9ca8-c031-11e6-8be2-1180426cc043.png)

**Comment by keeferrourke** [comment]
See issue #4, a dark version has been requested several times and it is the longest standing issue, however I just don't have the time to make one at the moment.

I'm in school right now, and redoing all of these icons would be a huge time-sink that I can't current afford. Bear with me, there will be one *eventually*.
