### ISSUE TITLE
[Request] Budgie support

### ISSUE THREAD

**Issue by JoshStrobl** [keeferrourke/la-capitaine-icon-theme#67]
Support for the distro-agnostic Budgie desktop environment would be appreciated. The Budgie logo, which is downloadable under the Assets section of Budgie on the [Solus Branding Guidelines](https://solus-project.com/branding-guidelines/) page, is licensed as CC-BY-SA-4.0.

Budgie support will likely involve modification of `configure`. We report `XDG_CURRENT_DESKTOP` as `Budgie:GNOME`.

**Comment by keeferrourke** [comment]
commits b3294a9d5d3af4af982f4183d534f9ea24fb6131 and 73a14a79eb9c1f28054e95294f19c044852f74fc fix some minor aesthetic issues with Budgie, namely the "start-here" icon in the panel is now a generic applications icon, and icons in titlebars are consistently the correct size now.

**Comment by keeferrourke** [comment]
To do:

- [ ] add `distributor-logo-budgie.svg`
- [ ] add alternative mime type for *.desktop files
- [ ] update `configure`

**Comment by keeferrourke** [comment]
@JoshStrobl here's a preview of changes!
![budgie](https://cloud.githubusercontent.com/assets/6888381/21468811/92fa2fa4-c9f6-11e6-9366-9a8702a3895c.png)
`distributor-logo-budgie`

**Comment by keeferrourke** [comment]
updated the configuration script in commit 54e980f, La Capitaine should now fully support the Budgie desktop environment!
