### ISSUE TITLE
[Request] Status icons for Redshift & ClipIt

### ISSUE THREAD

**Issue by Sadi58** [keeferrourke/la-capitaine-icon-theme#68]
I've found the following 3 icons missing from my Unity top panel (Ubuntu 16.10)

Application: _Redshift_
Icon names: _redshift-status-off.svg_ & _redshift-status-of.svg_
Context: _status_
Icons proposed: [redshift-status-off+on.zip](https://github.com/keeferrourke/la-capitaine-icon-theme/files/673252/redshift-status-off.on.zip)

Application: _ClipIt_
Icon name: _clipit-trayicon.svg_
Context: _status_
Icon proposed: [clipit-trayicon.svg.zip](https://github.com/keeferrourke/la-capitaine-icon-theme/files/673254/clipit-trayicon.svg.zip)

I hope this slight diversion from the expected format is also acceptable ;-)

**Comment by keeferrourke** [comment]
This format is fine :)

Unfortunately I probably won't get around to fixing this until the new year, but feel free to ping me if you think I forgot about it :P

**Comment by keeferrourke** [comment]
I took your suggestions to heart, but used modifications of icons from [the Material Design Icons](https://github.com/Templarian/MaterialDesign) project instead of the ones you attached.
