### ISSUE TITLE
[Request] Mark All Upgrades toolbar icon for Synaptic Package Manager

### ISSUE THREAD

**Issue by Sadi58** [keeferrourke/la-capitaine-icon-theme#69]
I think a symbolic link named **system-upgrade** to the icon **go-up** might suffice to complete the monochrome toolbar icons in Synaptic Package Manager.

Application: _Synaptic Package Manager_
Icon name: _system-upgrade_
Context: _action_
Icon reference: symlink to _go-up.svg_

**Comment by keeferrourke** [comment]
should be fixed now :) see commit 6cc3200
