### ISSUE TITLE
Monochrome panel icons Ubuntu

### ISSUE THREAD

**Issue by PaulMarco** [keeferrourke/la-capitaine-icon-theme#70]
The icons on the top panel of ubuntu are too dark, it is difficult to see. Please, to change all the icons of the panel to monochrome icons.
![la-capitaine-icon-ubuntu](https://cloud.githubusercontent.com/assets/16564571/21505103/5863ac1a-cc32-11e6-8c3e-de33884a5202.jpg)

**Comment by keeferrourke** [comment]
This is a probably a duplicate of issue #4.

Unfortunately creating another version of the icon theme for dark gtk themes/panels is a huge time commitment I can't make at this time.

**Comment by Elbullazul** [comment]
@keeferrourke you could use something like imagemagick and batch-recolour the icons
