### ISSUE TITLE
[Request] Kstars icon

### ISSUE THREAD

**Issue by barcia** [keeferrourke/la-capitaine-icon-theme#72]
Application: Kstars
Icon name: kstars
Context: Applications
Icon reference:
![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/KStars_icon_oxygen_hicolor.svg/206px-KStars_icon_oxygen_hicolor.svg.png)

**Comment by keeferrourke** [comment]
Closed by #412
