### ISSUE TITLE
A new symbolic link to application-x-rar.svg

### ISSUE THREAD

**Issue by wangxa** [keeferrourke/la-capitaine-icon-theme#78]
The mime type of RAR file in the current release of Fedora has changed to 'application/vnd.rar'. So I think there should be a new symblic link to application-x-rar.svg, named as 'application-vnd.rar.svg', in order to make RAR's icon looks correct.

Thank you.

**Comment by keeferrourke** [comment]
should be fixed as of commit f742509 :)
