### ISSUE TITLE
ownCloud client status icons missing

### ISSUE THREAD

**Issue by keeferrourke** [keeferrourke/la-capitaine-icon-theme#8]
I can't seem to figure out where the ownCloud status icons are found in the hicolor theme, nor the icon names. Images in question seem to be the `state-*.png` images located in the ownCloud git repo at https://github.com/owncloud/client/tree/master/theme/colored

Testing locally, creating status icons called state-whatever don't seem to actually theme the ownCloud applet. I'm going to keep looking into it, but if anyone has any ideas on how to go about doing this, help is appreciated.

**Comment by somniumAeternam** [comment]
Yes, you are right. The missing icons are:

state-ok.svg
state-warning.svg
state-pause.svg
state-information.svg
state-error.svg
state-offline.svg
state-sync.svg

Examples can be found in the Breeze Icon Theme of Plasma 5 (under status -> 22)

**Comment by keeferrourke** [comment]
I'm working on an update to fix this right now; this has been high priority for me for a while, but I hadn't been able to find the appropriate icon names. Thanks a bunch!

**Comment by keeferrourke** [comment]
Added the specified icons in https://github.com/keeferrourke/la-capitaine-icon-theme/commit/ae3095fd8c79403a82a1836e66357905e927611d though I do not see them get applied locally. ownCloud status icons seem not to take effect, though they also do not take effect when I apply the Breeze icon theme either. Hoping my system isn't borked ;)

Can someone test this?

**Comment by keeferrourke** [comment]
Seems I fixed this a while ago -- at least the correct icons show in the system tray on my OpenSUSE box. Ubuntu seems to display the wrong icons, but I will fault this to the packaged version of `owncloud-client` in Ubuntu. Closing.
