### ISSUE TITLE
Icon size problem in System Monitor

### ISSUE THREAD

**Issue by Sadi58** [keeferrourke/la-capitaine-icon-theme#80]
Gnome's System Monitor displays names of running processes with app icons. Iin the absence of one, mime icon for binary files is used, and it seems La Capitaine has a sizing problem here as can be seen in the screenshot below:
![image](https://cloud.githubusercontent.com/assets/6375934/21566616/3dcc3912-cead-11e6-898f-fb530e7c7756.png)

**Comment by keeferrourke** [comment]
fixed. (holy google chrome processes :fearful: )
![screenshot from 2016-12-30 12-14-51](https://cloud.githubusercontent.com/assets/6888381/21569294/9f54cb0a-ce89-11e6-8a7e-4953e7457444.png)
