### ISSUE TITLE
emblem image size (especially for symbolic-link)

### ISSUE THREAD

**Issue by Sadi58** [keeferrourke/la-capitaine-icon-theme#81]
This might be something preferential: I personally prefer emblems to be very small, and/or quite transparent.
This becomes much more of an issue in the case of symlinks as can be seen in the screenshot below (I tend to symlink almost all user files to a Data partition, in addition to a System and Home partition).
No problem if we agree to disagree as well (I'll then do a minor tweak to reduce them to a small image in the bottom-left corner).
![image](https://cloud.githubusercontent.com/assets/6375934/21567714/ef6df544-ceb6-11e6-8766-5db307b3fb06.png)

**Comment by Sadi58** [comment]
Like this ;-)
![image](https://cloud.githubusercontent.com/assets/6375934/21567986/4b558ffa-ceb9-11e6-900e-915384eb7628.png)

**Comment by keeferrourke** [comment]
I'm going to agree to disagree here &ndash; I tend to use detailed list views instead of icon views, and emblems (such as symlinks) at smaller sizes tend to be more difficult to distinguish.

Of course, feel free to make whatever local modifications you want :wink:

**Comment by Sadi58** [comment]
I understand. Such small emblems would be hardly visible in detailed view I guess. I wish the system could indicate symlinks in some other way, e.g. different text color -- until then we have to choose one or the other...
