### ISSUE TITLE
Ubuntu 16.10: Guest Session icon

### ISSUE THREAD

**Issue by Sadi58** [keeferrourke/la-capitaine-icon-theme#82]
Ubuntu's system menu has an item called Guest Session displayed with an avatar image.
This is almost invisible in La Capitaine, although the current user's active status is shown clearly with a white tick in a black circle.
It seems changing the fill color `#ffffff` to `#000000` solves the problem, but I don't know if this may cause problems elsewhere.
![guestsession](https://cloud.githubusercontent.com/assets/6375934/21568131/a5f775c6-ceba-11e6-82ad-ead5f65a23e5.png)
PS: I guess this is the last issue that I'll report this year ;-)
Happy New Year!

**Comment by keeferrourke** [comment]
That icon probably shouldn't be white, you're right. I believe it's used in most places as a generic/default profile icon, so it's hard to get right given there are so many contexts. This said, I'll see what I can do; what's the filename?

**Comment by Sadi58** [comment]
Sorry, I forgot something again in a rush. The file concerned is `./emblems/scalable/avatar-default.svg`

**Comment by keeferrourke** [comment]
This should be fixed with the latest commits for the dark theme. Now the `avatar-default` icon's colour is picked by the configuration script when you run it.

**Comment by Sadi58** [comment]
Great! Thanks :-)
