### ISSUE TITLE
[File type icon] Scala

### ISSUE THREAD

**Issue by strelec** [keeferrourke/la-capitaine-icon-theme#83]
Scala is a modern programming language, but its source files are just marked as text.

![scala logo](https://www.scala-lang.org/resources/img/smooth-spiral.png)

I propose simple red icon with with those three lines.

**Comment by keeferrourke** [comment]
![text-x-scala svg](https://cloud.githubusercontent.com/assets/6888381/21569775/eee5279c-ce8d-11e6-84ef-fe931a26bed1.png)
`text-x-scala.svg`

**Comment by strelec** [comment]
I think this one is really beautiful, maybe a touch bigger icon. Or not. You're the designer.

Thanks!
