### ISSUE TITLE
Some new problems with xfce

### ISSUE THREAD

**Issue by Kalle72** [keeferrourke/la-capitaine-icon-theme#86]
Hello again,

Thanks a lot for repairing the issues with evince, I mentioned in [35](https://github.com/keeferrourke/la-capitaine-icon-theme/issues/35). Aditionally, I am sorry for the long write-up which comes next ;-)

Unfortunately, some new problems occurred (I use xfce): 

1st: The new logon- and logoff-buttons are very small compared to other icons in the status lines
![bild1](https://cloud.githubusercontent.com/assets/14296454/21851644/486ee1be-d810-11e6-9afe-946ee860a705.png)

This issue exists since release 0.4.0 (Compare [35](https://github.com/keeferrourke/la-capitaine-icon-theme/issues/35) for the old look.)

2nd: Xfce uses full-coloured icons for almost everything and not symbolic ones -- at least this is true in many themes: Unfortunately, you exchanged some full-colour icons to symbolic ones. For example, the icons for "show desktop" (picture below) and for "applications-internet" (picture above)
![bild2](https://cloud.githubusercontent.com/assets/14296454/21851768/d2252f3a-d810-11e6-98e6-5703f24e11df.png)

This issue is also still alive with the "multimedia-volume-control" (audio-volume-....svg) icon, the clipman icon (edit-paste.svg), the battery-icons, and the nm-applet-icon. (Compare [35](https://github.com/keeferrourke/la-capitaine-icon-theme/issues/35))
![bild3](https://cloud.githubusercontent.com/assets/14296454/21851785/e579f87c-d810-11e6-8892-b73870408b0f.png)

Therefore, the style recommendations done in [52](https://github.com/keeferrourke/la-capitaine-icon-theme/issues/52) are problematic as they try to circumvent the decision of their theme designer for full-coloured icons. This is because Xfce, or at least the creator of the theme in use, is in the position to exchange full-coloured icons  by symbolic ones. He can do this by exchanging an icon A.svg by A-symbolic.svg If you do this instead by deleting A.svg and bringing A-symbolic.svg into play with the name of the full-coloured icon A.svg, it creates a confusing situation where a theme designer cannot decide if he wishes to use symbolic or full-coloured icons. 

To clear things up, I added some screenshots with the icons of faenza's icons set, to show that the full-coloured ones are in use.
![bild1_gegenbsp](https://cloud.githubusercontent.com/assets/14296454/21852362/1729db42-d813-11e6-884d-48f9bc60e866.png)
![bild2_gegenbsp](https://cloud.githubusercontent.com/assets/14296454/21852370/1c9f368a-d813-11e6-8570-a5c15f4a9d5a.png)
![bild3_gegenbsp](https://cloud.githubusercontent.com/assets/14296454/21852391/1f70a18c-d813-11e6-89af-4164c3458f13.png)

To conclude, I think it is awesome if you add symbolic icons to make the guys from  [52](https://github.com/keeferrourke/la-capitaine-icon-theme/issues/52) happy. But, it would be best to do this alongside with your full-coloured icons (as ....-symbolic.svg). Otherwise, the whole thing will ends up in confusion.  

If then the guys from [52](https://github.com/keeferrourke/la-capitaine-icon-theme/issues/52) wish symbolic icons, they can ask the theme-designer if he likes to switch. 

I hope my write-up is reasonably ;-)
Best regards
Kalle

**Comment by keeferrourke** [comment]
This is a totally reasonable complaint, but something that will take a while to fully address. I suppose you are completely correct, that applications which call for coloured (non-symbolic) icons should be allowed to do so. I'll be working on this to correct the problems in XFCE - of course feel free to ping me if you think I'm being lazy or not properly addressing the issue.

Thanks for pointing this out! I aim to make this thing much more consistent.

**Comment by keeferrourke** [comment]
I did a fair bit up cleaning up and de-duplicating of redundant icons in the latest few commits. If this is still issue, please point which icons in particular are affected, and I'll work from there.

**Comment by keeferrourke** [comment]
I haven't seen any notable issues with various configurations on my XFCE machine. Closing this for now.
