### ISSUE TITLE
keyboard indicator icons

### ISSUE THREAD

**Issue by Sadi58** [keeferrourke/la-capitaine-icon-theme#88]
Scalable status  icons are dark grey, but symbolic status icons are light grey. As a result, for example, the keyboard indicator icon on my Ubuntu top panel doesn't match with the rest.
The others displayed in the menus (network, keyboard, power, sound & session) are not so much of a problem (because all are light grey there) as long as you don't happen to use a window theme that is too close to that light grey.

**Comment by keeferrourke** [comment]
Would you mind adding a screenshot to your issue? I recently recoloured all the `*-symbolic` icons to `#bebebeff` to conform with the GNOME spec.

**Comment by Sadi58** [comment]
This is how it looks like on my Unity top panel:

![image](https://cloud.githubusercontent.com/assets/6375934/22077543/3ddf3700-ddbd-11e6-9bcb-4430a789c1d4.png)

**Comment by keeferrourke** [comment]
Will look into it, stay posted.

**Comment by keeferrourke** [comment]
Seems that there was a redundant set of keyboard indicator icons that snuck their way into `status/symbolic`. I've removed these in commit b926fcd, would you mind pulling the latest commits from master and verify that the colouring has been fixed?

**Comment by Sadi58** [comment]
Yes, it's OK now, thanks! :-)
