### ISSUE TITLE
Small inconsistency for Archive manager

### ISSUE THREAD

**Issue by Elbullazul** [keeferrourke/la-capitaine-icon-theme#91]
I love this theme, however I've found this small bug:
![screenshot_2017-01-24_19-47-29](https://cloud.githubusercontent.com/assets/15310985/22273327/12069d8e-e26e-11e6-8e8c-00e058769301.png)

the folder icon is slightly bigger than the files icons. maybe a small bug, but I though I'd report it anyway.

cheers and thanks for your hard work

P.S. the bug appears in Xubuntu + Cinnamon 3.0 (don't ask why I did it xD) when opening an archive with Archive Manager

**Comment by Ufeldraku** [comment]
Chico, eso se ve muy feo, MUY FEO. CinnXP? Enserio?

**Comment by Elbullazul** [comment]
@Ufeldraku cuando se desarrollan temas a veces no hay opcion. desde el año pasado que no tengo un escritorio bien arreglado con buenos iconos y tema harmonizado

**Comment by Ufeldraku** [comment]
Ah, :v, escribí sin saber. No olvides los temas vimix.

**Comment by keeferrourke** [comment]
Updated all your comments with English translations, sorry if they are poor &mdash; I did not check them thoroughly.

Regarding the actual reported issue, I've just changed some sizing in the theme index &mdash; hopefully this resolves the problem!

**Comment by Ufeldraku** [comment]
They're actually good bro. Lo hiciste bien.

**Comment by Elbullazul** [comment]
@keeferrourke it does indeed fix the bug, thanks for your great effort & attention ;)
