### ISSUE TITLE
[Request] ROSA

### ISSUE THREAD

**Issue by RastaDill** [keeferrourke/la-capitaine-icon-theme#92]
Hello
Please add icon distribution ROSA

Application: Usually the opening global menu
Icon name: distributor-logo.svg
Context: distribution ROSA
Icon reference:
![distributor-logo](https://cloud.githubusercontent.com/assets/12989870/22292627/9ca37da6-e325-11e6-8504-acb6316872c1.png)

**Comment by keeferrourke** [comment]
Can I get the output of the following commands from your ROSA machine?

 * `lsb_release -a`
* `cat /etc/os-release`

**Comment by RastaDill** [comment]
cat /etc/os-release 
NAME="ROSA Desktop Fresh R8"
VERSION="EE 2014.1 Desktop"
ID=rosa
VERSION_ID=2014.1
PRETTY_NAME="ROSA Desktop Fresh R8 EE 2014.1 Desktop"
ANSI_COLOR="1;43"
CPE_NAME="cpe:/o:rosa:rosalinux:2014.1"
HOME_URL="http://www.rosalinux.com/"
BUG_REPORT_URL="http://bugs.rosalinux.ru/"


lsb_release -a
LSB Version:    core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:core-5.0-amd64:core-5.0-noarch:cxx-3.1-amd64:cxx-3.1-noarch:cxx-3.2-amd64:cxx-3.2-noarch:graphics-3.1-amd64:graphics-3.1-noarch:graphics-3.2-amd64:graphics-3.2-noarch:lsb-2.0-amd64:lsb-2.0-noarch:lsb-3.0-amd64:lsb-3.0-noarch:lsb-3.1-amd64:lsb-3.1-noarch:lsb-3.2-amd64:lsb-3.2-noarch:lsb-4.0-amd64:lsb-4.0-noarch:lsb-4.1-amd64:lsb-4.1-noarch:lsb-5.0-amd64:lsb-5.0-noarch
Distributor ID: RosaDesktopFresh
Description:    ROSA Desktop Fresh R8
Release:        2014.1
Codename:       Fresh

**Comment by keeferrourke** [comment]
Here's a preview! Sorry for the wait!

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ![rosa](https://cloud.githubusercontent.com/assets/6888381/22865775/bb0f7cb0-f138-11e6-8d2e-dd79bb87339e.png)
`distributor-logo-rosa.svg`

**Comment by RastaDill** [comment]
Thanks a lot !!!
