### ISSUE TITLE
Icon Request : Atom Beta

### ISSUE THREAD

**Issue by bil-elmoussaoui** [keeferrourke/la-capitaine-icon-theme#94]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Atom Beta | `atom-beta` | `atom-beta.desktop` | ![Atom Beta](http://i.imgur.com/m55T6KR.png)| la-capitaine-icon-theme |

This issue was automatically created using IconRequsts.

**Comment by keeferrourke** [comment]
added in commit https://github.com/keeferrourke/la-capitaine-icon-theme/commit/d6f79aefe4ab2f28c2ac5adf2f648437c373da8d.
