### ISSUE TITLE
Icon Request : Caprine

### ISSUE THREAD

**Issue by bil-elmoussaoui** [keeferrourke/la-capitaine-icon-theme#95]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Caprine | `caprine` | `caprine.desktop` | ![Caprine](http://i.imgur.com/EccZER6.png)| la-capitaine-icon-theme |

This issue was automatically created using IconRequsts.

**Comment by keeferrourke** [comment]
symlinked the existing `messengerfordesktop.svg` to `caprine.svg`
