### ISSUE TITLE
Icon Request : Visual Studio Code

### ISSUE THREAD

**Issue by bil-elmoussaoui** [keeferrourke/la-capitaine-icon-theme#96]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| Visual Studio Code | `visual-studio-code` | `visual-studio-code.desktop` | ![Visual Studio Code](http://i.imgur.com/kSYb4Li.png)| la-capitaine-icon-theme |

This issue was automatically created using IconRequsts.

**Comment by keeferrourke** [comment]
Icon was committed ages ago, but I neglected to update symlinks. This issue is fixed as of commit be60d3d.
