### ISSUE TITLE
Icon Request : WebTorrent

### ISSUE THREAD

**Issue by bil-elmoussaoui** [keeferrourke/la-capitaine-icon-theme#97]
| Application name | Icon name | Desktop file name | Original icon | Theme |
| --- | :-- | :-- | :-- | :-- |
| WebTorrent | `webtorrent-desktop` | `webtorrent-desktop.desktop` | ![WebTorrent](http://i.imgur.com/gRbpAST.png)| la-capitaine-icon-theme |

This issue was automatically created using IconRequsts.

**Comment by keeferrourke** [comment]
Here's a preview of the recently pushed icon:
![webtorrent](https://cloud.githubusercontent.com/assets/6888381/23374603/fa51d0a6-fcf2-11e6-9948-38ebfbb17d1f.png)
&nbsp; `webtorrent.svg`
