### ISSUE TITLE
Icon Request: Meld

### ISSUE THREAD

**Issue by M4he** [keeferrourke/la-capitaine-icon-theme#99]
Application | Icon Name | Context | Original Icon
--- | --- | --- | ----
**Meld** | `meld` | app | ![apps_meld](https://cloud.githubusercontent.com/assets/1408105/22617939/c9d05e36-ead0-11e6-8d71-1d191bb72373.png)

**Comment by strelec** [comment]
This one is pretty important app.

**Comment by keeferrourke** [comment]
@strelec throw some money at me and I'll make this higher priority :wink:
